Sinaomrani patch 1: three line menu in mobile devices
nodejs/nodejs.org pull request #1138
Opened 2017-02-10 18:34 UTC by sinaomrani

add three line menu in mobile devices

2017-02-10 19:24 UTC, fhemberger requested changes

2017-02-10 19:24 UTC, fhemberger commented on layouts/css/page-modules/_header.styl
> +  #Mobile ul
please use lowercase IDs.

2017-02-10 19:25 UTC, fhemberger commented
This doesn't seem to work in Chrome/Mac for me:

<img width="426" alt="bildschirmfoto 2017-02-10 um 20 24 23" src="https://cloud.githubusercontent.com/assets/153481/22840762/06ae72c2-efcf-11e6-9d5c-245dc7335be5.png">

2017-02-11 14:07 UTC, hiroppy requested changes

2017-02-11 14:07 UTC, abouthiroppy commented on layouts/css/page-modules/_header.styl
> +    background-color #333333
Please use this(https://github.com/nodejs/nodejs.org/blob/dd12f6d/layouts/css/_variables.styl#L18).

2017-03-25 06:35 UTC, fhemberger commented
@sinaomrani Hi, can you please check the comments/requested changes?

2017-03-31 21:39 UTC, fhemberger commented
As the patch doesn't work and the committer doesn't seem to work on this any longer, I'm closing this.
@sinaomrani Please feel free to open a new version of this PR, which includes the requested changes.

2017-03-31 21:39 UTC, closed without merging