Fix a broken link in the blog post
nodejs/nodejs.org pull request #1224
Opened 2017-05-13 08:31 UTC by outsideris

This link was broken.

2017-05-13 11:13 UTC, fhemberger requested changes

2017-05-13 11:13 UTC, fhemberger commented on locale/en/blog/wg/diag-wg-update-2017-02.md
> +[Debugging - Getting Started]: https://nodejs.org/en/docs/guides/debugging_getting_started/
Should be https://nodejs.org/en/docs/guides/debugging-getting-started/

2017-05-13 17:36 UTC, outsideris commented
Good point! I updated it.

2017-05-13 17:54 UTC, gibfahn approved these changes

2017-05-13 19:19 UTC, merged

2017-05-13 19:20 UTC, fhemberger commented
Great, thank you! Was it only wrong in English or are other languages affected as well?

2017-05-14 07:39 UTC, outsideris commented
@fhemberger I found during I'm translating the post as Korean. I will check other languages.