nodejs-fr: init french locale
nodejs/nodejs.org pull request #1283
Opened 2017-07-07 14:44 UTC by clakech

Hello all,

Why not a french locale for nodejs.org website to help frenchies to start ?

2017-07-07 14:56 UTC, geoiris commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées sorties non bloquantes ce qui le rend
entrées/sorties ?

2017-07-07 14:58 UTC, geoiris approved these changes

2017-07-07 14:59 UTC, lborie commented on locale/fr/site.json
> +            "text": "Annoncements"
Annonces

2017-07-07 15:01 UTC, clakech commented on locale/fr/site.json
> +            "text": "Annoncements"
merki

2017-07-07 15:01 UTC, clakech commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées sorties non bloquantes ce qui le rend
merki

2017-07-07 15:02 UTC, clakech commented on locale/fr/site.json
> +            "text": "Annoncements"
il me faut un petit 👍 en réaction sur la PR please ^^

2017-07-07 15:02 UTC, clakech commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées sorties non bloquantes ce qui le rend
il me faut un petit 👍 en réaction sur la PR please ^^ @geoiris

2017-07-07 15:04 UTC, lborie approved these changes

2017-07-07 15:06 UTC, vdeturckheim submitted a review, later dismissed

2017-07-07 15:07 UTC, vdeturckheim commented
cc @nodejs/nodejs-fr

2017-07-07 16:01 UTC, abenhamdine requested changes

2017-07-07 16:01 UTC, abenhamdine commented on locale/fr/site.json
> +    "scrollToTop": "Faire définler en haut",
défiler

2017-07-07 16:56 UTC, clakech commented on locale/fr/site.json
> +    "scrollToTop": "Faire définler en haut",
thanks

2017-07-07 16:56 UTC, clakech commented on locale/fr/site.json
> +    "scrollToTop": "Faire définler en haut",
fixed && pushed

2017-07-07 17:40 UTC, harf18 requested changes

2017-07-07 17:40 UTC, harf18 commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées/sorties non bloquantes, ce qui le rend léger et efficace. L'écosystème de logiciels de Node.js, [npm](https://www.npmjs.com/), est le
librairies => bibliothèques ?

2017-07-07 19:22 UTC, clakech commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées/sorties non bloquantes, ce qui le rend léger et efficace. L'écosystème de logiciels de Node.js, [npm](https://www.npmjs.com/), est le
Both are ok, what others think about that?

2017-07-07 21:39 UTC, GromNaN commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées/sorties non bloquantes, ce qui le rend léger et efficace. L'écosystème de logiciels de Node.js, [npm](https://www.npmjs.com/), est le
"librairies" for code libraries is an Anglicism that sounds very familiar, like "open source".

2017-07-07 21:55 UTC, GromNaN reviewed
Not using accents on capital letters is considered as an orthographic mistake.

2017-07-07 21:55 UTC, GromNaN commented on locale/fr/site.json
> +            "text": "Compte rendus des réunions TSC Node.js"
"Compte-rendus"
https://fr.wiktionary.org/wiki/compte-rendus

2017-07-07 21:55 UTC, GromNaN commented on locale/fr/site.json
> +        "text": "A propos",
"À propos"

2017-07-07 21:55 UTC, GromNaN commented on locale/fr/site.json
> +             "text": "A la une"
"À la Une"

2017-07-07 21:55 UTC, GromNaN commented on locale/fr/site.json
> +            "text": "Initiatives Educatives"
"Initiatives éducatives"

2017-07-07 21:55 UTC, GromNaN commented on locale/fr/site.json
> +    "blog"       : { "link": "blog",            "text": "Nouvelles" },
"Actualités"

2017-07-08 00:55 UTC, vdeturckheim commented
I dismissed my review based on @GromNaN comments.

2017-07-08 08:44 UTC, cedced19 commented on locale/fr/site.json
> +            "text": "Compte rendus des réunions TSC Node.js"
It's a misspelling: "Comptes rendus"

2017-07-08 08:50 UTC, cedced19 commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées/sorties non bloquantes, ce qui le rend léger et efficace. L'écosystème de logiciels de Node.js, [npm](https://www.npmjs.com/), est le
I'm agree with @harf18. "bibliothèques" is the correct form.
If we have a word to translate english in a easy way, we should use this.
"open source" can be translate to "code source ouvert" but in some cases this translation is bad.
**To put it in a nutshell "open source"≠"code source ouvert" but "librairies" = "bibliothèques"**.

2017-07-08 09:35 UTC, clakech commented on locale/fr/index.md
> +Node.js utilise un modèle basé sur l'événementiel et des entrées/sorties non bloquantes, ce qui le rend léger et efficace. L'écosystème de logiciels de Node.js, [npm](https://www.npmjs.com/), est le
fixed && pushed @cedced19  @GromNaN @harf18

2017-07-08 09:36 UTC, clakech commented on locale/fr/site.json
> +            "text": "Compte rendus des réunions TSC Node.js"
fixed && pushed

2017-07-08 09:36 UTC, clakech commented on locale/fr/site.json
> +        "text": "A propos",
fixed && pushed

2017-07-08 09:36 UTC, clakech commented on locale/fr/site.json
> +             "text": "A la une"
fixed && pushed

2017-07-08 09:36 UTC, clakech commented on locale/fr/site.json
> +            "text": "Initiatives Educatives"
fixed && pushed

2017-07-08 09:36 UTC, clakech commented on locale/fr/site.json
> +    "blog"       : { "link": "blog",            "text": "Nouvelles" },
fixed && pushed

2017-07-08 09:37 UTC, clakech commented
Add a commit with correction from reviewers requested changes @vdeturckheim

2017-07-08 09:53 UTC, FKSI commented on locale/fr/site.json
> +            "text": "Code de Conduite"
Code de conduite

2017-07-08 09:55 UTC, FKSI commented on locale/fr/site.json
> +            "text": "ES6 et au delà"
au-delà

2017-07-08 15:23 UTC, clakech commented on locale/fr/site.json
> +            "text": "ES6 et au delà"
Done

2017-07-08 15:23 UTC, clakech commented on locale/fr/site.json
> +            "text": "Code de Conduite"
Done

2017-07-08 16:44 UTC, cedced19 approved these changes

2017-07-08 18:09 UTC, FKSI approved these changes

2017-07-08 19:21 UTC, harf18 approved these changes

2017-07-08 19:50 UTC, slester requested changes

2017-07-08 19:50 UTC, slester commented on locale/fr/site.json
> +          "text": "Evènements"
-> Évènements

2017-07-08 19:50 UTC, slester commented on locale/fr/site.json
> +            "text": "Gouvernance Technique"
Ici (et autre part) le deuxième mot est en majuscule, mais en bas vous avez "Initiatives éducatives" -- il faut les harmoniser.

2017-07-08 19:50 UTC, slester commented on locale/fr/index.md
> +  other-downloads: Autres Téléchargements
Majusculisation irrégulière (voir le commentaire en bas)

2017-07-08 19:50 UTC, slester commented on locale/fr/index.md
> +  tagline-current: Dernières Fonctionnalités
Majusculisation irrégulière partout dans ce fichier (voir le commentaire en bas)

2017-07-08 20:23 UTC, clakech commented
@slester thanks, pushed

2017-07-09 09:58 UTC, fhemberger commented
@GromNaN @slester @abenhamdine @vdeturckheim Can you please set a 👍 /👎  for your review, so we know if this change is good to merge? Thx!

2017-07-09 10:09 UTC, abenhamdine approved these changes

2017-07-09 15:46 UTC, slester commented
Oops, sorry, I thought I did!

2017-07-09 15:46 UTC, slester approved these changes

2017-07-09 20:21 UTC, clakech commented
7 reviewers approval, 6 👍 and even 1 🎉. Seems like we will have a nodejs.org french website very soon 😀

2017-07-10 04:32 UTC, fhemberger commented
Incredible, merci bien à tous!

2017-07-10 04:32 UTC, merged