Simplify web app Dockerfile
nodejs/nodejs.org pull request #1302
Opened 2017-07-19 13:40 UTC by LinusU

1) Remove redundant call to `mkdir -p` since the `WORKDIR` command creates the directory.
2) Uses relative targets in the `COPY` command to leverage the previous call to `WORKDIR`

2017-07-21 04:16 UTC, fhemberger requested changes
A little nitpicking, otherwise LGTM.

2017-07-21 04:16 UTC, fhemberger commented on locale/en/docs/guides/nodejs-docker-webapp.md
> +COPY package.json ./
`./` not required `.` should be enough

2017-07-21 04:16 UTC, fhemberger commented on locale/en/docs/guides/nodejs-docker-webapp.md
> +COPY package.json ./
same here

2017-07-24 13:28 UTC, fhemberger approved these changes

2017-07-24 13:28 UTC, merged

2017-07-24 13:28 UTC, fhemberger commented
Thank you!

2017-07-24 16:33 UTC, LinusU commented
Thanks for fixing the nitpicks! been busy packing my apartment into boxes these last few days 🙈