Add SafetyCulture as silver foundation member
nodejs/nodejs.org pull request #1309
Opened 2017-07-25 18:26 UTC by hackygolucky

Adds logo and link to new member, including translated pages that exist.

2017-07-25 23:17 UTC, stevemao approved these changes

2017-07-25 23:19 UTC, stevemao requested changes

2017-07-25 23:19 UTC, stevemao commented on locale/uk/foundation/members.md
>    <img alt="yld!" class="memberlogo" src="/static/images/foundation/yldLogo.png" />
You removed the `!` in en but not here. Should we keep the `!` or remove it everywhere?

2017-07-27 17:29 UTC, hackygolucky commented on locale/uk/foundation/members.md
>    <img alt="yld!" class="memberlogo" src="/static/images/foundation/yldLogo.png" />
The ! weren't consistent. The only other alt that held it was Yahoo so I assumed it was literally a typo.

2017-07-28 05:38 UTC, lpinca approved these changes

2017-07-28 06:23 UTC, merged