Update zh-cn translate for index.md
nodejs/nodejs.org pull request #1351
Opened 2017-09-04 18:14 UTC by undownding

2017-09-04 18:41 UTC, fhemberger commented
/cc @nodejs/nodejs-cn please review

2017-09-05 00:18 UTC, laosb approved these changes
looks good to me

2017-09-05 01:38 UTC, Lellansin approved these changes
LGTM

2017-09-05 02:52 UTC, JacksonTian commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包管理器，[npm](https://www.npmjs.com/)，是目前世界上最大的开源项目管理包管理工具。
开源项目管理包管理工具。

2017-09-05 05:43 UTC, undownding commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包管理器，[npm](https://www.npmjs.com/)，是目前世界上最大的开源项目管理包管理工具。
这就改

2017-09-05 05:48 UTC, undownding commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包管理器，[npm](https://www.npmjs.com/)，是目前世界上最大的开源项目管理包管理工具。
这句话斟酌了半天，该如何翻译比较合适？

package ecosystem 在这里结合上下文来看指的是 npm 本身还是整个以 npm 为首的生态环境？

2017-09-05 05:49 UTC, laosb commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包管理器，[npm](https://www.npmjs.com/)，是目前世界上最大的开源项目管理包管理工具。
我感觉可以直接翻译为「包生态系统」？

2017-09-05 10:47 UTC, XadillaX reviewed
Some nits.

Refs: https://github.com/sparanoid/chinese-copywriting-guidelines

2017-09-05 10:47 UTC, XadillaX commented on locale/zh-cn/index.md
> +  newsletter-postfix: ", Node.js 官方的新闻周报。"
why not use '，' to instead of ','?

2017-09-05 10:47 UTC, XadillaX commented on locale/zh-cn/index.md
>  Node.js®是一个基于[Chrome V8 引擎](https://developers.google.com/v8/)的 JavaScript 运行时。
Maybe we should add a space after '&reg;'.

2017-09-05 10:47 UTC, XadillaX commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
Maybe we can use '它的包生态系统'?

2017-09-05 10:47 UTC, XadillaX commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
```markdown
它的包生态系统 [npm](...) 是目前实际上最大的开源库生态系统。
```

2017-09-05 10:50 UTC, XadillaX commented on locale/zh-cn/index.md
>  Node.js®是一个基于[Chrome V8 引擎](https://developers.google.com/v8/)的 JavaScript 运行时。
Maybe we should add a space after '于' too.

2017-09-06 04:39 UTC, undownding commented
@XadillaX All nits has fixed. Please review.

2017-09-06 04:39 UTC, undownding commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
参考了原文发现本身就是上下文不连贯，还是以尊重原文为主。

@laosb

2017-09-06 04:39 UTC, undownding commented on locale/zh-cn/index.md
> +  newsletter-postfix: ", Node.js 官方的新闻周报。"
注册 Node.js Everywhere,  Node.js 官方的新闻周报。

注册 Node.js Everywhere，Node.js 官方的新闻周报。

I think the frist one is better : )

2017-09-06 04:42 UTC, laosb commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。Node.js 的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
嗯有道理

2017-09-06 04:45 UTC, laosb commented on locale/zh-cn/index.md
> +  newsletter-postfix: ", Node.js 官方的新闻周报。"
@undownding 我认为这属于句中的分隔符，逗号前后尽管都是英文，但是是两个专有名词，分属于两个子句，所以应当采用全角逗号。

2017-09-06 06:51 UTC, XadillaX commented on locale/zh-cn/index.md
> +  newsletter-postfix: ", Node.js 官方的新闻周报。"
+1 with @laosb.

2017-09-06 07:05 UTC, yorkie requested changes

2017-09-06 07:05 UTC, yorkie commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。它的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
建议不要加最后最大，避免引起其他不必要的问题～

2017-09-07 04:01 UTC, undownding commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。它的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.

仔细斟酌的话原文是有地方是上下不连贯以及奇怪的，出于翻译的信达雅原则我认为还是应该以尊重原文为先。

原先文案有问题的话我们应该开 issue 提出，此 PR 应以“在保证尊重原意的基础上尽量表达得好”为审查标准。

2017-09-07 04:06 UTC, undownding commented on locale/zh-cn/index.md
> +  newsletter-postfix: ", Node.js 官方的新闻周报。"
我今天才看到，等下面得那个问题讨论得出结论后再一块修复。

2017-09-11 06:37 UTC, fhemberger commented
@undownding Hi, what's the status of this PR? @yorkie Can you please set your review status as soon as everything is resolved?

2017-09-20 07:13 UTC, undownding commented
@fhemberger need more discuss but no one join it

2017-09-22 05:50 UTC, JacksonTian commented on locale/zh-cn/index.md
> +Node.js 使用高效、轻量级的事件驱动、非阻塞 I/O 模型。它的包生态系统，[npm](https://www.npmjs.com/)，是目前世界上最大的开源库生态系统。
尊重事实 > 尊重广告法

2017-09-22 05:51 UTC, JacksonTian approved these changes

2017-09-25 07:43 UTC, lpinca commented
@yorkie can this land?

2017-10-03 02:12 UTC, XadillaX requested changes

2017-10-03 02:12 UTC, XadillaX commented on locale/zh-cn/index.md
> +  newsletter-postfix: ", Node.js 官方的新闻周报。"
the comma still need to be modified.

2017-10-03 02:20 UTC, fhemberger commented
Ok, as @yorkie doesn't reply and this has already been open for a month: I'd love to land this change. @undownding @XadillaX Could you please work out the last little nit so we can merge this?

If there are further changes/refinements required, please open a follow up PR.

2017-10-03 06:13 UTC, yorkie approved these changes

2017-10-06 19:51 UTC, fhemberger commented
Ok, I'm merging this change. If there are still details to discuss, please open another PR.

Thanks for the update! :+1:

2017-10-06 19:51 UTC, merged