Using curl behind proxy: for nodejs#1371
nodejs/nodejs.org pull request #1372
Opened 2017-09-20 06:42 UTC by peter-kehl

2017-09-20 07:28 UTC, fhemberger requested changes

2017-09-20 07:28 UTC, fhemberger commented on locale/en/download/package-manager.md
> +When running ```curl``` behind a proxy, invoke it as ```curl --proxy http://proxy.racp.edu.au:3128```.
Hmm, not sure if this change is really required, I guess people used to `curl`ing behind a proxy usually now their required config switches. Thoughts?

a) Please use singleticks for inline code.
b) Maybe you should use a more generic proxy URL (something like `http://<hostname>:<port>` would be okay as well).

2017-09-21 06:46 UTC, peter-kehl commented
Hi Frederic,

This will save time even for people who have used `curl` behind a proxy. That's because of 2 stage installation, where in the first step `curl` downloads a script, which invokes `curl` again. That second step can be confusing.

a) changed to singleticks for inline code
b) made the instruction proxy-generic

2017-09-21 07:24 UTC, silverwind commented
Honestly, I see no need for this. curl honours environment variables like HTTP_PROXY, which is generally the preferred method to enable proxy usage system-wide.

2017-10-03 02:24 UTC, fhemberger commented
Personally, I agree with @silverwind, but would like to hear @nodejs/website's thoughts.

2017-10-03 05:55 UTC, lpinca commented
I also think that the usual way is to use the `HTTP_PROXY` env variable. I'm -0 on adding this.

2017-10-05 04:30 UTC, closed without merging

2017-10-05 04:31 UTC, fhemberger commented
Okay, I've closed this issue. But thanks for your PR, sorry it didn't work out this time.