French translation of Downloads page
nodejs/nodejs.org pull request #1550
Opened 2018-01-10 18:02 UTC by oncletom

Pardon my French! As part of the writing of [this book][], I wanted to offer the french audience a translated Downloads page :slightly_smiling:

The PR has two commits:

- one with the french translations of download/current and download pages
- one with modified partials (primary-download-matrix.hbs and secondary-download-matrics.hbs) to extract strings and make them translatable

The latter contains default strings (in English and in French) for the new translation keys.

I was a bit confused by the location of translation strings (sometimes in locale/*/site.json, sometimes directly in locale/**/*.md).
I am happy to relocate them if I did not do the right move.

[this book]: https://github.com/oncletom/nodebook

2018-01-10 18:04 UTC, oncletom commented on layouts/partials/secondary-download-matrix.hbs
> +        <td colspan="6"><a href="https://nodejs.org/dist/{{version.node}}/node-{{version.node}}-linux-ppc64le.tar.xz">64-bit</a></td>
Oh yeah and I removed the ` le` suffix. It felt like a typo.

2018-01-10 18:05 UTC, daxlab commented
@oncletom thanks for the effort.

2018-01-10 19:24 UTC, Tiriel reviewed
Merci beaucoup! Thanks for the effort!
Few nits to correct, but I'll call for @nodejs/nodejs-fr to check the rest!

2018-01-10 19:24 UTC, Tiriel commented on locale/fr/download/current.md
> +    current: Actuelle
J'aurais plutôt dit "Courante". Plus littéral mais aussi plus juste AMHA.

2018-01-10 19:24 UTC, Tiriel commented on locale/fr/download/current.md
> +    tagline-lts: Recommandé pour la plupart des utilisateurs
"Recommandée", au féminin plutôt, puisqu'on parle d'une version?

2018-01-10 19:24 UTC, Tiriel commented on locale/fr/download/current.md
> +        Téléchargez le code source de Node.js ou pour votre système d'exploitation et commencez à développer dès aujourd'hui.
La formulation me paraît étrange ici. Il ne manque pas un mot?

2018-01-10 19:24 UTC, Tiriel commented on locale/fr/download/current.md
> +    currentVersion: Dernière version Actuelle
Même chose que plus haut, "Courante"?

2018-01-10 19:24 UTC, Tiriel commented on locale/fr/download/current.md
> +        Les membres de la communauté Node.js maintiennent des installeurs de Node.js pour d'autres plate-formes. Veuillez noter que ces téléchargements ne sont pas maintenus par l'équipe principale d
"qualité" me semble potentiellement un peu péjoratif. Mais je sèche un peu.

2018-01-10 19:24 UTC, Tiriel commented on locale/fr/download/index.md
> +---
Mêmes remarques que pour le précédent fichier :slightly_smiling_face:

2018-01-10 19:52 UTC, oncletom commented on locale/fr/download/current.md
> +        Téléchargez le code source de Node.js ou pour votre système d'exploitation et commencez à développer dès aujourd'hui.
Il y a un mot en trop surtout :-) "ou"

2018-01-10 19:54 UTC, oncletom commented on locale/fr/download/current.md
> +        Les membres de la communauté Node.js maintiennent des installeurs de Node.js pour d'autres plate-formes. Veuillez noter que ces téléchargements ne sont pas maintenus par l'équipe principale d
Yes. La version anglaise est _the same build level_. Tu penses à un autre terme lié à "niveau" ? (chais pas, "niveau" ça me paraît bizarre…).

2018-01-10 19:58 UTC, oncletom commented on locale/fr/download/current.md
> +    currentVersion: Dernière version Actuelle
Je me suis contenté de reprendre la traduction existante, Cf. ce qu'on trouvera déjà ici : https://nodejs.org/fr/

En regardant d'autres sites parlant de "version", je vois aussi bien "Courant" qu'Actuelle.

2018-01-10 19:58 UTC, oncletom commented on locale/fr/download/current.md
> +    tagline-lts: Recommandé pour la plupart des utilisateurs
Là aussi je me suis basé sur ce qu'il y avait déjà de traduit sur la page d'accueil : https://nodejs.org/fr/

2018-01-10 20:00 UTC, Tiriel commented on locale/fr/download/current.md
> +    tagline-lts: Recommandé pour la plupart des utilisateurs
Au temps pour moi, on peut justifier qu'on parle d'un téléchargement!

2018-01-11 09:26 UTC, Tiriel commented on locale/fr/download/current.md
> +        Les membres de la communauté Node.js maintiennent des installeurs de Node.js pour d'autres plate-formes. Veuillez noter que ces téléchargements ne sont pas maintenus par l'équipe principale d
C'est ce que j'ai vu oui, mais niveau me paraît aussi tendancieux en français. Stabilité?

2018-01-11 09:32 UTC, oncletom commented on locale/fr/download/current.md
> +        Les membres de la communauté Node.js maintiennent des installeurs de Node.js pour d'autres plate-formes. Veuillez noter que ces téléchargements ne sont pas maintenus par l'équipe principale d
Ouais, ou _même niveau de support_ ?

2018-01-11 09:37 UTC, Tiriel commented on locale/fr/download/current.md
> +        Les membres de la communauté Node.js maintiennent des installeurs de Node.js pour d'autres plate-formes. Veuillez noter que ces téléchargements ne sont pas maintenus par l'équipe principale d
Ca me semble mieux oui!

2018-01-11 09:45 UTC, oncletom commented on locale/fr/download/current.md
> +        Les membres de la communauté Node.js maintiennent des installeurs de Node.js pour d'autres plate-formes. Veuillez noter que ces téléchargements ne sont pas maintenus par l'équipe principale d
Top. On part sur ça :-) merci pour ton aide !

2018-01-11 16:16 UTC, cedced19 requested changes

2018-01-11 16:16 UTC, cedced19 commented on locale/fr/download/current.md
> +    display-hint: Afficher les téléchargement pour Node
téléchargement**s**

2018-01-11 16:16 UTC, cedced19 commented on locale/fr/download/index.md
> +    display-hint: Afficher les téléchargement pour Node
téléchargement**s**

2018-01-11 17:58 UTC, oncletom commented
Okay folks I have made changes as you spotted issues. How is it now?

Is it good enough to be merged?

2018-01-25 03:47 UTC, fhemberger commented
/cc @nodejs/nodejs-fr @cedced19 Please do a final review, so we can merge this.

2018-01-25 11:23 UTC, cedced19 commented
For me it's good!

2018-02-11 18:54 UTC, fhemberger commented
Sorry, totally forgot about this. Merging now, thank you!

2018-02-11 18:54 UTC, merged