Update supported versions
nodejs/nodejs.org pull request #1832
Opened 2018-10-10 08:18 UTC by fhemberger

Updated supported versions, as mentioned in #1831.

However, I noticed that the two documents seem to be drifting apart in other sections. So we should really think about how we want to handle this in the future. That's also the reason I didn't update all distros.

/cc @bnb @rvagg Any ideas on how to proceed?

2018-10-10 14:11 UTC, vsemozhetbyt commented on locale/en/download/package-manager.md
> +* **i386** (32-bit)—**not available for Node.js 10 and later**
Nit: let's use m-dash or dash with spaces consistently (compare addition below)?

2018-10-10 14:24 UTC, refack commented on locale/en/download/package-manager.md
> +* **Ubuntu 17.10** (Artful Aardvark)
17.10 went EOL, so it not supported anymore...

2018-10-10 14:26 UTC, refack commented
I'm kinda in favor of just linking instead of C&P content (for example next week we're gonna have node v11 as well)...
Maybe just leave a line about supported (as in not EOL RE https://github.com/nodejs/Release/issues/359) node versions on supported distro versions.

2018-10-25 07:58 UTC, fhemberger commented
Okay, I removed the whole Debian/Ubuntu/RHEL section and replaced it with a link to the NodeSource repo.

We still need translations/updated for those pages:
- [ ] @nodejs/nodejs-es 
- [ ] @nodejs/nodejs-ja 
- [ ] @nodejs/nodejs-ko 
- [ ] @nodejs/nodejs-uk 
- [ ] @nodejs/nodejs-cn 
- [ ] @nodejs/nodejs-tw

2018-10-25 12:06 UTC, academo commented
I can help with the Spanish translation

2018-10-25 12:46 UTC, academo requested changes

2018-10-25 12:46 UTC, academo commented on locale/es/download/package-manager.md
> +[Official Node.js binary distributions](https://github.com/nodesource/distributions/blob/master/README.md) are provided by NodeSource.
```suggestion
[Las distribuciones de binarios oficiales de Node.js](https://github.com/nodesource/distributions/blob/master/README.md) son proporcinadas por NodeSource.
```

2018-10-25 13:21 UTC, refack approved these changes

2018-10-25 14:31 UTC, fhemberger commented
@academo Thanks!

2018-10-25 20:30 UTC, vsemozhetbyt commented
[uk/download/package-manager.md](https://github.com/nodejs/nodejs.org/blob/master/locale/uk/download/package-manager.md) has not translated text, it seems it's just a placeholder. It can be deleted or replaced by the [en/download/package-manager.md](https://github.com/nodejs/nodejs.org/blob/master/locale/en/download/package-manager.md).

2018-10-26 03:34 UTC, fhemberger commented
Great, only two more to go.

2018-10-28 03:37 UTC, fhemberger commented
I also added missing Android and Solus descriptions to es/ja/ko (untranslated).
Those can be translated in a separate PR as well, as I think it's more important to have the content up to date.

2018-10-28 03:38 UTC, merged

2018-10-28 03:38 UTC, fhemberger commented
Thank you all for your help!