nodejs-ca: Update Get Involved
nodejs/nodejs.org pull request #1838
Opened 2018-10-13 22:50 UTC by Tsuna-mi

This PR add Nodeiflux to Get Involved to catalan version. 
All updates follow English file version.
To review it we need some help from native catalan speakers. Thanks!

(cc @kvhuaxa @franher @axarrafols @jose-lara)
Related with #1766

2018-10-14 10:21 UTC, ghost reviewed
English part is well, however I'm not familiar with ca……Maybe this need another one to check with :)

2018-10-14 13:34 UTC, Tsuna-mi commented
I'll try to get colleagues help this week ;)

2018-10-15 13:26 UTC, luisprieto requested changes

2018-10-15 13:26 UTC, luisprieto commented on locale/ca/get-involved/index.md
> +- La [llista Github de qüestions](https://github.com/nodejs/node/issues) és el lloc per discutir les característiques del nucli de Node.js.
I find "incidència" a better translation of "issue", so I'd put here:
`La [llista d'incidències de Github]`

2018-10-15 13:26 UTC, luisprieto commented on locale/ca/get-involved/index.md
> +- [Nodeiflux](https://discordapp.com/invite/vUsrbjd) és una comunitat amigable de desenvolupadors de backend amb Node que es recolzen mútuament en Discord.
`... es recolzen mútuament a Discord.`

2018-10-15 13:43 UTC, luisprieto approved these changes

2018-10-15 14:10 UTC, franher reviewed
@Tsuna-mi thank you for the contribution 

I did a couple of suggestions :)

2018-10-15 14:10 UTC, franher commented on locale/ca/get-involved/index.md
> +- [Nodeiflux](https://discordapp.com/invite/vUsrbjd) és una comunitat amigable de desenvolupadors de backend amb Node que es recolzen mútuament a Discord.
`de backend amb Node.js`

I think we should use always the same name for Node.js :)

2018-10-15 14:10 UTC, franher commented on locale/ca/get-involved/index.md
> +- [Grup de Facebook en espanyol per Node.js](https://www.facebook.com/groups/node.es/)
`Grup de Facebook en espanyol de Node.js` I find the `de` better than `per`here.

2018-10-15 14:14 UTC, Tsuna-mi commented on locale/ca/get-involved/index.md
> +- [Nodeiflux](https://discordapp.com/invite/vUsrbjd) és una comunitat amigable de desenvolupadors de backend amb Node que es recolzen mútuament a Discord.
I just translate from the original document in english... where is approved/published just with 'Node'
I am agree with you and consistency using Node.js. 

More opinions?

2018-10-16 08:05 UTC, franher approved these changes

2018-10-22 15:27 UTC, fhemberger commented on locale/ca/get-involved/index.md
> +- [Nodeiflux](https://discordapp.com/invite/vUsrbjd) és una comunitat amigable de desenvolupadors de backend amb Node que es recolzen mútuament a Discord.
Yes, please use "Node.js". Should be fixed in the English version as well. ;)

2018-10-22 16:10 UTC, Tsuna-mi commented
PR ready to merge
Thanks for your review @luisprieto and @franher  :)

2018-10-22 16:39 UTC, merged

2018-10-22 16:39 UTC, fhemberger commented
Thanks everyone!