zh-cn: add release schedule
nodejs/nodejs.org pull request #1892
Opened 2018-11-09 00:32 UTC by ZYSzys

Refs: #1890 

/cc @nodejs/nodejs-cn

2018-11-09 00:55 UTC, willin requested changes

2018-11-09 00:55 UTC, willin commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
It reads awkwardly. but i have no idea how to figure it out. @Maledong 

<img width="831" alt="wx20181109-084422 2x" src="https://user-images.githubusercontent.com/1890238/48236431-231af380-e3fd-11e8-98fe-442bf981d0ab.png">

p.s. 注意一下前人翻译的术语。 `长期维护版`

2018-11-09 01:03 UTC, ZYSzys commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
对于这两个词的翻译我也有点纠结，翻译还是保留原版英文，等待你们提供修改意见

2018-11-09 02:15 UTC, Lellansin commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
稳定版 & 最新版？

2018-11-09 02:20 UTC, willin commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
因为都是在 LTS 下分的两个阶段，所以感觉似乎。。。我没找到合适的词来形容

2018-11-09 02:40 UTC, stevemao commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
> 稳定版 & 最新版？

We had a long discussion before on how to call "Current" version. The word "Current" is the out come of the discussion and so I don't think we should have the same discussion again when we translate. So I think we can keep the direct translation here:

`11.1.0 当前版 最新功能`

2018-11-09 03:20 UTC, ZYSzys commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
`current` => `当前版`, 那么 `Maintenance LTS` 和 `Active LTS` 应该如何翻译呢 ？

`Maintenance LTS` => `当前版` ?
`Active LTS` => `最新功能` ?

2018-11-09 03:56 UTC, stevemao commented on locale/zh-cn/about/releases.md
> +  active: '长期支持版(活跃)'
Your current changes looks fine to me:

```
maintenance: '长期支持版(维护)'
active: '长期支持版(活跃)'
```

2018-11-09 12:02 UTC, stevemao approved these changes

2018-11-09 16:59 UTC, willin commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
注意是 `长期维护版`

2018-11-09 17:20 UTC, ZYSzys commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
OK，我明早改一下。
那下面那个 active 呢，还需要改吗？

2018-11-09 22:56 UTC, stevemao commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
So this becomes `长期维护版(维护)`? Sounds a bit weird.

2018-11-10 01:59 UTC, ZYSzys commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
> maintenance: '长期维护版'
  active: '长期支持版(活跃)'

这样 ?

2018-11-10 02:26 UTC, willin commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
是的。一开头就提到了。。。但是术语应该是固定的。

其中 active 也应该是 `长期维护版` 与其他页面上保持一致。。。


- 长期维护版（维护中）
- 长期维护版（活跃中）

看着是怪怪的

2018-11-10 02:53 UTC, ZYSzys commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
其实有点感觉 `LTS` 是不是翻译为 `长期支持版` 比较合适 ? 难以抉择😅。。。
![screen shot 2018-11-10 at 10 47 23 am](https://user-images.githubusercontent.com/23313266/48296804-3b127600-e4d6-11e8-9d69-3c4025746adb.png)

2018-11-10 03:00 UTC, stevemao commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
I honestly think `长期支持版` is a lot better :) Just my 2c

2018-11-10 03:02 UTC, willin commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
那就顺带着把其他页面上的也替换为这个？

2018-11-10 03:08 UTC, ZYSzys commented on locale/zh-cn/about/releases.md
>    maintenance: '长期支持版(维护)'
👌

2018-11-10 04:11 UTC, stevemao commented
@ZYSzys I think you can take the last commit to a new PR against the master branch. This PR is against `feature/lts-release-plan` which might take longer to merge I think.

2018-11-10 04:13 UTC, stevemao commented
also `最新发布版` should probably be `当前版` (it was called `latest` before but changed).

2018-11-10 04:14 UTC, stevemao commented on locale/zh-cn/index.md
>    other-current-downloads: 其它尝鲜版下载
This should also be call `其它当前版下载`

2018-11-10 06:55 UTC, ghost reviewed
1、LTS的全称是“Long Term Support”，翻译成“长期支持”不错。

2、Maintance LTS：根据时间表看，说明这个LTS版本不是作为在首页上出现的主要版本推广（不是主推的，但是处于维护阶段）。
3、Active LTS：活跃长期支持版（推荐的，在Nodejs主页上显示的）。

根据实际情况使用下来，建议意译更好：

1）Active LTS：长期支持版（主推）
2）Maintance LTS：长期维护版

@stevemao ：Active LTS，从字面上翻译的确是“活跃的长期支持版”，但是我觉得这样翻译太过于直白，而且不符合中国人的思维习惯——其实“活跃的长期支持版”意味着这个版本是当前在Nodejs主页上主要推荐的，所以我大胆地翻译成“主推长期支持版”。

至于Maintance LTS，其实已经是过了“保鲜期”到了“维护期”（参考Nodejs10.X作为主推版之后，Nodejs8.x进入了维护阶段）。所以为了区分两者，建议后者翻译成“长期维护版”，没有必要再把“支持”翻译出来了。

2018-11-10 07:42 UTC, willin approved these changes

2018-11-10 08:09 UTC, ZYSzys commented
@Maledong 改好了，现在这样如何 ？

2018-11-10 11:15 UTC, Maledong commented
稍等，让其它人看看，@stevemao？

2018-11-11 00:08 UTC, stevemao commented
Thanks! I'm neutral on these :)

2018-11-11 02:05 UTC, merged

2018-11-11 06:50 UTC, fhemberger commented
Thank you!