Update built-in debugger link to latest
nodejs/nodejs.org pull request #1913
Opened 2018-11-26 11:45 UTC by ZYSzys

Update built-in debugger link to the latest in [guides/debugging-getting-started](https://nodejs.org/en/docs/guides/debugging-getting-started/).

2018-11-26 12:18 UTC, fhemberger approved these changes

2018-11-26 16:06 UTC, refack commented on locale/en/docs/guides/debugging-getting-started.md
>  Start `node debug script_name.js` to start your script under Node's builtin
So if you're here, there are two other changes the should be done:
1. Remove the next section (`#### node-inspector`) [REF](https://github.com/node-inspector/node-inspector#overview)
2. replace `debug` with `inspect`
```suggestion
Run `node inspect script_name.js` to start your script under node's builtin
```

And similar in L248

2018-11-26 16:11 UTC, richardlau commented on locale/en/docs/guides/debugging-getting-started.md
> -#### [Built-in Debugger](https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html)
This section is specifically referring to the Legacy Debugger though, which is different from the Inspector-based one. I don't think this link should be changed (the latest docs point to the Inspector-based debugger client while the `v6.x` docs refer to the legacy one).

cc @nodejs/diagnostics

2018-11-27 15:06 UTC, ZYSzys commented
Find that it's indeed the `Legacy Debugger` section, I'm kind of curious now  whether we should change this.

2018-12-19 10:37 UTC, fhemberger requested changes
@ZYSzys Please revert the changes, as it's indeed the legacy debugger.

I only noticed, that in the Korean version, links to the "Built-in Debugger" point to

- https://nodejs.org/docs/latest/api/debugger.html (comment)
- https://github.com/nodejs/node/blob/master/lib/_debugger.js

So these links should be replaced with `https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html`, as in the other languages.

If I'm not mistaken, this should be the only remaining change.

2018-12-19 10:53 UTC, ZYSzys commented
@fhemberger 👌Reverted and updated the link of "Built-in Debugger" in the Korean version.

2018-12-19 10:57 UTC, fhemberger approved these changes

2018-12-19 10:58 UTC, merged

2018-12-19 10:58 UTC, fhemberger commented
@ZYSzys Thanks! 👍