Add translation about/governance in Spanish
nodejs/nodejs.org pull request #1945
Opened 2018-12-18 00:24 UTC by Beor18

Hello community,

I bring you another contribution in the Spanish translation

Thank you very much and I hope for comments.

Best regards

2018-12-19 10:27 UTC, fhemberger commented
@Beor18 Hi, thanks for the update. Could you please rebase your changes from master and fix the merge conflicts?

/cc @nodejs/nodejs-es Please review.

2018-12-19 11:26 UTC, Beor18 commented
> @Beor18 Hi, thanks for the update. Could you please rebase your changes from master and fix the merge conflicts?
> 
> /cc @nodejs/nodejs-es Please review.

Hello @fhemberger, have now if it's okay.
Excuse me as I am new contributing by there I can make some mistake and it's good to let me know jajaja

Best regards!

2019-02-03 01:40 UTC, Maledong commented
@nodejs/nodejs-es：Sorry but it's been a long time, anyone free can have a review of that so as to merge it quickly :)

2019-02-03 09:01 UTC, academo commented on locale/es/about/governance.md
> +Las personas que hacen contribuciones importantes y valiosas se convierten en Colaboradores y se les otorga acceso comprometido al proyecto. Estas personas están identificadas por el TSC y su nominac
"access comprometido" no tiene sentido aqui, siendo un termino tan tecnico seria mejor usar "commit-access" (con comillas) aqui?

2019-02-03 14:09 UTC, Beor18 commented on locale/es/about/governance.md
> +Las personas que hacen contribuciones importantes y valiosas se convierten en Colaboradores y se les otorga acceso comprometido al proyecto. Estas personas están identificadas por el TSC y su nominac
entonces seria

_se le otorga un "commit-access" al proyecto._ ???

2019-02-05 17:17 UTC, edsadr requested changes

2019-02-05 17:17 UTC, edsadr commented on locale/es/about/governance.md
> +Las personas que hacen contribuciones importantes y valiosas se convierten en Colaboradores y se les otorga acceso comprometido al proyecto. Estas personas están identificadas por el TSC y su nominac
es mejor una traducción menos literal usar por ejemplo `permisos de escritura` estaría bien.

2019-02-06 23:04 UTC, Beor18 commented on locale/es/about/governance.md
> +Las personas que hacen contribuciones importantes y valiosas se convierten en Colaboradores y se les otorga acceso comprometido al proyecto. Estas personas están identificadas por el TSC y su nominac
perfecto!

2019-02-07 15:23 UTC, edsadr approved these changes

2019-02-10 07:47 UTC, Maledong commented
@Beor18：Would you mind get the latest version of these files and rebase, then make a force push? It seems there're are some difference between yours and the real nodejs's master (such as `f0c1874` and `
582a01f `), and then maybe your submission will be merged :)

2019-02-10 18:17 UTC, vrunoa approved these changes

2019-02-14 08:36 UTC, merged

2019-02-14 08:36 UTC, Maledong commented
@Beor18：Thank you!