translate security.md to pt-br
nodejs/nodejs.org pull request #1953
Opened 2018-12-20 23:43 UTC by cezaraugusto

cc @glaucia86 @Drieger for review (thanks for leading this work!)

**Core reviewers**: this is likely not your in language and there aren't active maintainers in https://github.com/nodejs/nodejs-pt. Per https://github.com/nodejs/nodejs-pt/issues/69#issue-392831345 (also in Portuguese) both @glaucia86 and @Drieger are willing to take ownership of the project and I'm (@cezaraugusto) also volunteering as well. Is it possible for us to be included in the org and have privileges in that repo so we could have it maintained?

2018-12-21 00:04 UTC, gustavohenke reviewed
Sorry for the long review 😅

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +Após a resposta inicial do seu reporte, a equipe de segurança irá se encarregar de manter você informado sobre o progresso que está sendo feito em relaçäo à resolução e ao anúncio completo, e pode so
```suggestion
Após a resposta inicial do seu reporte, a equipe de segurança irá se encarregar de manter você informado sobre o progresso que está sendo feito em relação à resolução e ao anúncio completo, e pode solicitar informações adicionais ou orientação sobre o problema reportado.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +Seu reporte terá tido conhecimento dentre 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
```suggestion
Seu reporte terá tido conhecimento em até 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +Estas atualizaçōes serāo enviadas pelo menos a cada cinco dias, mas na prática, isso é geralmente feito entre 24-48 horas.
```suggestion
Estas atualizaçōes serão enviadas pelo menos a cada cinco dias, mas na prática, isso é geralmente feito entre 24-48 horas.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +The program is managed through the HackerOne platform at [https://hackerone.com/nodejs](https://hackerone.com/nodejs) with further details.
Esta seção necessita tradução

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +Problemas de segurança em módulos terceiros (third-party) devem ser reportados aos
```suggestion
Problemas de segurança em módulos de terceiros (third-party) devem ser reportados aos
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +Aqui encontra-se a política de divulgação de segurança para o Node.js
```suggestion
Aqui encontra-se a política de divulgação de segurança para o Node.js:
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +O código é auditado para encontrar quaisquer problemas similares em potencial. Os consertos sao preparados para todos os releases os quais encontram-se sobre _maintance_. Estes consertos nao sao envi
```suggestion
O código é auditado para encontrar quaisquer problemas similares em potencial. Os consertos são preparados para todos os releases os quais encontram-se em manutenção. Estes consertos não são enviados para o repositório publico mas mantidos localmente aguardando lançamento.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +- Na data de embargo, é enviada uma cópia do anúncio para a lista de e-mails de segurança do Node.js. As alterações sao enviadas para o repositório público e é feito o deploy dos novos builds para o
```suggestion
- Na data de embargo, é enviada uma cópia do anúncio para a lista de e-mails de segurança do Node.js. As alterações são enviadas para o repositório público e é feito o deploy dos novos builds para o nodejs.org. Dentro de 6 horas da lista de segurança ser notificada, uma cópia do conselho será publicada no blog do Node.js.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +- Este processo pode levar algum tempo, especialmente quando é necessária uma coordenação com _maintainers_ de outros projetos. Todo esforço será feito para garantir que o bug seja consertado a tempo
```suggestion
- Este processo pode levar algum tempo, especialmente quando é necessária uma coordenação com _maintainers_ de outros projetos. Todo esforço será feito para garantir que o bug seja consertado a tempo, entretanto, é importante que siga-se o processo de release acima para garantir que o anúncio seja feito de forma consistente.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +ou email [security@nodejs.org](mailto:security@nodejs.org) para discussāo.
```suggestion
ou e-mail [security@nodejs.org](mailto:security@nodejs.org) para discussão.
```

2018-12-21 00:04 UTC, gustavohenke commented on locale/pt-br/security.md
> +Notificaçōes de segurança irão ser distribuídas através dos seguintes métodos.
```suggestion
Notificações de segurança serão distribuídas através dos seguintes métodos:
```

2018-12-21 01:16 UTC, JCMais commented on locale/pt-br/security.md
> +Após a resposta inicial do seu reporte, a equipe de segurança irá se encarregar de manter você informado sobre o progresso que está sendo feito em relaçäo à resolução e ao anúncio completo, e pode so
orientações soa melhor aqui.

2018-12-21 01:21 UTC, glaucia86 commented on locale/pt-br/security.md
> +Seu reporte terá tido conhecimento dentre 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
Todos os bugs de segurança no Node.js são tratados com seriedade e devem ser reportados através do e-mail [security@nodejs.org](mailto:security@nodejs.org). O e-mail será entregue para uma divisão do core team que cuida de problemas de segurança.

2018-12-21 01:41 UTC, glaucia86 commented on locale/pt-br/security.md
> +Todos os bugs de segurança no Node.js são tratados com seriedade e devem ser reportados através do e-mail [security@nodejs.org](mailto:security@nodejs.org). O e-mail irá ser entregue para uma divisão
Todos os bugs de segurança no Node.js são tratados com seriedade e devem ser reportados através do e-mail [security@nodejs.org](mailto:security@nodejs.org). O e-mail será entregue para uma divisão do core team que cuida de problemas de segurança.

2018-12-21 01:48 UTC, glaucia86 commented on locale/pt-br/security.md
> +Seu reporte terá tido conhecimento dentre 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
```sugestion
Seu reporte terá tido conhecimento dentre 24 horas, e você receberá uma resposta mais detalhada sobre assunto dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
```

2018-12-21 01:49 UTC, glaucia86 commented on locale/pt-br/security.md
> +Seu reporte terá tido conhecimento dentre 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
```sugestion
Seu reporte terá tido conhecimento dentre 24 horas, e você receberá uma resposta mais detalhada sobre assunto dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
```

2018-12-21 01:52 UTC, glaucia86 commented on locale/pt-br/security.md
> +Após a resposta inicial do seu reporte, a equipe de segurança irá se encarregar de manter você informado sobre o progresso que está sendo feito em relaçäo à resolução e ao anúncio completo, e pode so
```suggestion 
Após a resposta inicial do seu reporte, a equipe de segurança se encarregará de manter você informado sobre o progresso que está sendo feito em relação à resolução e ao anúncio completo, e pode solicitar informações adicionais ou orientação sobre o problema reportado.
```

2018-12-21 02:15 UTC, glaucia86 approved these changes

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +Após a resposta inicial do seu reporte, a equipe de segurança irá se encarregar de manter você informado sobre o progresso que está sendo feito em relaçäo à resolução e ao anúncio completo, e pode so
@JCMais no lugar de **informações** para **orientações** ?

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +Estas atualizaçōes serāo enviadas pelo menos a cada cinco dias, mas na prática, isso é geralmente feito entre 24-48 horas.
```suggestion
Estas atualizações serão enviadas pelo menos a cada cinco dias. Mas na prática, isso é geralmente feito entre 24h à 48 horas.
```

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +Obrigado por melhorar a segurança do Node.js. Seus esforços e a divulgação feita de forma responsável são muito bem-quistos e serão considerados.
```suggestion
Obrigado por melhorar a segurança do Node.js. Seus esforços e a divulgação feita de forma responsável são muito benquistos e serão considerados.
```

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +- O reporte de segurança é recebido e designado para um cuidador primário. Esta pessoa irá coordenar o conserto e o processo de release. O problema é confirmado e uma lista de todas as versões afetad
```suggestion
O reporte de segurança é recebido e designado para um cuidador primário. Esta pessoa coordenará o conserto e o processo de release. O problema é confirmado e uma lista de todas as versões afetadas é determinada.
```

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +O código é auditado para encontrar quaisquer problemas similares em potencial. Os consertos sao preparados para todos os releases os quais encontram-se sobre _maintance_. Estes consertos nao sao envi
```suggestion
O código é auditado para encontrar quaisquer problemas similares em potencial. Os consertos são preparados para todos os releases os quais encontram-se em manutenção. Estes consertos não são enviados para o repositório público, mas mantidos localmente aguardando lançamento.
```

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +- Tipicamente a data de embargo irá ser definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação do co
```suggestion
Geralmente a data de embargo será definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação do conserto (fix).
```

2018-12-21 02:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +- Este processo pode levar algum tempo, especialmente quando é necessária uma coordenação com _maintainers_ de outros projetos. Todo esforço será feito para garantir que o bug seja consertado a tempo
```suggestion
Este processo pode levar algum tempo, especialmente quando é necessária uma coordenação com _maintainers_ de outros projetos. Todo esforço será feito para garantir que o bug seja consertado a tempo. Entretanto, é importante que acompanhe o processo de release acima para garantir que o anúncio seja feito de forma consistente.
```

2018-12-21 02:16 UTC, glaucia86 requested changes
@cezaraugusto dê uma olhada nas partes onde o @gustavohenke e eu sinalizamos. Procurei ver no dicionário sinônimos de algumas palavras para soar melhor alguns contextos de frases!
E parabéns também pela iniciativa! :)

2018-12-21 12:52 UTC, Drieger requested changes
Fiz alguma sugestões de modificação. Olhando a versão que está no master da versão em inglês https://github.com/nodejs/nodejs.org/blob/master/locale/en/security.md também acho que tinham algumas modificações.

De qualquer forma, vlw @cezaraugusto pela iniciativa. :smile:  :+1:

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +Todos os bugs de segurança no Node.js são tratados com seriedade e devem ser reportados através do e-mail [security@nodejs.org](mailto:security@nodejs.org). O e-mail irá ser entregue para uma divisão
Tenho a impressão que faltou a parte do "HackerOne" nesse parágrafo. Olhando o arquivo na versão em inglês: https://github.com/nodejs/nodejs.org/blob/master/locale/en/security.md

```suggestion
Todos os bugs de segurança no Node.js são tratados com seriedade e devem ser reportados através do sistema [HackerOne](https://hackerone.com/nodejs) ou do e-mail [security@nodejs.org](mailto:security@nodejs.org). O problema reportado será entregue a uma subdivisão do time de principal, responsável por gerênciar as questões de segurança.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +Seu reporte terá tido conhecimento dentre 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
Talvez ao invés de utilizar `reporte`, talvez fique mais claro trocar por `relatório`. Também acho a construção `terá tido conhecimento` estranha, poderiamos trocar por  `será confirmado`

```suggestion
Seu relatório será confirmado em até 24 horas, e você receberá, dentro de 48h, uma resposta mais detalhada sobre o assunto, indicando os próximos passos a serem tomados.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +seus respectivos _maintainers_ e podem também serem coordenados através do [Node Ecosystem Security Team](https://hackerone.com/nodejs-ecosystem) ou via e-mail para [security-ecosystem@nodejs.org](ma
```suggestion
seus respectivos _maintainers_ e também coordenados através do [Node Ecosystem Security Team](https://hackerone.com/nodejs-ecosystem) ou via e-mail para [security-ecosystem@nodejs.org](mailto:security-ecosystem@nodejs.org).
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +Obrigado por melhorar a segurança do Node.js. Seus esforços e a divulgação feita de forma responsável são muito bem-quistos e serão considerados.
```suggestion
 Obrigado por melhorar a segurança do Node.js e seu ecossistema. Seus esforços e a divulgação feita de forma responsável são muito estimados e serão reconhecidos.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +- O reporte de segurança é recebido e designado para um cuidador primário. Esta pessoa irá coordenar o conserto e o processo de release. O problema é confirmado e uma lista de todas as versões afetad
Acho que precisa manter o `-` no ínicio pra ele ficar com um item na versão renderizada do `.md`

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +- O reporte de segurança é recebido e designado para um cuidador primário. Esta pessoa irá coordenar o conserto e o processo de release. O problema é confirmado e uma lista de todas as versões afetad
```suggestion
- O relatório de segurança é recebido e designado a um primeiro responsável. Esta pessoa irá coordenar os processos de correção e atualização. O problema é confirmado e uma lista de todas as versões afetadas é determinada.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +O código é auditado para encontrar quaisquer problemas similares em potencial. Os consertos sao preparados para todos os releases os quais encontram-se sobre _maintance_. Estes consertos nao sao envi
```suggestion
O código é auditado para encontrar possíveis problemas similares. As correções são preparadas para todas as versões que ainda estão sob manutenção. Estas correções não são enviadas ao repositório público mas mantidos localmente aguardando a divulgação.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +- Na data de embargo, é enviada uma cópia do anúncio para a lista de e-mails de segurança do Node.js. As alterações sao enviadas para o repositório público e é feito o deploy dos novos builds para o
```suggestion
- Na data de embargo, é enviada uma cópia do anúncio para a lista de e-mails de segurança do Node.js. As alterações são enviadas para o repositório público e é feito o deploy dos novos builds para o nodejs.org. Dentro de 6 horas da notificação na lista de segurança, uma cópia do anúncio será publicada no blog do Node.js.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +- Tipicamente a data de embargo irá ser definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação do co
Acho que `correção` no lugar de `conserto` fica mais claro.

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +- Este processo pode levar algum tempo, especialmente quando é necessária uma coordenação com _maintainers_ de outros projetos. Todo esforço será feito para garantir que o bug seja consertado a tempo
```suggestion
- Este processo pode levar algum tempo, especialmente quando é necessária uma coordenação com _maintainers_ de outros projetos. Todo esforço será feito para garantir que o bug seja corrigido a tempo. Entretanto, é importante que sigamos o processo de _release_ acima para garantir que a divulgação seja feita de forma consistente.
```

2018-12-21 12:52 UTC, Drieger commented on locale/pt-br/security.md
> +ou email [security@nodejs.org](mailto:security@nodejs.org) para discussāo.
Acho que isso foi alterado, olhando https://github.com/nodejs/nodejs.org/blob/master/locale/en/security.md

```suggestion
ou [crie uma _issue_](https://github.com/nodejs/security-wg/issues/new) para discussão.
```

2018-12-21 13:54 UTC, glaucia86 commented on locale/pt-br/security.md
> +Seu reporte terá tido conhecimento dentre 24 horas, e você irá receber uma resposta mais detalhada sobre ele dentro de 48 horas indicando as próximas etapas para resolver seu reporte.
@Drieger fiquei com essa mesma impressão também. Gostei do contexto **relatório**

2018-12-23 09:11 UTC, fhemberger commented
/cc @bnb @Trott @MylesBorins: Could you please add @glaucia86, @Drieger and @cezaraugusto to @nodejs/nodejs-pt (which seems to be inactive). Thanks!

2018-12-23 14:02 UTC, glaucia86 commented
> /cc @bnb @Trott @MylesBorins: Could you please add @glaucia86, @Drieger and @cezaraugusto to @nodejs/nodejs-pt (which seems to be inactive). Thanks!

Thanks @fhemberger

2018-12-23 17:18 UTC, Trott commented
> /cc @bnb @Trott @MylesBorins: Could you please add @glaucia86, @Drieger and @cezaraugusto to @nodejs/nodejs-pt (which seems to be inactive). Thanks!

I normally have the necessary privileges due to TSC membership, but I'm not on the TSC at the current time. I stepped down last month and plan to ask to rejoin next month.

@bnb has elevated privileges due to Moderation Team membership but this is not a moderation action.  Previously, @bnb had the elevated privileges also due to being CommComm chair. If Myles is unable to get to this in a reasonably timely fashion, let's ping the current CommComm chair (`@amiller-gh`) and/or `@nodejs/tsc`.

2018-12-26 02:20 UTC, MylesBorins commented
members added 😄 

Happy holidays

2018-12-26 02:23 UTC, glaucia86 commented
> members added 😄
> 
> Happy holidays

Thank you so much @MylesBorins.

2018-12-26 06:22 UTC, cezaraugusto commented
What a great review! thanks for taking time on this one. cc @gustavohenke, @glaucia86, @JCMais Ready for re-review. 

@fhemberger, @Trott, @MylesBorins thanks for taking a look 👍

2018-12-26 11:28 UTC, Drieger requested changes
LGTM after addressing this last comment @cezaraugusto

2018-12-26 11:28 UTC, Drieger commented on locale/pt-br/security.md
> +- Geralmente a data de embargo será ser definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação da co
```suggestion
- Geralmente a data de embargo será definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação da correção (fix).
```

2018-12-26 13:15 UTC, glaucia86 commented on locale/pt-br/security.md
> +- Geralmente a data de embargo será ser definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação da co
> Suggested change Beta 
> [Give us feedback](https://www.research.net/r/SuggestedChanges)
> - Geralmente a data de embargo será ser definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação da correção (fix).
> - Geralmente a data de embargo será definida 72 horas após o horário que o CVE é criado. Entretanto, a data pode variar dependendo do grau de severidade do bug ou a dificuldade na aplicação da correção (fix).

@Drieger excelente! Darei continuidade tbm em outras traduções. Vamos que vamos! :)

2018-12-29 00:49 UTC, glaucia86 approved these changes
Aprovado!
👍

2018-12-31 09:45 UTC, gustavohenke approved these changes

2018-12-31 09:45 UTC, gustavohenke commented on locale/pt-br/security.md
> +Estas atualizações serāo enviadas pelo menos a cada cinco dias. Mas na prática, isso é geralmente feito entre 24h à 48 horas.
```suggestion
Estas atualizações serāo enviadas pelo menos a cada cinco dias. Mas na prática, isso é geralmente feito entre 24 à 48 horas.
```

2018-12-31 09:45 UTC, gustavohenke commented on locale/pt-br/security.md
> +- - O relatório de segurança é recebido e designado a um primeiro responsável. Esta pessoa coordenará os processos de atualização e revisão. O problema é confirmado e uma lista de todas as versões af
duplo `- ` aqui

```suggestion
- O relatório de segurança é recebido e designado a um primeiro responsável. Esta pessoa coordenará os processos de atualização e revisão. O problema é confirmado e uma lista de todas as versões afetadas é determinada.
```

2018-12-31 20:31 UTC, cezaraugusto commented
@JCMais, @Drieger could you please check again? all feedback should be addressed. I guess we need consensus before core reviewers can merge this

2019-01-02 04:14 UTC, JCMais approved these changes
great job

2019-01-02 10:05 UTC, Drieger approved these changes
LGTM

2019-01-02 10:40 UTC, merged