translate knowledge/repl to pt-br
nodejs/nodejs.org pull request #1954
Opened 2018-12-20 23:46 UTC by cezaraugusto

includes:
* how-to-create-a-custom-repl.md
* how-to-use-nodejs-repl.md

cc @glaucia86 @Drieger for review

**core reviewers** please see https://github.com/nodejs/nodejs.org/pull/1953#issue-240333731 if you have a chance and let me know the steps needed to make it, if any.

2018-12-21 02:22 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +`prompt` é uma string que é usada para o prompt do seu REPL e tem por padrão o "> ". `stream` é um stream que o repl escuta e tem por padrão o `processo.stdin`. Quando você roda `node` pelo prompt de
```suggestion
`prompt` é uma string que é usada para o prompt do seu REPL e tem por padrão o "> ". `stream` é um stream que o repl escuta e tem por padrão o `processo.stdin`. Quando você executa o comando `node` pelo prompt de comando, o que ele faz nos bastidores é executar `repl.start()` para fornecer o REPL padrão.
```

2018-12-21 02:23 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Entretanto, o repl é bem flexível. Aqui um exemplo que demonstra isso:
```suggestion
Entretanto, o repl é bem flexível. Abaixo segue um exemplo que demonstra isso:
```

2018-12-21 02:24 UTC, glaucia86 requested changes

2018-12-21 02:24 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +    //Um repl remoto que você pode fazer uma conexão telnet!
```suggestion
// Aqui um exemplo de um repl remoto que você pode fazer uma conexão telnet!
```

2018-12-21 02:25 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +      remote.context.mood = mood;
```suggestion
// Adicionando "mood" e "bonus" para o contexto remoto do REPL.
```

2018-12-21 02:26 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +    //Um nó do repl "local" com um prompt customizado
```suggestion
// Aqui temos um nó do repl "local" com um prompt customizado
```

2018-12-21 02:28 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Este script cria *dois* REPLs: Um é normal exceto pelo prompt customizado, mas o  *outro* é exposto através do modulo net de forma que eu possa fazer a conexão telnet para ele! Além disso, ele usa a
```suggestion
Este script cria *dois* REPLs: Um é normal, exceto pelo prompt customizado. Porém. o  *outro* é exposto através do módulo net de forma que se possa fazer a conexão telnet para ele! Além disso, ele usa a propriedade `context` para expor a função "mood" para os dois REPLs e a string "bonus" apenas o REPL remoto. Como pode ver, essa forma de tentar expor objetos de um REPL e não o outro *nao funciona realmente*.
```

2018-12-21 02:28 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Aqui o que acontece quando eu rodo o script:
```suggestion
Observe o que acontece quando eu executo o script:
```

2018-12-21 02:30 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Como se pode ver, a função `mood` é usada junto do REPL local, mas a string `bonus` nao. Isso é esperado.
```suggestion
Como podem notar, a função `mood` é usada junto do REPL local. Mas a string `bonus` não. Isso é esperado.
```

2018-12-21 02:31 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Agora, aqui o que acontece quando eu tento fazer uma telnet para a porta 5001:
```suggestion
Observem agora o que acontece quando fazemos um telnet para a porta 5001:
```

2018-12-21 02:32 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Como você pode ver, a funcao `mood` é *também* é disponibilizada através da telnet! Alem tambem de "bonus".
```suggestion
Como podem notar, a função `mood` é *também* disponibilizada através da telnet! Incluso também de "bonus".
```

2018-12-21 02:33 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Uma consequência interessante das minhas ações, bonus agora também é definida no REPL local:
```suggestion
Outro ponto interessante das minhas ações é que bonus agora também é definida no REPL local:
```

2018-12-21 02:34 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +O Node.js vem com seu próprio REPL, que é uma abreviação para 'Read-Eval-Print Loop'. É o shell do Node.js; qualquer JavaScript válido que pode ser escrito em um script pode ser passado para o REPL.
```suggestion
O Node.js vem com seu próprio REPL, que é uma abreviação para 'Read-Eval-Print Loop'. É o shell do Node.js. Qualquer JavaScript válido que pode ser escrito em um script, pode ser passado para o REPL. Pode ser extremamente útil para experimentos com o node.js, depurar código e entender alguns comportamentos excêntricos do JavaScript.
```

2018-12-21 02:35 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Roda-lo é simples - basta rodar o node sem um nome de arquivo.
```suggestion
Para executar é simples - execute o node sem um nome de arquivo.
```

2018-12-21 02:36 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Ele então te deixa em um prompt simples ('>') onde você pode escrever qualquer comando JavaScript que desejar. Assim como na maioria dos shells, você pode apertar as setas para cima e para baixo para
```suggestion
Ele então te deixa em um prompt simples ('>') onde você pode escrever qualquer comando JavaScript que desejar. Assim como na maioria dos shells, você pode apertar as setas para cima e para baixo para fazer um scroll através do histórico de comandos e modificar comandos anteriores. O REPL também utiliza o `Tab` para realizar o autocomplete do comando.
```

2018-12-21 02:37 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Qualquer que seja o comando, ele irá fazer print do valor de retorno deste comando. Se você quer reutilizar um valor de retorno anterior, você pode usar a variavel especial `_`.
```suggestion
Qualquer que seja o comando, ele fará o print do valor de retorno deste comando. Se você quiser reutilizar um valor de retorno anterior, você pode usar a variável especial:  `_`.
```

2018-12-21 02:38 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Quando a palavra-chave `var` é utilizada, o valor da expressão é armazenado, mas *NÃO* retornado. Quando um simples identificador é utilizado, o valor é retornado também, assim como armazenado.
```suggestion
Quando a palavra-chave `var` é utilizada, o valor da expressão é armazenado. Porém, *NÃO* retornado. Quando um simples identificador é utilizado, o valor é retornado também, assim como armazenado.
```

2018-12-21 02:38 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Se você precisar acessar quaisquer módulos nativos, ou modulos terceiros, eles podem ser acessados através do `require`, assim como em qualquer parte do Node.
```suggestion
Se você precisar acessar quaisquer módulos nativos, ou módulos terceiros, eles podem ser acessados através do `require`, assim como em qualquer parte do Node.
```

2018-12-21 02:39 UTC, glaucia86 requested changes
@cezaraugusto novamente, dê uma olhada nos pontos onde eu sinalizei.
Parabéns pela iniciativa :)

2018-12-21 13:27 UTC, Drieger requested changes
Reviewed the first file only for now. Thanks @cezaraugusto for the great job :smile: and @glaucia86 for the reviews.

2018-12-21 13:27 UTC, Drieger commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +O Node permite aos usuários criarem seus próprios REPLS com o [modulo repl](http://nodejs.org/docs/v0.4.10/api/repl.html). A forma de uso mais básica se parece com isso:
```suggestion
O Node permite aos usuários criarem seus próprios REPLS com o [módulo repl](http://nodejs.org/docs/v0.4.10/api/repl.html). A forma de uso mais básica se parece com isso:
```

2018-12-21 13:27 UTC, Drieger commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +      remote.context.mood = mood;
@glaucia86 acho que a linha da sugestão deveria ser a 32 e não a 33, pra não remover a atribuição do exemplo

2018-12-21 13:27 UTC, Drieger commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +      //Adicionando "mood" e "bonus" para o contexto remoto do REPL.
```suggestion
      //Adicionando "mood" e "bonus" no contexto do REPL remoto.
```

2018-12-21 13:27 UTC, Drieger commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Este script cria *dois* REPLs: Um é normal exceto pelo prompt customizado, mas o  *outro* é exposto através do modulo net de forma que eu possa fazer a conexão telnet para ele! Além disso, ele usa a
```suggestion
Este script cria *dois* REPLs: Um é normal, exceto pelo prompt customizado. Porém o  *outro* é exposto através do módulo net de forma que se possa fazer a conexão telnet para ele! Além disso, ele usa a propriedade `context` para expor a função "mood" para os dois REPLs e a string "bonus" apenas para o REPL remoto. Como pode ver, essa forma de tentar expor objetos em um REPL e não no outro *não funciona*.
```

2018-12-21 13:27 UTC, Drieger commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Como você pode ver, a funcao `mood` é *também* é disponibilizada através da telnet! Alem tambem de "bonus".
```suggestion
Como podem notar, a função `mood` é *também* disponibilizada através da telnet! Além disso "bonus" também é.
```

2018-12-21 13:47 UTC, glaucia86 commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +O Node permite aos usuários criarem seus próprios REPLS com o [modulo repl](http://nodejs.org/docs/v0.4.10/api/repl.html). A forma de uso mais básica se parece com isso:
Perdão. Já era quase 2h da manhã e tava programando. Vou desconsiderar aqui.

2018-12-21 13:54 UTC, Drieger commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +O Node permite aos usuários criarem seus próprios REPLS com o [modulo repl](http://nodejs.org/docs/v0.4.10/api/repl.html). A forma de uso mais básica se parece com isso:
Nem esquenta, o processo de revisão é pra isso :smile:

2018-12-26 06:40 UTC, cezaraugusto commented
@glaucia86, @Drieger thanks for reviewing, feedback addressed

2018-12-27 23:17 UTC, gustavohenke requested changes

2018-12-27 23:17 UTC, gustavohenke commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +O Node permite aos usuários criarem seus próprios REPLS com o [módulo repl](http://nodejs.org/docs/v0.4.10/api/repl.html). A forma de uso mais básica se parece com isso:
`v0.4.10` 👴 👵 

Use o link pra uma documentação mais atual:
```suggestion
O Node permite aos usuários criarem seus próprios REPLs com o [módulo `repl`](https://nodejs.org/dist/latest/docs/api/repl.html). A forma de uso mais básica se parece com isso:
```

2018-12-27 23:17 UTC, gustavohenke commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +    repl.start(prompt, stream);
Que tal usar

```
```js
```

pra deixar o syntax highlighting configurado pra JS?

2018-12-27 23:17 UTC, gustavohenke commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Ele então te deixa em um prompt simples ('>') onde você pode escrever qualquer comando JavaScript que desejar. Assim como na maioria dos shells, você pode apertar as setas para cima e para baixo para
```suggestion
Ele então te deixa em um prompt simples ('>') onde você pode escrever qualquer comando JavaScript que desejar. Assim como na maioria dos shells, você pode apertar as setas para cima e para baixo para navegar através do histórico de comandos e modificar comandos anteriores. O REPL também utiliza a tecla <kbd>Tab</kbd> para completar o comando.
```

2018-12-27 23:17 UTC, gustavohenke commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Qualquer que seja o comando, ele fará o print do valor de retorno deste comando. Se você quiser reutilizar um valor de retorno anterior, você pode usar a variável especial:  `_`.
```suggestion
Qualquer que seja o comando, ele imprimirá o valor de retorno deste comando. Se você quiser reutilizar um valor de retorno anterior, você pode usar a variável especial `_`.
```

2018-12-27 23:17 UTC, gustavohenke commented on locale/pt-br/knowledge/REPL/how-to-use-nodejs-repl.md
> +Algo importante de notar é onde os valores de retorno do REPL sao aplicados:
```suggestion
Algo importante de notar é onde os valores de retorno do REPL são aplicados:
```

2018-12-27 23:17 UTC, gustavohenke commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +Como podem notar, a função `mood` é *também* disponibilizada através da telnet! Além disso "bonus" também é.
```suggestion
Como podem notar, a função `mood` *também* é disponibilizada através da telnet! Além disso `bonus` também é.
```

2018-12-31 20:23 UTC, cezaraugusto commented on locale/pt-br/knowledge/REPL/how-to-create-a-custom-repl.md
> +    repl.start(prompt, stream);
boa ideia, coloquei no trecho de código abaixo desse também

2018-12-31 20:32 UTC, cezaraugusto commented
@glaucia86, @Drieger, @gustavohenke could you please check again? all feedback should be addressed. I guess we need consensus before core reviewers can merge this

2019-01-01 22:41 UTC, gustavohenke approved these changes

2019-01-02 00:41 UTC, glaucia86 commented
Thanks all!

2019-01-02 00:43 UTC, glaucia86 approved these changes

2019-01-02 04:13 UTC, JCMais approved these changes
everything looks great, thanks

2019-01-02 10:29 UTC, Drieger approved these changes
LGTM :+1: 
Great work!

2019-01-02 10:40 UTC, merged

2019-01-03 21:40 UTC, glaucia86 commented
LGTM 👍
Nice!