Translate get involved to pt-br
nodejs/nodejs.org pull request #1955
Opened 2018-12-21 19:10 UTC by Drieger

Translated `get-involved`

ping @nodejs/nodejs-pt @glaucia86 @cezaraugusto

2018-12-21 19:14 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +Eventos Programe & Aprenda permitem que você comece a contribuir (ou de um passo adiante) com a principais funcionalidades do Node.js. Contribuidores experientes irão auxiliá-lo em seu primeiro (ou s
```suggestion
Eventos Programe & Aprenda permitem que você comece a contribuir (ou de um passo adiante) com as principais funcionalidades do Node.js. Contribuidores experientes irão auxiliá-lo em seu primeiro (ou segundo ou terceiro ou quarto) _commit_ ao Node.js. Eles também estarão disponíveis para guiá-los através de áreas específicas do código fonte do Node.js.
```

2018-12-21 19:16 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +- Kilkenny, Ireland na [NodeConfEU](https://www.nodeconf.eu/): 4 de Novembro de 2018
Kilkenny, Irlanda no [NodeConfEU](https://www.nodeconf.eu/): 4 de Novembro de 2018

2018-12-21 19:17 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +- Vancouver, BC na [Node Interactive](https://events.linuxfoundation.org/events/node-js-interactive-2018/): 12 de Outubro de 2018
```suggestion
- Vancouver, BC no [Node Interactive](https://events.linuxfoundation.org/events/node-js-interactive-2018/): 12 de Outubro de 2018
```

2018-12-21 19:17 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +- Vancouver, BC na [Node Interactive](http://events.linuxfoundation.org/events/node-interactive): 6 de October de 2017
```suggestion
- Vancouver, BC no [Node Interactive](http://events.linuxfoundation.org/events/node-interactive): 6 de Outubro de 2017
```

2018-12-21 19:18 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +- Kilkenny, Ireland na [NodeConfEU](http://www.nodeconf.eu/): 5 de Novembro de 2017
```suggestion
- Kilkenny, Irlanda na [NodeConfEU](http://www.nodeconf.eu/): 5 de Novembro de 2017
```

2018-12-21 19:18 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +- Tokyo em Novembro de 2016
```suggestion
- Tóquio em Novembro de 2016
```

2018-12-21 19:19 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +- Dublin e London em Setembro de 2015
```suggestion
Dublin e Londres em Setembro de 2015
```

2018-12-21 19:19 UTC, glaucia86 commented on locale/pt-br/get-involved/collab-summit.md
> +O _Collaboration Summit_ é uma desconferência organizada para juntar contribuidores e
**desconferência**? @Drieger ?

2018-12-21 19:21 UTC, glaucia86 commented on locale/pt-br/get-involved/collab-summit.md
> +Essa é uma oportuidade para você ficar a par do que está acontecendo na comunidade,
```suggestion
Essa é uma oportunidade para você ficar a par do que está acontecendo na comunidade,
```

2018-12-21 19:21 UTC, glaucia86 commented on locale/pt-br/get-involved/collab-summit.md
> +embarcar e contribuir com as habilidade que possui e gostaria de aprimorar.
```suggestion
embarcar e contribuir com as habilidades que possui e gostaria de aprimorar.
```

2018-12-21 19:22 UTC, glaucia86 commented on locale/pt-br/get-involved/collab-summit.md
> +para verificar eventos futuros e passados. Também de uma olhada nos [tópicos reportados](https://github.com/nodejs/summit/issues)
```suggestion
para verificar eventos futuros e passados. Também dê uma olhada nos [tópicos reportados](https://github.com/nodejs/summit/issue
```

2018-12-21 19:23 UTC, Drieger commented on locale/pt-br/get-involved/collab-summit.md
> +O _Collaboration Summit_ é uma desconferência organizada para juntar contribuidores e
No inglês ta `un-conference` pesquisando na internet a página em portguês desse termo utiliza desconferência (https://pt.wikipedia.org/wiki/Desconfer%C3%AAncia)

2018-12-21 19:23 UTC, glaucia86 commented on locale/pt-br/get-involved/contribute.md
> +O projeto Node.js é atualmente gerênciando através de diversos repositórios separados no GitHub, cada
```suggestion
O projeto Node.js é atualmente gerenciando através de diversos repositórios separados no GitHub, cada
```

2018-12-21 19:28 UTC, glaucia86 commented on locale/pt-br/get-involved/contribute.md
> +Se você gostaria de corrigir _bugs_ ou adicionar novas funcionalidades ao node.j, por favor consulte
```suggestion
Se você gostaria de corrigir _bugs_ ou adicionar novas funcionalidades ao Node.js, por favor consulte
```

2018-12-21 19:29 UTC, glaucia86 commented on locale/pt-br/get-involved/contribute.md
> +O processo de revisão realizado pelo colaboradores para todas as contribuições ao projeto é explicado
```suggestion
O processo de revisão realizado pelos colaboradores para todas as contribuições ao projeto são explicados
```

2018-12-21 19:30 UTC, glaucia86 commented on locale/pt-br/get-involved/contribute.md
> +Ao tornar-se um Colaborator, contribudores poderão impactar ainda mais o projeto. Colaboradores podem auxiliar outros contribuidores revisando suas contribuições, filtrando problemas e assumem um pap
```suggestion
Tornando-se um Colaborador, contribuidores poderão impactar ainda mais o projeto. Colaboradores podem auxiliar outros contribuidores revisando suas contribuições, filtrando problemas e assumindo um papel importante moldando o futuro do projeto. Indivíduos reconhecidos pelo TSC, por terem realizado contribuições significantes e valiosas em algum dos repositórios do Node.js podem tornar-se Colaboradores e a estes são concedidos permissões de _commit_ ao projeto
```

2018-12-21 19:31 UTC, glaucia86 commented on locale/pt-br/get-involved/contribute.md
> +Se alguém, realizando contribuições, valiosas acredita que não foi considerado para receber esse título, poderá [abrir um pedido](https://github.com/nodejs/TSC/issues) ou [contatar um membro do TSC](
```suggestion
Se alguém, realizando contribuições valiosas acredita que não foi considerado para receber esse título, poderá [abrir um pedido](https://github.com/nodejs/TSC/issues) ou [contatar um membro do TSC](https://github.com/nodejs/TSC#current-members) diretamente.
```

2018-12-21 19:34 UTC, glaucia86 requested changes
@Drieger fiz a revisão e tem poucos erros! Parabéns mais uma vez pela iniciativa. E vamos que vamos! :)

2018-12-21 19:34 UTC, glaucia86 commented on locale/pt-br/get-involved/code-and-learn.md
> +Eventos Programe & Aprenda permitem que você comece a contribuir (ou de um passo adiante) com a principais funcionalidades do Node.js. Contribuidores experientes irão auxiliá-lo em seu primeiro (ou s
@Drieger fiz a revisão e tem poucos erros! Parabéns mais uma vez pela iniciativa e vamos juntos! :)

2018-12-22 14:34 UTC, glaucia86 approved these changes

2018-12-22 14:34 UTC, glaucia86 approved these changes

2018-12-22 14:35 UTC, glaucia86 approved these changes

2018-12-22 14:35 UTC, glaucia86 approved these changes

2018-12-22 14:36 UTC, glaucia86 approved these changes

2018-12-22 14:36 UTC, glaucia86 approved these changes

2018-12-22 14:37 UTC, glaucia86 approved these changes

2018-12-22 14:37 UTC, glaucia86 approved these changes

2018-12-22 15:42 UTC, fhemberger commented
Is everything reviewed? Can this be merged?

2018-12-22 15:49 UTC, glaucia86 commented
> Is everything reviewed? Can this be merged?

Yes. It's pretty correctly the translation. @fhemberger

2018-12-22 15:51 UTC, merged

2018-12-22 15:51 UTC, fhemberger commented
Thank you!