revise Debugging Getting Started doc
nodejs/nodejs.org pull request #1969
Opened 2018-12-30 17:25 UTC by Trott

Refs: https://github.com/nodejs/nodejs.org/issues/1968

/cc @Floriferous

2018-12-31 20:41 UTC, lpinca approved these changes

2019-01-01 06:08 UTC, fhemberger commented
Also appears in

```
fa/docs/guides/getting-started-guide.md
ja/docs/guides/getting-started-guide.md
ko/docs/guides/getting-started-guide.md
zh-cn/docs/guides/getting-started-guide.md
```

2019-01-01 06:27 UTC, ghost commented
@nodejs/localization：Plz check your own localizations and do translations at **[Trott:debugging-start](https://github.com/Trott/new.nodejs.org/tree/debugging-start/locale)**

2019-01-01 10:25 UTC, ZYSzys approved these changes
LGTM with some nits.

2019-01-01 10:25 UTC, ZYSzys commented on locale/zh-cn/docs/guides/debugging-getting-started.md
> +检查器的客户端必须知晓并制定连接的域名地址、端口号以及 UUID。一个典型的 URL 看上去如：`ws://127.0.0.1:9229/0f2c936f-b1cd-4ac9-aab3-f63b0f33d55e`。
Nit:
```suggestion
检查器的客户端必须知晓并指定连接的域名地址、端口号以及 UUID。一个完整的 URL 看上去如：`ws://127.0.0.1:9229/0f2c936f-b1cd-4ac9-aab3-f63b0f33d55e`。
```

2019-01-01 10:25 UTC, ZYSzys commented on locale/zh-cn/docs/guides/debugging-getting-started.md
> +如果收到了 `SIGUSR1` 信号 (`SIGUSR1` 在 Windows 下不可用)，Node.js 同样会开始侦听调试信息；在 Node.js 7 以及先前的版本中，这将激活遗留版本的调试 API（legacy Debugger API）；在 Nodejs 8 和后续版本中，将激活检查器 API（Inspector API）。
Nit:
```suggestion
如果收到了 `SIGUSR1` 信号 (`SIGUSR1` 在 Windows 下不可用)，Node.js 同样会开始侦听调试信息；在 Node.js 7 以及先前的版本中，这将激活遗留版本的调试 API（legacy Debugger API）；在 Node.js 8 和后续版本中，将激活检查器 API（Inspector API）。
```

2019-01-01 10:40 UTC, vsemozhetbyt approved these changes

2019-01-01 12:55 UTC, willin approved these changes

2019-01-02 10:52 UTC, fhemberger commented
@nodejs/nodejs-ko Could you please update the Korean translation?

2019-01-02 10:54 UTC, yous commented
@outsideris @taggon Please take a look.

2019-01-02 14:14 UTC, taggon commented
@nodejs/nodejs-ko I will take a look at this tomorrow.

2019-01-04 03:19 UTC, outsideris requested changes
Please check this @nodejs/nodejs-ko

2019-01-04 03:19 UTC, outsideris commented on locale/ko/docs/guides/debugging-getting-started.md
```suggestion
`--inspect` 스위치로 시작하면 Node.js 프로세스가 디버깅 클라이언트에서 수신을 시작하고 
기본 호스트와 포트로 `127.0.0.1:9229`를 사용합니다. 각 프로세스는 고유한 [UUID][]도 할당받습니다.

인스펙터 클라이언트는 호스트 주소, 포트, UUID를 알아야 접속할 수 있습니다. 전체 URL은 
`ws://127.0.0.1:9229/0f2c936f-b1cd-4ac9-aab3-f63b0f33d55e` 같은 형태가 됩니다.

Node.js가 `SIGUSR1` 신호를 받으면 디버깅 메시지도 수신하기 시작합니다.(`SIGUSR1`는 
Windows에서는 사용할 수 없습니다.) Node.js 7 이하 버전에서는 레거시 Debugger API가 활성화되고 
Node.js 8 이상에서는 Inspector API를 활성화합니다. 
```

2019-01-04 03:19 UTC, outsideris commented on locale/ko/docs/guides/debugging-getting-started.md
And L35 - L47 should be removed.

2019-01-04 03:26 UTC, yous commented on locale/ko/docs/guides/debugging-getting-started.md
Gitpod should be addded below "chrome-remote-interface" at the line 198.

2019-01-04 07:01 UTC, yous commented on locale/ko/docs/guides/debugging-getting-started.md
``` markdown
#### [Gitpod](https://www.gitpod.io)

* `Debug` 뷰에서 Node.js 디버그 설정을 실행하거나 `F5` 키를 누르세요.
  [자세한 방법은 여기를 참고하세요.](https://medium.com/gitpod/debugging-node-js-applications-in-theia-76c94c76f0a1)
```

2019-01-10 03:21 UTC, Trott commented
@outsideris @yous You should be able to push commits directly to my branch if you wish. Feel free to do so if you feel confident about the changes. I'd very much like to get this landed.

2019-01-14 07:00 UTC, yous commented
Just pushed updates for Korean that applies reviews.

2019-01-15 11:45 UTC, yous commented
@nodejs/nodejs-ko Please check this.

2019-01-29 19:40 UTC, Trott commented
Seems like all requests for changes have been addressed? @outsideris

2019-01-30 08:43 UTC, outsideris approved these changes
LGTM

2019-01-30 09:04 UTC, merged

2019-01-30 09:04 UTC, fhemberger commented
Thanks everybody!