[pt-BR] Translate about/index.md to pt-br
nodejs/nodejs.org pull request #1974
Opened 2019-01-02 19:42 UTC by Drieger

Translated about/index.md to pt-br.

/cc @nodejs/nodejs-pt

2019-01-02 20:22 UTC, glaucia86 commented on locale/pt-br/about/index.md
> +é projetado para a construção de aplicações escaláveis de rede. No exemplo a
```suggestion
é projetado para desenvolvimento de aplicações escaláveis de rede. No exemplo a
```

2019-01-02 20:22 UTC, glaucia86 commented on locale/pt-br/about/index.md
> +a função de _callback_ é chamada, mas se não houver trabalho a ser realizado,
```suggestion
a função de _callback_ é chamada. Mas, se não houver trabalho a ser realizado,
```

2019-01-02 20:23 UTC, glaucia86 commented on locale/pt-br/about/index.md
> +Essa alternativa contrasta com o modelo de concorrência mais comum, onde são
```suggestion
Essa é uma alternativa que contrasta com o modelo de concorrência mais comum, onde são
```

2019-01-02 20:24 UTC, glaucia86 commented on locale/pt-br/about/index.md
> +se preocupar com _deadlock_ de processos, pois não existem _locks_. Quase nenhum função
```suggestion
se preocupar com _deadlock_ de processos, pois não existem _locks_. Quase nenhuma função
```

2019-01-02 20:26 UTC, glaucia86 commented on locale/pt-br/about/index.md
> +ou [Twisted][] do Python, porém leva o modelo de eventos um pouco além. No Node o _[event loop][]_
```suggestion
ou [Twisted][] do Python. Porém, leva o modelo de eventos um pouco mais além. No Node o _[event loop][]_
```

2019-01-02 20:27 UTC, glaucia86 requested changes
Pequenos ajustes. Muito boa a tradução. Parabéns @Drieger ! :)

2019-01-02 23:47 UTC, gustavohenke approved these changes

2019-01-02 23:47 UTC, gustavohenke commented on locale/pt-br/about/index.md
> +[event loop]: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
Podemos substituir os links acima por versões em português (se os tivermos)?

2019-01-02 23:49 UTC, gustavohenke commented
I didn't mean to early approve this 🤦‍♂️
Please make sure @glaucia86's reviews are resolved before merging 😃

2019-01-03 00:02 UTC, glaucia86 commented on locale/pt-br/about/index.md
> +[event loop]: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
Boa ideia @gustavohenke

2019-01-03 10:27 UTC, Drieger commented on locale/pt-br/about/index.md
> +[event loop]: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
Concordo @gustavohenke, mas não encontrei a versão em português, acho que ainda não temos elas traduzidas. A medida que tivermos, podemos ir atualizando esse documento.

2019-01-03 10:31 UTC, Drieger commented
@glaucia86 all suggestions were addressed. Could you take a look again?

2019-01-03 11:45 UTC, JCMais approved these changes

2019-01-03 21:44 UTC, glaucia86 commented
> @glaucia86 all suggestions were addressed. Could you take a look again?

Let me see here again... a minute.

2019-01-03 21:45 UTC, glaucia86 approved these changes
LGTM 👍
Excelent @Drieger

2019-01-04 22:07 UTC, cezaraugusto approved these changes
++

2019-01-05 12:36 UTC, merged