Add nodejs.dev link to get-involved -> learning
nodejs/nodejs.org pull request #2101
Opened 2019-02-20 14:24 UTC by watson

For details see https://medium.com/@nodejs/node-js-selected-by-google-for-dev-top-level-domain-early-access-6b0c5f9205f8

Two questions that needs to be ok'ed before merging:

- I'm not sure if this is the expected way to "handle" translations. I looked at some of the other commits to this file and saw this approach used.
- I came up with link text and description quickly. If someone have a better text for these let me know 😄

2019-02-20 14:56 UTC, vsemozhetbyt commented on locale/uk/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
```suggestion
- [Node.js Guides](https://nodejs.dev) містить посібники з розробки на Node.js.
```

2019-02-20 15:01 UTC, watson commented on locale/uk/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
Thanks 😊

2019-02-20 22:51 UTC, Maledong commented
@celyes: Please trans for your Arabic.

2019-02-20 22:52 UTC, Maledong commented
@nodejs/localization：Please trans for all of your own languages if possible and free.

2019-02-20 22:52 UTC, ghost approved these changes
LGTM in English version

2019-02-20 23:13 UTC, celyes commented
@Maledong 
Updated file : `locale/ar/get-involved/index.md`
See https://github.com/nodejs/nodejs.org/pull/2100

2019-02-21 11:20 UTC, ZYSzys reviewed
AFAIK, nodejs.dev was designed as our new website, not just for learning. It was in development rapidly now.

Maybe it’s not so suitable to add it here, IMHO.

2019-02-26 04:27 UTC, fhemberger commented
I'd put that on hold as well.

2019-04-04 08:53 UTC, haoxins commented on locale/uk/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) містить посібники з розробки на Node.js.
LGTM in the Chinese version

2019-04-04 08:53 UTC, haoxins commented
LGTM in the Chinese version

2019-04-04 21:57 UTC, aymen94 commented on locale/fr/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
```suggestion
- [Node.js Guides](https://nodejs.dev) pour le développement de node. js.
```

2019-04-04 21:59 UTC, aymen94 commented on locale/en/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
```suggestion
- [Node.js Guides](https://nodejs.dev) to Node.js development.
```

2019-04-04 22:00 UTC, aymen94 commented on locale/en/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
Duplicate _Guides_

2019-04-04 22:03 UTC, aymen94 commented on locale/ca/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
- [Node.js Guides](https://nodejs.dev) to development.

2019-04-04 22:05 UTC, aymen94 commented on locale/ca/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
```suggestion
- [Node.js Guides](https://nodejs.dev) to development.
```

2019-04-04 22:06 UTC, aymen94 commented on locale/fa/get-involved/index.md
> +- [Node.js Guides](https://nodejs.dev) Guides to Node.js development.
```suggestion
- [Node.js Guides](https://nodejs.dev) to development.
```

2019-04-07 06:49 UTC, Maledong commented
@aymen94：I don't think it is duplicated and no need to modify, because "Node.js Guides" is the title and " Guides to Node.js development." is the detailled explaination. Since this is still on hold, so I just leave my comment here for others to have a review :)

2019-04-13 02:56 UTC, ghost requested changes
I don't think it is duplicated and no need to modify, because "Node.js Guides" is the title and " Guides to Node.js development." is the detailled explaination. Since this is still on hold, so I just leave my comment here for others to have a review.

@aymen94

2019-09-05 05:44 UTC, ghost requested changes
A lot of things to be changed and conflicts should be resolved.

2019-09-05 06:26 UTC, yous commented
In this branch, there is no `locale/ko/get-involved/index.md` file, so I can't update the corresponding part.

2019-10-14 17:02 UTC, MylesBorins commented
@watson would you be able to rebase?

2019-11-10 16:18 UTC, Trott commented
@watson I'm interested in seeing this get pushed across the finish line. Are you invested enough to resolve the merge conflicts? If so, awesome! If not, I'll close this and (maybe) open my own alternative.

2019-12-23 19:42 UTC, MylesBorins commented
quick ping about conflicts

2020-03-26 10:12 UTC, willin approved these changes

2020-06-15 16:53 UTC, MylesBorins commented
This has been un touched in quite a bit and is stale. Closing. Please feel free to lmk if you would like it reopened

2020-06-15 16:53 UTC, closed without merging