AR: translation for "docs/index.md" AR
nodejs/nodejs.org pull request #2139
Opened 2019-03-05 16:21 UTC by Aissaoui-Ahmed

Arabic translation for `docs/index.md`.

@celyes @ouadie-lahdioui @InterstellarClub

2019-03-06 00:13 UTC, celyes requested changes

2019-03-06 00:13 UTC, celyes commented on locale/ar/docs/index.md
> +- [نظرة عامة على Blocking ضد Non-Blocking](blocking-vs-non-blocking/)
نظرة عامة على Blocking ضد Non-Blocking >> مقارنة عامة بين Blocking و Non-Blocking

2019-03-06 11:09 UTC, celyes approved these changes

2019-03-06 11:11 UTC, celyes commented
Looks good to me 👍

2019-03-06 16:26 UTC, ouadie-lahdioui commented on locale/ar/docs/index.md
> +## عام
ارشادات عامة

2019-03-06 20:44 UTC, Aissaoui-Ahmed commented on locale/ar/docs/index.md
> +## عام
in [english](https://github.com/nodejs/nodejs.org/blame/master/locale/en/docs/guides/index.md#L6) language is sub-paragraph title

2019-03-06 23:19 UTC, Maledong commented
This file should be "docs/guides/index.md" instead of "docs/index.md", so I've helped to fix it :)

2019-03-06 23:19 UTC, ghost approved these changes
LGTM

2019-03-06 23:25 UTC, ghost submitted a review, later dismissed
This file should be "docs/guides/index.md" instead of "docs/index.md", please update all of your files locally and see what's the difference between 'docs/index.md' and 'docs/guides/index.md'. I think you should add this file into the 'docs/guides/', compared with the English one.

![question](https://user-images.githubusercontent.com/40081831/53921096-3dfb2d00-40aa-11e9-98aa-bc3fe7397883.PNG)

2019-03-07 00:00 UTC, ghost approved these changes

2019-03-07 00:01 UTC, Maledong commented
@ouadie-lahdioui：Anything else？

2019-03-07 09:43 UTC, ouadie-lahdioui approved these changes
LGTM

2019-03-07 10:09 UTC, merged