translation of the index page in download section
nodejs/nodejs.org pull request #2208
Opened 2019-04-25 23:07 UTC by maugravena

Translated download/index.md from en to pt-BR

Refs: nodejs/nodejs-pt#72

/cc @nodejs/nodejs-pt

2019-04-26 02:01 UTC, Maledong commented
@nodejs/nodejs-pt: Please have a review, thanks!

2019-04-26 03:49 UTC, gustavohenke requested changes

2019-04-26 03:49 UTC, gustavohenke commented on locale/pt-br/download/index.md
> +        Baixar o código fonte do Node.js ou um instalador pré-compilado para o seu sistema, e comece a devenvolver hoje.
```suggestion
        Baixe o código fonte do Node.js ou um instalador pré-compilado para o seu sistema, e comece a desenvolver hoje.
```

2019-04-26 03:49 UTC, gustavohenke commented on locale/pt-br/download/index.md
> +        Membros da comunidade Node.js mantêm compilados não oficiais do Node.js para plataformas adicionais. Note, que tais compilados não são mantidos pela equipe principal do Node.js e pode não est
```suggestion
        Membros da comunidade Node.js mantêm compilados não oficiais do Node.js para plataformas adicionais. Note, tais compilados não são mantidos pela equipe oficial do Node.js e podem não estar no mesmo nível de compilação da versão atual do Node.js.
```

2019-04-26 11:15 UTC, Drieger commented
LGTM after @gustavohenke suggestions are addressed

2019-04-26 12:29 UTC, maugravena commented
Thanks @gustavohenke

2019-04-26 20:32 UTC, JCMais approved these changes

2019-04-26 20:32 UTC, JCMais commented
LGTM, thanks @maugravena

2019-04-27 00:56 UTC, Maledong commented
@gustavohenke: Is it fine with you?

2019-04-27 02:20 UTC, gustavohenke approved these changes
😃

2019-04-27 03:12 UTC, merged

2019-04-27 03:12 UTC, Maledong commented
Thanks all for your contributions!