Add IBM i to package manager page
nodejs/nodejs.org pull request #2223
Opened 2019-05-07 21:21 UTC by ThePrez

Opening as a draft, as I figure it makes sense to "land" this when Node 12 is available from IBM (but am willing to take feedback in the meantime).

2019-05-08 03:32 UTC, Maledong commented
@nodejs/website：Please have a review, everything is fine with me.

2019-05-09 16:28 UTC, mhdawson approved these changes
LGTM

2019-05-09 16:44 UTC, srl295 approved these changes

2019-05-09 17:37 UTC, aymen94 commented
LGTM

2019-05-09 17:37 UTC, aymen94 approved these changes

2019-05-10 03:16 UTC, Maledong commented
@nodejs/website：Please have a translation if possible for this, thanks anyway!

2019-05-10 07:33 UTC, yous commented
It seems that `*` in "\*ALLOBJ" is not for italic: https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzarl/rzarlallobjsa.htm

But `*` can be parsed as a part of markdown syntax, we should use `\*ALLOBJ special authority` instead of `*ALLOBJ special authority`.

2019-05-10 07:44 UTC, yous commented
@nodejs/nodejs-ko Updated Korean translation. Please take a look.

2019-05-11 03:56 UTC, Aissaoui-Ahmed approved these changes

2019-05-11 04:00 UTC, Aissaoui-Ahmed commented
Update `package-manager.md` 
@celyes take a look !

2019-05-11 11:05 UTC, celyes requested changes

2019-05-11 11:05 UTC, celyes commented on locale/ar/download/package-manager.md
> +لتثبيت Node.js 12.x من سطر الأوامر شغل التالي كمستخدم مع \*ALLOBJ  سلطة خاصة :
change this line to the following:

لتثبيت Node.js 12.x باستخدام سطر الأوامر، شغل الامر التالي كمستخدم مع سلطة \*ALLOBJ الخاصة :
Thank you so much ! :+1:

2019-05-11 11:05 UTC, celyes commented on locale/ar/download/package-manager.md
> +يمكن أيضًا تثبيت Node.js مع IBM i وصول العملاء لحلول المنتج. انظر [هذه الوثيقة الدعم](http://www-01.ibm.com/support/docview.wss?uid=nas8N1022619) .لمزيد من التفاصيل
Change this line with following : 

يمكن أيضًا تثبيت Node.js مع منتج IBM i الخاص بحلول وصول العملاء. انظر [وثيقة الدعم هذه](http://www-01.ibm.com/support/docview.wss?uid=nas8N1022619) .لتفاصيل أكثر
thank you so much ^^
:+1:

2019-05-11 15:06 UTC, celyes approved these changes
Looks great
thank you all @ThePrez @Aissaoui-Ahmed @Maledong @aymen94 @ouadie-lahdioui @mhdawson

2019-05-12 01:54 UTC, merged

2019-05-12 01:54 UTC, Maledong commented
Thank you all!