Translate/guide translate japanese.
nodejs/nodejs.org pull request #2229
Opened 2019-05-12 16:17 UTC by silverskyvicto

Hi.

I translate a part of guide.

2019-05-12 16:55 UTC, hiroppy commented
/cc @nodejs/nodejs-ja

2019-05-13 05:09 UTC, e-jigsaw commented
@silverskyvicto https://github.com/nodejs/nodejs.org/pull/2228#issuecomment-491677469 にもコメントを書いたんですが、こちらもお願いします 🙏

2019-05-14 05:41 UTC, silverskyvicto commented
@e-jigsaw 翻訳した範囲はスタイルを揃えてみました。

2019-05-14 12:35 UTC, okuryu commented on locale/ja/docs/guides/debugging-getting-started.md
> +same-origin-policy は、Web サイトがこの HTTP 接続を確立できないようにします。
見出しと合わせて「同一生成元ポリシー」と言ってもいいんじゃないでしょうか。
```suggestion
同一生成元ポリシーは、Web サイトがこの HTTP 接続を確立できないようにします。
```

2019-05-16 01:00 UTC, e-jigsaw commented on locale/ja/docs/guides/diagnostics-flamegraph.md
> +Solaris vms はフレームグラフには不要です。:
```suggestion
Solaris vms はフレームグラフには不要です。
```

?

2019-05-16 01:02 UTC, e-jigsaw commented on locale/ja/docs/guides/index.md
>  ---
このファイルもフォーマットを揃えてください〜

2019-05-16 03:40 UTC, silverskyvicto commented
@e-jigsaw 揃えました。

2019-05-16 12:20 UTC, okuryu approved these changes
👍

2019-05-17 04:15 UTC, e-jigsaw requested changes
https://github.com/nodejs/nodejs.org/pull/2229/files#r284506260

2019-05-17 12:51 UTC, silverskyvicto commented on locale/ja/docs/guides/index.md
>  ---
@e-jigsaw こんな感じですか？

2019-05-18 19:27 UTC, e-jigsaw commented on locale/ja/docs/guides/index.md
>  ---
Thanks!

2019-05-18 19:29 UTC, e-jigsaw approved these changes
ありがとうございます！

Looks Great

2019-05-22 08:35 UTC, merged