translation of the releases page in download section
nodejs/nodejs.org pull request #2235
Opened 2019-05-18 16:39 UTC by maugravena

Translated download/releases.md from en to pt-BR

Refs: [nodejs/nodejs-pt#72](https://github.com/nodejs/nodejs-pt/issues/72)

/cc @[nodejs/nodejs-pt](https://github.com/nodejs/nodejs-pt)

2019-05-19 01:28 UTC, JCMais approved these changes
LGTM, thanks again @maugravena

2019-05-20 11:19 UTC, Drieger requested changes

2019-05-20 11:19 UTC, Drieger commented on locale/pt-br/download/releases.md
> +modules: "<code>NODE_MODULE_VERSION</code> Se refere ao número de versão de ABI (application binary interface) do Node.js, usado para determinar quais versões do Node.js que compilam binários de comp
```suggestion
modules: "<code>NODE_MODULE_VERSION</code> Se refere ao número de versão de ABI (application binary interface) do Node.js, usado para determinar quais versões do Node.js que compilam binários de complemento do C++ que podem ser carregados sem precisarem ser re-compilados. Ele costumava ser armazenado como um valor hexadecimal em versões anteriores, mas agora é representado como um inteiro."
```

2019-05-21 10:53 UTC, Drieger approved these changes

2019-05-22 08:37 UTC, merged