doc: about/releases traduzido para pt-br
nodejs/nodejs.org pull request #2256
Opened 2019-06-11 14:56 UTC by AugustoCalaca

Nesse PR a página about/release foi traduzida
@nodejs/nodejs-pt

2019-06-11 16:44 UTC, TiagoDanin requested changes

2019-06-11 16:44 UTC, TiagoDanin commented on locale/pt-br/about/releases.md
> + As pricipais versões do Node.js entram em status de lançamento _Atual_ por seis meses, o qual dá tempo aos autores da biblioteca adicionarem suporte a elas. Depois de seis meses, os lançamentos ímpa
**principais**

2019-06-12 02:23 UTC, TiagoDanin approved these changes
:100: LGTM

2019-06-14 07:20 UTC, merged

2020-04-20 20:36 UTC, AugustoCalaca commented
update the list 
ping friendly @khaosdoctor