how-to-use-fs-create-write-stream pt-br
nodejs/nodejs.org pull request #2260
Opened 2019-06-14 21:16 UTC by VacariGabriel

2019-06-14 22:09 UTC, TiagoDanin requested changes

2019-06-14 22:09 UTC, TiagoDanin commented on locale/pt-br/knowledge/advanced/streams/how-to-use-fs-create-write-stream.md
> +title: Como usar fs.createWriteStream?
Sugestion: `Como usar o fs.createWriteStream?`

2019-06-14 22:09 UTC, TiagoDanin commented on locale/pt-br/knowledge/advanced/streams/how-to-use-fs-create-write-stream.md
> +A função `fs.createWriteStream()` cria um fluxo corrente de uma maneira muito simples. Depois de chamar a função `fs.createWriteStream` com o caminho da pasta, voce tem um fluxo corrente. Os objetos
`voce` ~> `você`

2019-06-15 12:36 UTC, TiagoDanin approved these changes
:100: LGTM

2019-06-18 18:57 UTC, glaucia86 approved these changes
LGTM 👍 

Thank you for your contribution @VacariGabriel

2019-06-18 19:00 UTC, glaucia86 commented
cc: @Maledong @Trott approved it this translation pt-br

2019-06-19 14:18 UTC, aymen94 approved these changes

2019-06-20 07:20 UTC, merged

2019-06-20 07:21 UTC, ZYSzys commented
@VacariGabriel Thanks for contributing!