doc: about/trademark traduzido para pt-br
nodejs/nodejs.org pull request #2261
Opened 2019-06-14 21:29 UTC by thalees

Nesse PR foi traduzida a seguinte página:
:large_blue_circle: **prioridade média** - 1. Página: About
- [x] trademark.md

@nodejs/nodejs-pt

2019-06-14 22:15 UTC, TiagoDanin requested changes

2019-06-14 22:15 UTC, TiagoDanin commented on locale/pt-br/about/trademark.md
> +As marcas registradas do Node.js, marcas de serviço e marcas gráficas símbolos de
`... marcas gráficas são símbolos de...`

2019-06-14 22:15 UTC, TiagoDanin commented on locale/pt-br/about/trademark.md
> +que não enganaem as pessoas ou fazem com que confundam o Node.js com outro software
`enganaem` ~> `enganem`

2019-06-14 22:17 UTC, TiagoDanin commented
**Note:** Description of pull request and title must be in English

2019-06-15 13:12 UTC, thalees commented on locale/pt-br/about/trademark.md
> +que não enganaem as pessoas ou fazem com que confundam o Node.js com outro software
Done.

2019-06-15 13:12 UTC, thalees commented on locale/pt-br/about/trademark.md
> +As marcas registradas do Node.js, marcas de serviço e marcas gráficas símbolos de
Done.

2019-06-15 13:15 UTC, TiagoDanin approved these changes
:100: LGTM

2019-06-18 18:56 UTC, glaucia86 approved these changes
LGTM 👍 

Thank you for your contribution @thalees

2019-06-18 18:59 UTC, glaucia86 commented
cc: @Maledong @Trott I approved it this translation pt-br

2019-06-20 23:38 UTC, merged