Translate command-line/how-to-get-colors-on-the-command-line into pt_BR
nodejs/nodejs.org pull request #2274
Opened 2019-06-20 05:59 UTC by xavierleonardo

## Changes

This PR tranlate command-line/how-to-get-colors-on-the-command-line doc.

### Please review

- @nodejs/nodejs-pt
- @khaosdoctor 
- @glaucia86

2019-06-20 16:42 UTC, khaosdoctor commented
Hey man! Can you please put the original version in comments in the file? This way we can check the translation faster!

Example: https://github.com/nodejs/nodejs.org/blob/7f31f2fd492175da5bf077b246ae939a2a4576d6/locale/pt-br/docs/guides/abi-stability.md#L10-L25

2019-06-20 17:35 UTC, xavierleonardo commented
> Hey man! Can you please put the original version in comments in the file? This way we can check the translation faster!
> 
> Example:
> 
> https://github.com/nodejs/nodejs.org/blob/7f31f2fd492175da5bf077b246ae939a2a4576d6/locale/pt-br/docs/guides/abi-stability.md#L10-L25

Sure, @khaosdoctor. Already done.

2019-06-20 19:02 UTC, khaosdoctor approved these changes
LGTM 👍

2019-06-20 19:02 UTC, khaosdoctor commented
Another one is GTG!

cc: @Maledong @Trott @MylesBorins @fhemberger

2019-06-20 19:32 UTC, glaucia86 requested changes
@xavierleonardo só a palavra 'configure' que você acabou engolindo a letra... só acertar que aprovo aqui para ti!

cc: @khaosdoctor

2019-06-20 19:32 UTC, glaucia86 commented on locale/pt-br/knowledge/command-line/how-to-get-colors-on-the-command-line.md
> +Você pode pensar no seu terminal dizendo para si mesmo, "Faça isto verde. Não, faça azul. Não, faça isto vermelho. Sem mais cores agora? É vermelho mesmo, então." Os códigos são lidos em ordem invers
```suggestion
Você pode pensar no seu terminal dizendo para si mesmo, "Faça isto verde. Não. Faça azul. Não. Faça isto vermelho. Sem mais cores agora? É vermelho mesmo, então." Os códigos são lidos em ordem inversa, e o último/'mais interno' é aplicado. Isto pode ser bastante útil se você estiver usando uma biblioteca que configura seu próprio padrão de cores que você não gosta - se você passar uma cor na _string_ que você passa para a biblioteca, ela vai sobrepor as cores internas da biblioteca.
```

2019-06-21 01:17 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-get-colors-on-the-command-line.md
> +Você pode pensar no seu terminal dizendo para si mesmo, "Faça isto verde. Não, faça azul. Não, faça isto vermelho. Sem mais cores agora? É vermelho mesmo, então." Os códigos são lidos em ordem invers
Passou batido por mim D:

2019-06-21 12:46 UTC, TiagoDanin requested changes

2019-06-21 12:46 UTC, TiagoDanin commented on locale/pt-br/knowledge/command-line/how-to-get-colors-on-the-command-line.md
> +Quando trabalhamos com a linha de comando, pode ser muito últil e divertido ter respostas coloridas. Para colorir a resposta do console você precisa usar códigos escape ANSI. O módulo [colors.js](htt
`últil` ~> `útil`

2019-06-21 12:46 UTC, TiagoDanin commented on locale/pt-br/knowledge/command-line/how-to-get-colors-on-the-command-line.md
> +Quando trabalhamos com a linha de comando, pode ser muito últil e divertido ter respostas coloridas. Para colorir a resposta do console você precisa usar códigos escape ANSI. O módulo [colors.js](htt
Sugestion: ...precisa usar códigos de escape ANSI.

2019-06-21 12:46 UTC, TiagoDanin commented on locale/pt-br/knowledge/command-line/how-to-get-colors-on-the-command-line.md
> +Note também, a partir do segundo par de chamadas `console.log` que, uma vez atrbuído, o valor da cor persiste como parte da _string_. Isto é porque, por debaixo dos panos, a tag de cor ANSI apropriad
`atrbuído` ~> `atribuído`

2019-06-21 12:46 UTC, TiagoDanin commented on locale/pt-br/knowledge/command-line/how-to-get-colors-on-the-command-line.md
> +O último par de chamadas `console.log` é, provavelmente, o mais importante. Por causa da forma em que o `colors.js` e os códigos de cores ANSI funcionam, se mais de uma propriedade de cor é atribuída
`primeia` ~> `primeira`

2019-06-22 02:10 UTC, xavierleonardo commented
@glaucia86 e @TiagoDanin, já corrigi as palavras solicitadas.

Meu teclado anda falhando bastante e eu vou ter que parar essa atividade até eu resolver isso. Senão sempre haverão vários _typos_ desses e, consequentemente, mais trabalho na revisão hehehe. E olha que eu ainda revisei o texto e corrigi vários.

2019-06-22 13:17 UTC, TiagoDanin approved these changes

2019-06-27 00:44 UTC, merged