PT-BR/Translation for what-is-require and npm/what-is-npm
nodejs/nodejs.org pull request #2279
Opened 2019-06-20 21:04 UTC by elainemattos

Hey everyone,

This PR translates to portuguese the pages `what-is-require` and `what-is-npm`.
The `getting-started` and `npm` folder were created for the translated files.

@glaucia86 @khaosdoctor @nodejs/nodejs-pt

2019-06-20 23:44 UTC, MaledongGit commented
@nodejs/nodejs-pt : Please have a review, thanks!

2019-06-21 12:35 UTC, TiagoDanin requested changes

2019-06-21 12:35 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/npm/what-is-npm.md
> +`npm`, é a abreviação para Node Package Manager (Gerenciador de Pacotes do Node), é duas coisas, em primeiro lugar, é um repositório online para a publicação de projetos Node.js de códido aberto; seg
`códido` ~> `código`
`dependencias` ~> `dependências`

2019-06-21 12:35 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/what-is-require.md
> +NOTA: você pode omitir ".js" que o `require` irá anexá-lo automaticamente, se necessário. Para informações mais detalhadas, consulte [os documentos oficiais](https://nodejs.org/docs/v0.4.2/api/module
Sugestion: Para mais informações, consulte a [documentação official](https://nodejs.org/docs/v0.4.2/api/modules.htmll#all_Together...)

2019-06-21 18:58 UTC, cezaraugusto commented on locale/pt-br/knowledge/getting-started/npm/what-is-npm.md
> +`npm`, é a abreviação para Node Package Manager (Gerenciador de Pacotes do Node), é duas coisas, em primeiro lugar, é um repositório online para a publicação de projetos Node.js de código aberto; seg
```diff
- `npm`, é a abreviação para Node Package Manager (Gerenciador de Pacotes do Node), é duas coisas, em primeiro lugar, é 
+ `npm`, é a abreviação para Node Package Manager (Gerenciador de Pacotes do Node). O npm é duas coisas: em primeiro lugar, é 
```

2019-06-21 19:00 UTC, cezaraugusto commented on locale/pt-br/knowledge/getting-started/npm/what-is-npm.md
> +`npm`, é a abreviação para Node Package Manager (Gerenciador de Pacotes do Node), é duas coisas, em primeiro lugar, é um repositório online para a publicação de projetos Node.js de código aberto; seg
entendo que estava assim antes mas seria legal se a gente aproveitasse a oportunidade para consertar. O comentário é uma sugestão, se achar que de outra forma fica melhor é válido também

2019-06-21 19:20 UTC, TiagoDanin approved these changes

2019-06-21 19:26 UTC, elainemattos commented on locale/pt-br/knowledge/getting-started/npm/what-is-npm.md
> +`npm`, é a abreviação para Node Package Manager (Gerenciador de Pacotes do Node), é duas coisas, em primeiro lugar, é um repositório online para a publicação de projetos Node.js de código aberto; seg
Acho que fica melhor desta forma!

2019-06-21 19:27 UTC, elainemattos commented
Posso remover a parte Original em inglês? Ou será mergeado com ela comentada?

2019-06-21 21:10 UTC, cezaraugusto commented
@elainemattos pode sim. os commits anteriores cuidam do texto removido caso a gente precise consultá-lo.

2019-06-22 08:06 UTC, MaledongGit commented
@cezaraugusto：Is it finished and can be merged?

2019-06-24 17:49 UTC, khaosdoctor commented
LGTM

2019-06-27 00:58 UTC, MaledongGit commented
Please also see #2278. We don't need to do translations, if you have other feedbacks, please leave them here :)

2019-06-29 10:06 UTC, merged