PT-BR Translation for javascript-conventions/using-ECMA5-in-nodejs
nodejs/nodejs.org pull request #2281
Opened 2019-06-22 06:45 UTC by romulo94

@nodejs/nodejs-pt

2019-06-23 21:50 UTC, romulo94 commented
@khaosdoctor

2019-06-24 17:40 UTC, khaosdoctor requested changes

2019-06-24 17:40 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/using-ECMA5-in-nodejs.md
> +Ao desenvolver no navegador, há muitas funções maravilhosas construídas em JavaScript que não podemos usar, porque certos navegadores não as implementam. Como resultado, a maioria dos desenvolvedores
```suggestion
Ao desenvolver no navegador, há muitas funções maravilhosas construídas em JavaScript que não podemos usar, porque certos navegadores não as implementam. Como resultado, a maioria dos desenvolvedores nunca as usa. No Node, no entanto, podemos assumir que todos têm a mesma implementação de JavaScript e, como tal, podem usar essas funções maravilhosas e não implementá-las repetidamente em nossas próprias bibliotecas.
```

2019-06-24 17:40 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/using-ECMA5-in-nodejs.md
> +A seguir está uma lista de alguns pedaços interessantes da API que não são considerados seguros para uso em uma configuração da Web, mas que são incorporados ao mecanismo V8 do node.
```suggestion
A seguir está uma lista de algumas partes interessantes da API que não são considerados seguros para uso no desenvolvimento para a Web, mas que são nativos ao mecanismo V8 do node.
```

2019-06-24 17:40 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/using-ECMA5-in-nodejs.md
> +- `Object.seal(obj)` - Impede que o código adicione ou exclua propriedades ou altere os descritores de qualquer propriedade em um objeto. Valores de propriedade podem ser alterados no entanto.
```suggestion
- `Object.seal(obj)` - Impede que o código adicione ou exclua propriedades ou altere os descritores de qualquer propriedade em um objeto. No entanto, valores de propriedade podem ser alterados.
```

2019-06-25 23:41 UTC, romulo94 commented on locale/pt-br/knowledge/javascript-conventions/using-ECMA5-in-nodejs.md
> +A seguir está uma lista de alguns pedaços interessantes da API que não são considerados seguros para uso em uma configuração da Web, mas que são incorporados ao mecanismo V8 do node.
@khaosdoctor it's done

2019-06-26 18:03 UTC, khaosdoctor approved these changes
LGTM 👍

2019-06-26 18:03 UTC, khaosdoctor commented
cc: @MaledongGit @Trott

2019-06-27 01:00 UTC, MaledongGit commented
Please also see #2278. We don't need to do translations for knowledge yet, if you have other feedbacks, please leave them here :)

2019-06-27 01:00 UTC, closed without merging