PT-BR/Translation for what-is-json.md (@thierrysantoos1)
nodejs/nodejs.org pull request #2287
Opened 2019-06-23 13:15 UTC by thierrysantoos1

Hi everyone,

This PR translates to portuguese the page what-is-json.md.
The javascript-conventions folder were created for the translated file.

@glaucia86 @khaosdoctor @nodejs/nodejs-pt

2019-06-24 17:47 UTC, khaosdoctor requested changes
A few typos

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +o padrão de fato para a web. JSON pode ser representado como uma lista de
```suggestion
o padrão para a web. JSON pode ser representado como uma lista de
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +valores, ex: um Array, ou um hash de propriedades e valores, ex: um
```suggestion
valores, por exemplo, um Array, ou um hash de propriedades e valores, por exemplo, um
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +O JavaScript fornece 2 métodos, um para codificar estrutura de dados para json
```suggestion
O JavaScript fornece 2 métodos. Um para codificar estrutura de dados para JSON
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +e o outro para decodificar json para objetos e arrays javascript.
```suggestion
e o outro para decodificar JSON para objetos e arrays javascript.
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +Eles são ambos disponíveis no objeto `JSON` que está disponível no escopo
```suggestion
Ambos estão disponíveis no objeto `JSON` que existe no escopo
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +// imprimi '{"nome":"John Doe","idade":32,"titulo":"Vice Presidente do JavaScript"}'
```suggestion
// imprime '{"nome":"John Doe","idade":32,"titulo":"Vice Presidente do JavaScript"}'
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +você pode anticipar os erros encapsulando a chamada em um block try/catch.
```suggestion
você pode antecipar os erros encapsulando a chamada em um bloco try/catch.
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +parece fazer sentido no começo. Mas lembre-se que o JSON é um formato de dados,
```suggestion
parecer fazer sentido no começo. Mas lembre-se que o JSON é um formato de dados,
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +não é um formato para transferir objetos javascript complexos junto com
```suggestion
não um formato para transferir objetos javascript complexos junto com
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +- **Plugins para IDEs/editores**: Existem muitos plugins/extensões disponíveis para a maioria dos IDEs/editores que validam o JSON para você. Alguns editores como o `VS Code` vêm com JSON IntelliSens
```suggestion
- **Plugins para IDEs/editores**: Existem muitos plugins/extensões disponíveis para a maioria dos IDEs/editores que validam o JSON para você. Alguns editores como o `VS Code` vêm com JSON intelliSense e validação pronto para uso.
```

2019-06-24 17:47 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-json.md
> +# imprimi "{ \"um\": 1 }"
```suggestion
# imprime "{ \"um\": 1 }"
```

2019-06-24 22:10 UTC, thierrysantoos1 commented
Hi, I have fixed right now.

2019-06-26 18:04 UTC, khaosdoctor approved these changes
LGTM 👍

2019-06-26 18:04 UTC, khaosdoctor commented
cc: @Maledong @trott

2019-06-27 00:49 UTC, MaledongGit commented
@thierrysantoos1  We don't need to do translations for knowledge now, please also see #2278 :)
So I'll close this, and if you have other feedbacks, you can leave them here.

2019-06-29 10:05 UTC, merged