Translate part of knowledge/javascript-conventions into portuguese (pt-br)
nodejs/nodejs.org pull request #2290
Opened 2019-06-24 13:42 UTC by ftonato

Hello,

I have finished the `knowledge/javascript-conventions/what-are-truthy-and-falsy-values.md` file, can you validate and approve this one?

/cc @nodejs/nodejs-pt
/cco @glaucia86 @khaosdoctor

2019-06-24 17:34 UTC, khaosdoctor requested changes
Did some comments

2019-06-24 17:34 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-are-truthy-and-falsy-values.md
> +Note que todas os objetos e arrays são truthy, ainda que sejam vazios.
```suggestion
Note que todos os objetos e arrays são truthy, ainda que sejam vazios.
```

2019-06-24 17:34 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-are-truthy-and-falsy-values.md
> +Truthiness e Falsiness também entram em jogo com operadores lógicos. Quando usamos operadores lógicos AND/OR, os valores serão convertidos com base em truthiness ou falseness e, em seguida, a express
```suggestion
Truthiness e Falsiness também entram em jogo com operadores lógicos. Quando usamos operadores lógicos AND/OR, os valores serão convertidos com base em truthiness ou falsiness e, em seguida, a expressão será resolvida para o último valor truthy. Regras de curto-circuito se aplicam. Aqui está um breve exemplo.
```

2019-06-24 17:34 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-are-truthy-and-falsy-values.md
> +JavaScript é uma linguagem fracamente tipada. Isso significa que diferentes tipos podem ser usados em operações e a linguagem tentará converter os tipos até que a operação faça sentido.
```suggestion
JavaScript é uma linguagem fracamente tipada. Isso significa que diferentes tipos podem ser usados em operações e a linguagem tentará converter estes tipos até que a operação faça sentido.
```

2019-06-24 21:43 UTC, ftonato commented
> Did some comments

Hello, I have fixed right now, tks :)

2019-06-26 18:04 UTC, khaosdoctor approved these changes
Awesome! LGTM 👍 

cc: @Trott @MaledongGit

2019-06-27 00:50 UTC, MaledongGit commented
Please also see #2278. We don't need to do translations, if you have other feedbacks, please leave them here :)

2019-06-27 00:50 UTC, closed without merging