Move C+L at NodeConfCo to the past
nodejs/nodejs.org pull request #2295
Opened 2019-06-26 16:02 UTC by julianduque

Event was a success!! now it's time to move it to the past ;)

2019-06-26 16:09 UTC, Trott approved these changes

2019-06-27 01:38 UTC, MaledongGit commented
@nodejs/website：Please check your own language so as to confirm that 'To be announced' and other names of events are correctly translated, I used English in union.

2019-06-30 16:00 UTC, e-jigsaw commented
ja translated :)

2019-07-02 18:21 UTC, edsadr approved these changes

2019-07-02 18:33 UTC, Aissaoui-Ahmed requested changes

2019-07-02 18:33 UTC, Aissaoui-Ahmed commented on locale/ar/get-involved/code-and-learn.md
> +- To be accounced
سوف يتم الإعلان عنها

2019-07-03 07:15 UTC, aymen94 approved these changes

2019-07-03 09:07 UTC, Aissaoui-Ahmed approved these changes

2019-07-03 21:36 UTC, Trott commented
Should this land (to update the listing on the website) and any additional translations can happen later?

2019-07-05 14:25 UTC, bnb commented
@Trott I would assume that is the process 🤔

2019-07-05 15:07 UTC, merged