Translate knowledge/file-system/how-to-read-files-in-nodejs into russian (ru)
nodejs/nodejs.org pull request #2298
Opened 2019-06-27 12:38 UTC by Palidos

how-to-read-files-in-nodejs

2019-06-27 19:43 UTC, alexandrtovmach commented
Wow, thanks for your contribution. I'll check it soon.

If you have any plans to continue translation, please take a look an issue about Russian community.

2019-06-28 06:31 UTC, alexandrtovmach requested changes
1. Имеет смысл удалить закомментированный текст оригинала.
2. Рекомендую использовать mdash тире, вместо дефисов. Да, я вижу что в оригинале дефисы, но зачем множить ошибки

2019-06-28 06:31 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +Чтение содержимого файла - очень распространенная задача программирования, и, как и для многих других вещей, базовый API Node.js предоставляет методы, позволяющие упростить эту задачу. Существует мно
> Самый простой способ прочитать все содержимое файла, это с помощью `fs.readFile`.

"это с помощью" ― некорректно. Может лучше:
- "это использовать"
- "с помощью"

или перефразировать предложение:
"Что бы прочитать всё содержимое файла, проще всего использовать `fs.readFile`"

2019-06-28 06:31 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +    // file = (string) путь до файла, который нужно прочитать
путь к файлу

2019-06-28 06:31 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +`encoding` это необязательный параметр, который указывает тип кодировки, с которой будет прочитан файл. Возможные кодировки: 'ascii', 'utf8' и 'base64'. Если кодировка не указана, по умолчанию исполь
тип кодировки, для чтения файла

2019-06-28 06:31 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +`callback` - это функция, которая вызывается, когда файл был прочитан и содержимое готово - ей передается два аргумента,` error` и `data`. Если ошибки нет, `error` будет иметь значение` null`, а `dat
` error` - лишний пробел

2019-06-28 06:31 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +Давайте теперь рассмотрим пример того, что происходит, когда вы пытаетесь прочитать недопустимый файл - самый простой пример - это тот файл, которого не существует.
это тот файл, которого не существует. - слишком сложно для такой простой формулировки. Может лучше:

- "несуществующий файл"

2019-06-28 06:31 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +<!-- This is a basic Node.js [Error object](/what-is-the-error-object) - it can often be useful to log `err.stack` directly, since this contains a stack trace to the location in code at which the Err
[Объект ошибки] - не уверен что стоит переводить подобное словосочетание. Ну а если всё-таки переводим, то нужно сохранять значимость:

[объект Ошибки]

2019-06-28 13:03 UTC, Palidos commented
@alexandrtovmach Listed mistakes were fixed.

2019-06-28 13:09 UTC, alexandrtovmach requested changes
Более практично использовать непосредственно знак тире "―", вместо кода `&mdash;`, просто удобнее читать

2019-06-28 13:09 UTC, alexandrtovmach commented on locale/ru/knowledge/file-system/how-to-read-files-in-nodejs.md
> +Это базовый [Error object](/what-is-the-error-object) Node.js &mdash; часто может быть полезно вызывать `err.stack` напрямую, поскольку он содержит трассировку стека до места в коде, в котором был со
"в котором был создан Объект ошибки."

Ещё одно упоминание Error object поправь

2019-06-28 14:20 UTC, alexandrtovmach approved these changes

2019-06-28 14:22 UTC, alexandrtovmach commented
@Palidos Looks okay for me. Thanks for contribution

2019-06-28 20:44 UTC, Palidos commented
@alexandrtovmach If I have more translated files ready for a review, should I commit it to this pull request or better create a new one?

2019-06-29 08:19 UTC, alexandrtovmach commented
@Palidos Basing on this staled issue #2284, I can't answer now. Because I don't understand the main process of how it's should work.

Contributor docs told to not make direct PR into nodejs.org repo, and use locale team, but we haven't Russian team, so I'm confused...

2019-06-30 02:55 UTC, MaledongGit commented
@nodejs/nodejs-ru ，Any ideas or suggestions about this translation？

2019-07-01 06:20 UTC, alexandrtovmach commented
@MaledongGit in case of I'm only one active member of @nodejs/nodejs-ru we can merge it

2019-07-01 08:46 UTC, merged