pt-BR: Translate 'how-to-use-util-inspect'
nodejs/nodejs.org pull request #2304
Opened 2019-06-30 17:30 UTC by vbertazzo

Hey everyone,

This PR translates to Brazilian Portuguese the page `how-to-use-util-inspect` from the section `getting-started`.

@glaucia86 @khaosdoctor @nodejs/nodejs-pt

2019-07-01 14:54 UTC, khaosdoctor requested changes
A typo and a few suggestions for better understanding

2019-07-01 14:54 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +O Node oferece uma função utilitária, para fins de depuração, que retorna uma representação string de um objeto. `util.inspect ()` pode ser de grande ajuda quando utilizada com propriedades de grande
```suggestion
O Node oferece uma função utilitária, para fins de depuração, que retorna uma representação string de um objeto. `util.inspect()` pode ser de grande ajuda quando utilizada com propriedades de objetos que são muito grandes ou complexos.
```

2019-07-01 14:54 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +O argumento `depth` é o número de níveis dentro de um objeto aninhado para ser recursivo - o padrão é 2. Configurá-lo para `null` fará com que ele recurse tudo, mostrando todos os níveis. Compare o t
```suggestion
O argumento `depth` é o número de níveis dentro de um objeto aninhado para ser recursivo - o padrão é 2. Configurá-lo para `null` fará com que ele vá até o último nível, mostrando todos os níveis. Compare o tamanho dos outputs dessas duas instruções `util.inspect` no REPL:
```

2019-07-03 15:37 UTC, khaosdoctor approved these changes
LGTM

2019-07-03 15:37 UTC, khaosdoctor commented
@Trott @MaledongGit

2019-07-03 15:56 UTC, TiagoDanin requested changes
Do not mix Portuguese with Enslish

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +O output vai ser:
```suggestion
O resultado vai ser:
```
or
```suggestion
A saída vai ser:
```

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +Esta é uma listagem de todas as propriedades enumeráveis ​​do objeto `console`. Também vale a pena notar que `console.dir` é um wrapper em torno de ` util.inspect` que utiliza seus argumentos padrão.
```suggestion
Esta é uma listagem de todas as propriedades enumeráveis ​​do objeto `console`. Também vale a pena notar que `console.dir` é um wrapper em torno de ` util.inspect` que utiliza seus argumentos padrões.
```

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +`util.inspect` pode também receber diversos argumentos opcionais, mostrados aqui com seus valores padrão:
```suggestion
`util.inspect` pode também receber diversos argumentos opcionais, mostrados aqui com seus valores padrões:
```

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +Por exemplo, `util.inspect(myObj, true, 7, true)` inspecionaria `myObj`, mostrando todas as propriedades ocultas e não ocultas até uma profundidade de `7` e coloriria o output. Vamos conferir os argu
```suggestion
Por exemplo, `util.inspect(myObj, true, 7, true)` inspecionaria `myObj`, mostrando todas as propriedades ocultas e não ocultas até uma profundidade de `7` e coloriria o resultado. Vamos conferir os argumentos individualmente.
```

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +O argumento `depth` representa o número de níveis dentro de um objeto aninhado para ser recursivo - o padrão é 2. Configurá-lo para `null` fará com que ele vá até o último nível, mostrando todos os n
```suggestion
O argumento `depth` representa o número de níveis dentro de um objeto aninhado para ser recursivo - o padrão é 2. Configurá-lo para `null` fará com que ele vá até o último nível, mostrando todos os níveis. Compare o tamanho dos resultados dessas duas instruções `util.inspect` no REPL:
```

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +O argumento opcional `showHidden` é um booleano que determina se as propriedades 'não-enumeráveis' de um objeto serão ou não exibidas - o padrão é `false`, o que tende a resultar em um output muito m
```suggestion
O argumento opcional `showHidden` é um booleano que determina se as propriedades 'não-enumeráveis' de um objeto serão ou não exibidas - o padrão é `false`, o que tende a resultar em uma saída muito mais legível. Isso não é algo que um iniciante precise se preocupar na maior parte do tempo, mas vale a pena demonstrar brevemente. Mais uma vez, tente o seguinte no REPL:
```

2019-07-03 15:56 UTC, TiagoDanin commented on locale/pt-br/knowledge/getting-started/how-to-use-util-inspect.md
> +Finalmente, o argumento opcional `colorize` é um booleano que adiciona códigos de escape ANSI ao output da string. Quando utilizado em uma janela de terminal, o output deve aparecer colorido.
```suggestion
Finalmente, o argumento opcional `colorize` é um booleano que adiciona códigos de escape ANSI ao resultado da string. Quando utilizado em uma janela de terminal, o output deve aparecer colorido.
```

2019-07-03 17:28 UTC, TiagoDanin approved these changes
LGTM :100:

2019-07-04 09:45 UTC, merged