nodejs-pt-br: Add file translated > what-is-the-arguments-object.md
nodejs/nodejs.org pull request #2318
Opened 2019-07-04 13:50 UTC by fernandoors

Hello everyone,

The translation file 'what-is-the-arguments-object.md'  was completed. 

@nodejs/nodejs-pt
@khaosdoctor

2019-07-05 14:25 UTC, khaosdoctor requested changes
Please do **not** add or remove any words or phrases from the docs, since it'd create a different documentation for each language. To localize and apply region-like expressions is ok, however, completely change phrases, add new paragraphs or remove others is something we can't do, since we'd create a hard fork of the original docs.

Also, please do not change, add or remove examples from the docs. Let's try to keep it as much closer to the original English docs as possible :)

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +Os objetos `arguments` são uma estrutura especial disponível dentro de todas as chamadas de função e que é representada como uma lista de argumentos que são passadas quando a função é chamada. Desde
```suggestion
O objeto `arguments` é uma estrutura especial disponível dentro de todas as chamadas de função e que é representada como uma lista de argumentos que são passados quando a função é chamada. Uma vez que o JavaScript permite chamar funções com número indeterminado de argumentos, nós precisamos de um método para descobrir e acessar esses argumentos.
```

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +Os objetos `arguments` são um tipo de objeto array, seu tamanho corresponde a quantidade de argumentos passados para a função e que é possível acessar seu valor através de indexação do Array. Exemplo
```suggestion
O objeto `arguments` é um array-like, seu tamanho corresponde a quantidade de argumentos passados para a função. É possível acessar estes valores através da indexação do Array. Exemplo: `arguments[0]` captura o primeiro argumento. A única outra propriedade de `arguments` é chamada `callee`, a qual o ES5 impede o uso no `strict mode`, mais informações podem ser encontradas [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee). 

Veja mais exemplos sobre as propriedades de `arguments`.
```

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +const minhaFunc = function(primeiro) {
This code is different from the one in the docs

```
const myfunc = function(one) {
  arguments[0] === one;
  arguments[1] === 2;
  arguments.length === 3;
}

myfunc(1, 2, 3);
```

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +```js
This example doesn't exist in the document

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +```
In between those two examples, there is another paragraph which is missing:

*"This construct is very useful and gives javascript functions a lot of flexibility. But there is an important gotcha. The arguments object behaves like an array, but it is not an actual array. It does not have Array in its prototype chain and it does not respond to any array methods, e.g. arguments.sort() raises a TypeError. Instead, you need to copy the values into a true array first. With the advent of ES6 Array.from() method this is quite straightforward."*

Please add it so the docs are complete :)

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +```js
This example does not exist in the docs

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +Em alguns casos você ainda pode tratar o `arguments` como um Array, neste caso você pode usar o `arguments` através de funções dinâmicas. Os métodos nativos do Array (Ex. Array.prototype.concat) serã
```suggestion
Em alguns casos você ainda pode tratar o `arguments` como um Array, você pode usar o `arguments` através de invocações de funções dinâmicas. E a maioria dos métodos nativos do Array (Ex. Array.prototype.concat) aceitarão `arguments` quando invocados dinamicamente utilizando `call` ou `apply`. Essa técnica também oferece outros modos de conversão dos `arguments` para um tipo Array utilizando do método `Array.slice`.
```

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +```js
This whole example is different from the one in the docs:

```js
myfunc.apply(obj, arguments).

// concat arguments onto the 
Array.prototype.concat.apply([1,2,3], arguments);

// turn arguments into a true array
const args = Array.prototype.slice.call(arguments);

// cut out first argument
args = Array.prototype.slice.call(arguments, 1);
```

2019-07-05 14:25 UTC, khaosdoctor commented on locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
> +O `arrow functions` foram adicionados no ECMAScript 2015 (ES6), propondo uma sintaxe mais compacta do que em sua versão anterior. Com isso, houve um modo alternativo para tratar os `arguments` o conv
```suggestion
As `arrow functions` foram adicionadas na especificação do ECMAScript 2015 (ES6), propondo uma alternativa mais compacta do que a declaração de uma função comum. A desvantagem dessa alternativa é que não existe mais o objecto `arguments` (e também as keywords `this`, `super` ou `new.target`). A solução para esses casos é o uso dos parâmetros `rest`. Os parâmetros `rest` permitem representar um número indeterminado de argumentos como um Array. Leia mais detalhes [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters).
```

2019-07-05 15:24 UTC, fernandoors commented
> Please do **not** add or remove any words or phrases from the docs, since it'd create a different documentation for each language. To localize and apply region-like expressions is ok, however, completely change phrases, add new paragraphs or remove others is something we can't do, since we'd create a hard fork of the original docs.
> 
> Also, please do not change, add or remove examples from the docs. Let's try to keep it as much closer to the original English docs as possible :)

Hi @khaosdoctor thanks for any suggestions. I'll applying your recommendations in the next commit.

2019-08-14 18:52 UTC, khaosdoctor approved these changes
LGTM 👍

2019-08-14 18:54 UTC, khaosdoctor commented
I think this one is good to go @MaledongGit

2019-08-18 02:35 UTC, merged