Ru: translation debugging-getting-started.md
nodejs/nodejs.org pull request #2323
Opened 2019-07-08 17:41 UTC by stasonuke

Translation of the guide about debugging in node.js to Russian.
Перевод руководства об отладке в node.js

2019-07-09 06:32 UTC, alexandrtovmach requested changes
Похоже на машинный перевод. Нужно исправить места, где слова начинаются с большой буквы в неположенных местах (_Сигнал `SIGUSR1` (`SIGUSR1` Не доступен в Windows) В Node.js 7 и_) и убрать лишние обращения "вы", "ваше", которые не нужны в русском языке (_Это руководство призвано помочь вам в отладке вашего_)

Я начал проверять, но ошибок слишком много и они однотипные, поэтому доработайте немного, пожалуйста, потом я просмотрю весь текст.

2019-07-09 06:32 UTC, alexandrtovmach commented on locale/ru/docs/guides/debugging-getting-started.md
> +Это руководство призвано помочь вам в отладке вашего Node.js Приложения или скрипта.
`Это руководство призвано помочь вам в отладке вашего Node.js Приложения или скрипта.`

`Это руководство призвано помочь в отладке вашего Node.js приложения или скрипта.`

2019-07-09 06:32 UTC, alexandrtovmach commented on locale/ru/docs/guides/debugging-getting-started.md
> +При запуске с параметром `--inspect`,  Node.js Начинает прослушку
`При запуске с параметром `--inspect`,  Node.js Начинает прослушку`

`При запуске с параметром `--inspect`,  Node.js начинает слушать` ... клиент отладки

2019-07-09 06:32 UTC, alexandrtovmach commented on locale/ru/docs/guides/debugging-getting-started.md
> +В клиенте инспектора вы должны знать и указывать адрес хоста, порт и UUID для соединения.
`В клиенте инспектора вы должны знать и указывать адрес хоста, порт и UUID для соединения.`

`Для соединения клиента инспектора нужно знать адрес хоста, порт и UUID.`

2019-08-22 23:11 UTC, MylesBorins commented
there is now a conflict... should this be closed?

2019-09-03 02:19 UTC, MaledongGit commented
@stasonuke, Can I close this for you because someone has translated? If anything urgent, you can re-open it.

2019-09-03 02:19 UTC, closed without merging