Translated file : abi-stability.md
nodejs/nodejs.org pull request #2330
Opened 2019-07-12 14:08 UTC by celyes

Translated file: `abi-stability.md` found in `ar/docs/guides/abi-stability.md`

@Aissaoui-Ahmed 
@Maledong 
@Softvenue

2019-07-12 15:03 UTC, Aissaoui-Ahmed requested changes

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +# ثبات الواجهة الثنائية للتطبيق
ثبات  > إسقرار

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +## ثبات الواجهة البرمجية للتطبيقات في الـ Node.js
هنا أيضا

الترويس

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +فهي تعتبر النسخة المفسرة لواجهة برمجة تطبيق الخاصة برنامج ما. بعبارة أخرى، هي ترويسات الملفات التي تصف الكلاسات و الدوال
فهي تعتبر النسخة المفسرة لواجهة برمجة تطبيق (API) الخاصة برنامج ما. بعبارة أخرى، هي رؤوس الملفات التي تصف مصنفات و الدوال

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +يجب على التطبيق الذي يستعمل الواجهة الثنائية للتطبيق أن يُفسر بطريقة تجعل العناوين و الإعدادات المتوقعة و أحجام هياكل الذاكرة و الأنساق متوافقة مع
التنسيقات > الأنساق

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +تلك التي تم بواسطتها تفسير مزود الواجهة الثنئاية للتطبيق، ويتم تحقيق هذا عادة عبر التفسير باستخدام الترويس التي تم توفيرها من طرف مزود الواجهة الثنائية للتطبيق.
الترويس  > الرؤوس

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +الواجهة الثنائية للتطبيق انطلاقا من ملف ترويسة ذو محتوى محدد، كما يجب عليها ان تنتج شيفرة خاصة بالتطبيق باستعمال الواجهة الثنائية للتطبيق التي يمكنها الوصول إلى الواجهة البرمجية
ترويسة > الرأس

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +للتطبيق و التي تم وصفها في ترويسة معطاة استنادا إلى الناتج المتفق عليه للواجهة الثنائية للتطبيق الناتجة عن الوصف المتوفر في الترويسة. إن المفسرات الحديثة تمتلك سجل تتبع جيداُ فيما يخص
هنا أيضا

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +بما أن مزود الواجهة الثنائية للتطبيق و مستخدم الواجهة الثنائية للتطبيق قد يتم تفسيرهما في أوقات مختلفة باستعمال نسخ مفسرات مختلفة، فإن القطعة المسؤولة عن
فإن القطعة المسؤولة عن > قإن جزء من المسؤولية 

**remove** عن

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +توفر الـ Node.js ملفات ترويس يتم صيانتها من طرف عدة فرق تقنية مستقلة. على سبيل المثال، ملفات الترويس مثل `node.h` و `node_buffer.h` يتم صيانتها من طرف فريق الـ Node.js، بينما يتم صيانة ملف `v8.h` من
اجندة > اجندته

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +## ثبات الواجهة البرمجية للتطبيقات في الـ Node.js
ثبات  > إستقرار

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +لهذه الأطراف، تم طرح الـ N-API في النسخة 8.6.0 و تم تمييزه كميزة مستقرة في النسخة 8.12.0. هذه الواجهة البرمجية معرفة في ملفات الترويس [`node_api.h`][] و [`node_api_types.h`][] و تضمن توافقا متقدما عل
الترويس

2019-07-12 15:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +ينطوي الـ N-API على نسخ عدة لكون أن هناك واجهات برمجية جديدة تضاف من وقت ﻵخر، وعكس الترميز الدلالي، فإن تنسيخ الـ N-API هو تراكمي، أي أن كل نسخة منه تمثل نفس المعنى للنسخ الثانوية في نظام الترميز الد
وعكس الإصدار الدلالي > وعكس الترميز الدلالي

ان تحتوي على تغييرات  > ان تنطوي على تغييرات

2019-07-13 18:57 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +## ثبات الواجهة البرمجية للتطبيقات في الـ Node.js
الترويس is the correct word.

2019-07-13 18:58 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +# ثبات الواجهة الثنائية للتطبيق
the two terms convey the exact same meaning @Aissaoui-Ahmed

2019-07-13 19:11 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +للتطبيق و التي تم وصفها في ترويسة معطاة استنادا إلى الناتج المتفق عليه للواجهة الثنائية للتطبيق الناتجة عن الوصف المتوفر في الترويسة. إن المفسرات الحديثة تمتلك سجل تتبع جيداُ فيما يخص
ترويس is the correct word for "header" since the word "رأس" means in English "head"

2019-07-13 19:11 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +توفر الـ Node.js ملفات ترويس يتم صيانتها من طرف عدة فرق تقنية مستقلة. على سبيل المثال، ملفات الترويس مثل `node.h` و `node_buffer.h` يتم صيانتها من طرف فريق الـ Node.js، بينما يتم صيانة ملف `v8.h` من
no error here

2019-07-13 19:11 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +## ثبات الواجهة البرمجية للتطبيقات في الـ Node.js
the two words convey the exact same meaning

2019-07-13 19:11 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +لهذه الأطراف، تم طرح الـ N-API في النسخة 8.6.0 و تم تمييزه كميزة مستقرة في النسخة 8.12.0. هذه الواجهة البرمجية معرفة في ملفات الترويس [`node_api.h`][] و [`node_api_types.h`][] و تضمن توافقا متقدما عل
see upper conversation

2019-07-13 19:13 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +ينطوي الـ N-API على نسخ عدة لكون أن هناك واجهات برمجية جديدة تضاف من وقت ﻵخر، وعكس الترميز الدلالي، فإن تنسيخ الـ N-API هو تراكمي، أي أن كل نسخة منه تمثل نفس المعنى للنسخ الثانوية في نظام الترميز الد
first mistake corrected
second is definitely not a mistake

2019-07-13 19:13 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +بما أن مزود الواجهة الثنائية للتطبيق و مستخدم الواجهة الثنائية للتطبيق قد يتم تفسيرهما في أوقات مختلفة باستعمال نسخ مفسرات مختلفة، فإن القطعة المسؤولة عن
it's totally correct in the context of the paragraph.

2019-07-13 19:14 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +تلك التي تم بواسطتها تفسير مزود الواجهة الثنئاية للتطبيق، ويتم تحقيق هذا عادة عبر التفسير باستخدام الترويس التي تم توفيرها من طرف مزود الواجهة الثنائية للتطبيق.
head = رأس
header = ترويس

2019-07-13 19:14 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +يجب على التطبيق الذي يستعمل الواجهة الثنائية للتطبيق أن يُفسر بطريقة تجعل العناوين و الإعدادات المتوقعة و أحجام هياكل الذاكرة و الأنساق متوافقة مع
error corrected

2019-07-13 19:14 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +فهي تعتبر النسخة المفسرة لواجهة برمجة تطبيق الخاصة برنامج ما. بعبارة أخرى، هي ترويسات الملفات التي تصف الكلاسات و الدوال
mistake corrected

2019-07-14 09:03 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +## ثبات الواجهة البرمجية للتطبيقات في الـ Node.js
نعم صحيح لكن تجنب البس والإختلاف على الكلمة الترويس فقد يظن البعض على انها الترويس في الخط العربي أو الترويس من الثقافة الروسية.

2019-07-14 09:36 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +بما أن مزود الواجهة الثنائية للتطبيق و مستخدم الواجهة الثنائية للتطبيق قد يتم تفسيرهما في أوقات مختلفة باستعمال نسخ مفسرات مختلفة، فإن القطعة المسؤولة عن
عندما نقول قطعة في سياق الكلام قد يظن البعض أنه شئ مادي

2019-07-14 09:38 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +توفر الـ Node.js ملفات ترويس يتم صيانتها من طرف عدة فرق تقنية مستقلة. على سبيل المثال، ملفات الترويس مثل `node.h` و `node_buffer.h` يتم صيانتها من طرف فريق الـ Node.js، بينما يتم صيانة ملف `v8.h` من
لا داعي الإضافة الهاء فقد سبقتها كلمة يمتلك

2019-07-14 10:22 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +بما أن مزود الواجهة الثنائية للتطبيق و مستخدم الواجهة الثنائية للتطبيق قد يتم تفسيرهما في أوقات مختلفة باستعمال نسخ مفسرات مختلفة، فإن القطعة المسؤولة عن
بالفعل شيء مادي

2019-07-14 10:22 UTC, celyes commented on locale/ar/docs/guides/abi-stability.md
> +توفر الـ Node.js ملفات ترويس يتم صيانتها من طرف عدة فرق تقنية مستقلة. على سبيل المثال، ملفات الترويس مثل `node.h` و `node_buffer.h` يتم صيانتها من طرف فريق الـ Node.js، بينما يتم صيانة ملف `v8.h` من
عدم اضافتها يستوجب اضافة جملة جديدة...
اضافة حرف خير من اضافة جملة

2019-07-14 10:29 UTC, Aissaoui-Ahmed commented on locale/ar/docs/guides/abi-stability.md
> +بما أن مزود الواجهة الثنائية للتطبيق و مستخدم الواجهة الثنائية للتطبيق قد يتم تفسيرهما في أوقات مختلفة باستعمال نسخ مفسرات مختلفة، فإن القطعة المسؤولة عن
ABI ?

2019-07-17 21:50 UTC, Aissaoui-Ahmed approved these changes

2019-07-20 16:15 UTC, celyes commented
@MaledongGit

2019-07-23 00:29 UTC, merged