fix: make Hamburg a separate state
nodejs/nodejs.org pull request #2334
Opened 2019-07-13 13:55 UTC by LEQADA

Hamburg is now a separate state and not a part of Bavaria :slightly_smiling_face:

2019-07-14 02:55 UTC, ghost approved these changes

2019-07-16 08:22 UTC, LEQADA commented
@MaledongGit thank you for review. Should we merge it now?

2019-07-16 09:52 UTC, aymen94 approved these changes

2019-07-16 14:50 UTC, Aissaoui-Ahmed approved these changes

2019-07-16 15:02 UTC, lojzatran approved these changes

2019-07-16 15:03 UTC, heshamMassoud commented on locale/en/get-involved/node-meetups.md
> +#### Hamburg
```suggestion
#### Hamburg 🍔
```

2019-07-16 15:04 UTC, lojzatran commented on locale/en/get-involved/node-meetups.md
> +#### Hamburg
Why do you think so?

2019-07-16 15:05 UTC, heshamMassoud commented on locale/en/get-involved/node-meetups.md
> +#### Hamburg
I think why not? is the question..

2019-07-16 15:06 UTC, lojzatran commented on locale/en/get-involved/node-meetups.md
> +#### Hamburg
Hm I've never thought that way...

2019-07-16 15:16 UTC, heshamMassoud requested changes
👍

2019-07-16 15:17 UTC, heshamMassoud approved these changes

2019-07-16 15:19 UTC, JudeNiroshan approved these changes
good job @LEQADA !

2019-07-19 02:29 UTC, merged