RU: blocking vs non-blocking guide
nodejs/nodejs.org pull request #2337
Opened 2019-07-14 08:18 UTC by unstoo

Human translation.

2019-07-15 19:24 UTC, alexandrtovmach requested changes
_JavaScript код_ — для удобочитаемости оба слова можно использовать по отдельности и/или заменять JavaScript на JS. Так текст будет лишен нагрузки тавтологиями.

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +О **блокировании** говорят, когда выполнение оставшегося JavaScript кода в Node.js
"оставшегося" - можно убрать, смысл не меняется.

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +какого-нибудь файла). Так происходит, потому что цикл событий не может продолжить исполнение оставшегося JavaScript
"оставшегося JavaScript" - можно убрать, потому что смысл не меняется и, чтобы избегать лишних повторений

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +В Node.js медленный код JavaScript не принято называть **блокирующим**,
В Node.js медленно исполняемый JavaScript не принято называть **блокирующим**,

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +JavaScript кода может продолжаться, не дожидаясь окончания его работы. Как следствие
"кода" - можно опустить как само собой разумеющееся

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +инженерное решение, которое обеспечивает высокую пропускную способность Node.js.
Отсутствие необходимости дожидаться окончания чтения файла и других системных вызовов — ключевое инженерное решение, которое обеспечивает высокую пропускную способность Node.js.

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +## Опасность Смешивания Блокирующего и Неблокирующего Кода
Странно что в оригинале "Mixing" с большой буквы, я думаю что это ошибка. Предлагаю не перепечатывать в русскую версию, но это спорно.

2019-07-15 19:24 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +Существует паттерны, которые следует избегать при работе с I/O. Взглянем на пример:
1. "Существуют"
2. "которых"

2019-07-27 13:08 UTC, unstoo commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +## Опасность Смешивания Блокирующего и Неблокирующего Кода
Поддерживаю.

2019-07-27 13:12 UTC, unstoo commented
Please approve.

2019-08-03 19:41 UTC, unstoo commented
Is it good to go?

2019-08-03 20:01 UTC, alexandrtovmach commented
Sorry for delay, will check tomorrow

2019-08-05 11:06 UTC, alexandrtovmach approved these changes

2019-08-05 11:08 UTC, alexandrtovmach approved these changes

2019-08-05 11:08 UTC, alexandrtovmach commented on locale/ru/docs/guides/blocking-vs-non-blocking.md
> +Существуют паттерны, которые следует избегать при работе с I/O. Взглянем на пример:
'которых'

2019-08-06 11:12 UTC, merged