AR : Fix missing part & some translate in site.json
nodejs/nodejs.org pull request #2338
Opened 2019-07-14 12:57 UTC by 3imed-jaberi

Some details :
1. I've added a part that is in the English version and is missing here ; 
```
    "dependencies": {
      "link": "docs/meta/topics/dependencies",
      "text": "Dependencies"
    }
```
2. Fix translation of meetups ; from `لقاءات` to `مُلْتَقَيات` .. 
3. Fix translation of docs ; from `التوثيق` to `المستندات` ..

2019-07-14 13:12 UTC, 3imed-jaberi commented
Hi @Aissaoui-Ahmed , 
Please check these changes and thank you ❤️ ..
If you can give me your email address ✌️

2019-07-14 20:24 UTC, Aissaoui-Ahmed commented
I appreciate your interest I've left a comment on [React ](https://github.com/reactjs/ar.reactjs.org/issues/122#issuecomment-511190921) about words
in the file site.json don't update it before complete translation 
you can contact me on [Facebook](https://www.facebook.com/a.aissaoui)

2019-07-14 22:51 UTC, 3imed-jaberi commented
I'm sorry my bro ( @Aissaoui-Ahmed ) ..
At REACT we have the methodology of work and the glossary that we build ..
For example, when the difference in the translation of a word we must discuss ..
I've read your comments there and fixed the TAB bug ..

2019-07-16 14:47 UTC, Aissaoui-Ahmed requested changes

2019-07-16 14:47 UTC, Aissaoui-Ahmed commented on locale/ar/site.json
> +    "text": "المستندات",
المستندات = documents
التوثيق = documentation

2019-07-16 23:45 UTC, 3imed-jaberi commented on locale/ar/site.json
> +    "text": "المستندات",
وثائق = documents ... !

2019-07-17 02:09 UTC, 3imed-jaberi commented on locale/ar/site.json
> +    "text": "المستندات",
الوثائق  = documents ... !

2019-07-17 15:10 UTC, Aissaoui-Ahmed approved these changes

2019-07-19 02:27 UTC, merged