AR : Upadte about/releases.md AR #2345
nodejs/nodejs.org pull request #2346
Opened 2019-07-20 21:57 UTC by Aissaoui-Ahmed

Hi ! 
Upadte about/releases.md 

/cc @3imed-jaberi
@SoftVenue

2019-07-21 10:49 UTC, celyes requested changes
ل => للـ
مؤلفي  => لمؤلفي
المكتبة => المكتبات
إضافة دعم لهم => لدعمهم
احذف الجملة التالية : 

>  الإصدارات odd-numbered (الأعداد الفردية الصحيحة و غير مضاعفة ل 2 مثل 9، 11، إلخ) تصبح غير مدعومة و بعد ستة أشهر،

الإصدارات الأعداد الفردية (مثل 9، 11، إلخ)  =>  الاصدارات المرقمة فردياً
و الإصدارات الأعداد الزوجية (10، 12، إلخ) => أما الاصدارات المرقمة زوجياً،
ترحل إلى حالة LTS ناشطة وهي جاهزة للاستخدام العام 
=> 
 تصبح اصدارات نشيطة ذات دعم طويل الأمد و تكون في هذه الحالة جاهزة للاستخدام العام (LTS).
حالة الإصدار LTS هو "دعم طويل الأمد" التي تتضمن الأخطاء الخطيرة ستصلح في مدة قدرها 30 شهرا. 
=>
يعتبر الاصدار ذو دعم طويل الامد (LTS) إصداراً يتم فيه إصلاح الأخطاء الخطيرة لمدة قدرها 30 شهرا 

LTS الصيانة  => LTS قيد الصيانة

2019-07-21 13:53 UTC, 3imed-jaberi commented
> ل => للـ
> مؤلفي => لمؤلفي
> المكتبة => المكتبات
> إضافة دعم لهم => لدعمهم
> احذف الجملة التالية :
> 
> > الإصدارات odd-numbered (الأعداد الفردية الصحيحة و غير مضاعفة ل 2 مثل 9، 11، إلخ) تصبح غير مدعومة و بعد ستة أشهر،
> 
> الإصدارات الأعداد الفردية (مثل 9، 11، إلخ) => الاصدارات المرقمة فردياً
> و الإصدارات الأعداد الزوجية (10، 12، إلخ) => أما الاصدارات المرقمة زوجياً،
> ترحل إلى حالة LTS ناشطة وهي جاهزة للاستخدام العام
> =>
> تصبح اصدارات نشيطة ذات دعم طويل الأمد و تكون في هذه الحالة جاهزة للاستخدام العام (LTS).
> حالة الإصدار LTS هو "دعم طويل الأمد" التي تتضمن الأخطاء الخطيرة ستصلح في مدة قدرها 30 شهرا.
> =>
> يعتبر الاصدار ذو دعم طويل الامد (LTS) إصداراً يتم فيه إصلاح الأخطاء الخطيرة لمدة قدرها 30 شهرا
> 
> LTS الصيانة => LTS قيد الصيانة

ألا تعتقدون انه يجب ترجمة ; 
LTS ==> النسخة المستقرة / النسخة المدعومة على المدى البعيد

2019-07-21 14:29 UTC, Aissaoui-Ahmed commented
<div dir="rtl">
@3imed-jaberi  اتعامل مع "LTS" على أنها إختصار وعدم حصرها في كلمة واحدة ،يوجد توضيح في نهاية الجملة على انها  "دعم طويل الأمد" وإذا كان هناك إجماع على أنها النسخة المستقرة فسأغيرها ❤✔
</div>

2019-07-22 01:22 UTC, 3imed-jaberi approved these changes

2019-07-22 01:23 UTC, 3imed-jaberi approved these changes

2019-07-27 08:19 UTC, ouadie-lahdioui approved these changes
LGTM 👍

2019-08-01 23:00 UTC, 3imed-jaberi commented
please @celyes  , update your review 👻 ...

2019-08-07 18:42 UTC, celyes commented
> 
> @3imed-jaberi اتعامل مع "LTS" على أنها إختصار وعدم حصرها في كلمة واحدة ،يوجد توضيح في نهاية الجملة على انها "دعم طويل الأمد" وإذا كان هناك إجماع على أنها النسخة المستقرة فسأغيرها ❤✔

كلا المصطلحين صحيحان لغويا، لذلك يمكن الابقاء على احدهما.

2019-08-07 18:42 UTC, celyes approved these changes
LGTM 💯

2019-08-07 19:24 UTC, merged