AR : Fix the style / structure of download section ..
nodejs/nodejs.org pull request #2349
Opened 2019-07-22 00:54 UTC by 3imed-jaberi

My try to make the files in the download section similar in structure to the original file ..

2019-07-22 04:07 UTC, MaledongGit commented
@nodejs/nodejs-ar , Please have a review.

2019-07-22 08:28 UTC, ram-you commented
This sounds good.

2019-07-22 12:38 UTC, Aissaoui-Ahmed commented on locale/ar/download/current.md
> +        يقوم أعضاء من مجتمع النود جي اس بالاشراف على نسخ غير رسمية من النود جي اس لمنصات أخرى. يجب التذكير أن هذه النسخ غير مدعومة من الفريق الأساسي للنود جي اس و قد لا تكون على نفس مستوى التطوير الخ
النود جي اس > Node.js

2019-07-22 13:05 UTC, 3imed-jaberi commented on locale/ar/download/current.md
> +        يقوم أعضاء من مجتمع النود جي اس بالاشراف على نسخ غير رسمية من النود جي اس لمنصات أخرى. يجب التذكير أن هذه النسخ غير مدعومة من الفريق الأساسي للنود جي اس و قد لا تكون على نفس مستوى التطوير الخ
هذه ليست ترجمتي لكن لاباس .. ان فقط قمت بتعديل المثل من ناحية التنسيق ليكون مماثل للملف الأصلي ..

2019-07-22 16:22 UTC, Aissaoui-Ahmed requested changes

2019-07-22 16:22 UTC, Aissaoui-Ahmed commented on locale/ar/download/releases.md
>  modules: "يشير <code>NODE_MODULE_VERSION</code> إلى رقم نسخة النود جي اس الخاص بالواجهة الثنائية (ABI) للتطبيق، وهو يستعمل لتحديد أي من نسخ النود جي اس المنتجة كملفات ثنائية خاصة بالسي ++ يمكنها ان ت
هنا أيضا

2019-07-22 16:22 UTC, Aissaoui-Ahmed commented on locale/ar/download/index.md
> +        يقوم أعضاء من مجتمع النود جي اس بالاشراف على نسخ غير رسمية من النود جي اس لمنصات أخرى. يجب التذكير أن هذه النسخ غير مدعومة من الفريق الأساسي للنود جي اس و قد لا تكون على نفس مستوى التطوير الخ
هنا أيضا

2019-07-22 16:24 UTC, Aissaoui-Ahmed commented
thank you for your contribution @3imed-jaberi

2019-07-22 17:27 UTC, celyes requested changes
looks perfect, except whenever there is the word 'Node.js', leave it as it is in the English writing... this is how the guide recommends as well as what is found across all other translations.

2019-07-23 10:43 UTC, Aissaoui-Ahmed approved these changes

2019-07-23 10:45 UTC, Aissaoui-Ahmed commented
LGTM :100:

2019-07-28 11:21 UTC, 3imed-jaberi commented
Hey @celyes  , please check this  ..

2019-08-01 22:20 UTC, celyes approved these changes
Absolutely beautiful !

2019-08-01 22:55 UTC, merged