AR : Fix structure of get-involved section and ignore tatbi3 ..
nodejs/nodejs.org pull request #2350
Opened 2019-07-22 23:31 UTC by 3imed-jaberi

2019-07-23 00:28 UTC, MaledongGit commented
@nodejs/nodejs-ar, Please have a review.

2019-07-23 10:39 UTC, Aissaoui-Ahmed requested changes

2019-07-23 10:39 UTC, Aissaoui-Ahmed commented on locale/ar/get-involved/index.md
> -- [مجموعة الفيسبوك الإسرائيلية للـ Node.js](https://www.facebook.com/groups/node.il/)
مجموعة الفيسبوك في الكيان الصهيوني للـ Node.js

2019-07-23 10:39 UTC, Aissaoui-Ahmed commented on locale/ar/get-involved/node-meetups.md
> -### إسرائيل
الكيان الصهيوني

2019-07-28 23:54 UTC, 3imed-jaberi commented
@ram-you , @ouadie-lahdioui please check this ...

2019-07-29 01:10 UTC, Aissaoui-Ahmed approved these changes

2019-07-29 05:39 UTC, merged