Translation of How-To-Parse-Command-Line-Argumentsmd To PT-BR
nodejs/nodejs.org pull request #2536
Opened 2019-09-07 21:38 UTC by SauloNunes

@nodejs/nodejs-pt

2019-09-08 05:39 UTC, MaledongGit commented
@nodejs/nodejs-pt：Please have a reivew, thanks!

2019-09-08 18:29 UTC, khaosdoctor requested changes
Some typos and translation tips

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-parse-command-line-arguments.md
> +Enquanto diariamente a CLI está concentrada nos argumentos, você provavelmente vai querer pular os dois primeiros. Agora tente isso em `argv.js`:
```suggestion
No que diz respeito a uso de argumentos no dia-a-dia, você provavelmente vai querer pular os dois primeiros. Agora tente isso em `argv.js`:
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-parse-command-line-arguments.md
> +- **command()**: Este método é usado para adicionar comandos, a descrição e as opções são específicas somente para esse comando, como no seguinte código `lyr` que é um comando e `-y` é uma opção espe
```suggestion
- **command()**: Este método é usado para adicionar comandos, a descrição e as opções são específicas somente para esse comando, como no código anterior, `lyr`, que é um comando, e `-y` é uma opção específica de lyr: `node myapp.js lyr -y 2016`
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +Então você possui uma pequena ferramenta CLI, mas deseja habilitar uma opção onde o usuário possa inserir dados adicionais após o start do mesmo ao invés de passar esses dados como argumento de linha
```suggestion
Então você possui uma pequena ferramenta CLI, mas deseja habilitar uma opção onde o usuário possa inserir dados adicionais após o start do mesmo ao invés de passar esses dados como argumento de linha de comando ou inserindo dentro do arquivo. Para fazer isso, será necessário escutar ao STDIN ("standard input", ex: seu teclado), no qual o Node.js exporta para você como `process.stdin`, uma stream de leitura.
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +Stream é uma forma do Node.js lidar com tipos de E/S - é um tópico importante, e você pode ler mais sobre isso [aqui](https://nodejs.org/api/stream.html). No momento, nós vamos usar o módulo `readlin
```suggestion
Streams são a forma do Node.js lidar com tipos de E/S - é um tópico importante, e você pode ler mais sobre isso [aqui](https://nodejs.org/api/stream.html). No momento, nós vamos usar o módulo `readline` do Node.js que é um wrapper envolvendo o padrão de E/S, adequado para receber a entrada do usuário a partir da linha de comando (terminal).
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +Promt foi criado para ser fácil - se seus olhos começaram a brilhar assim que você leu `Readable Stream`,então essa é uma seção para você. Compare os seguintes exemplos abaixo:
```suggestion
O prompt foi criado para ser fácil - se seus olhos começaram a brilhar assim que você leu `Readable Stream`,então essa é uma seção para você. Compare os seguintes exemplos abaixo:
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +Se tudo isso parece um pouco complicado, ou se você deseja uma interface de nível superior, não se preocupe - como sempre, a comunidade Node.js veio ao resgate. Existe um módulo amigável para isto, o
```suggestion
Se tudo isso parece um pouco complicado, ou se você deseja uma interface de alto nível, não se preocupe - como sempre, a comunidade Node.js veio ao resgate. Existe um módulo amigável para isto, o `prompt` disponível no `npm`:
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +DICA PRO NODE: Esse pequeno script também demonstra o tratamento adequado de erros em node - erros são o primeiro argumento de uma callback, e `return` é utilizado com o controlador de erros de tal f
```suggestion
DICA PRO NODE: Esse pequeno script também demonstra o tratamento adequado de erros em node - erros são o primeiro argumento de um callback, e `return` é utilizado com o controlador de erros de tal forma que o restante da função não seja executado quando um erro ocorrer.
```

2019-09-08 18:29 UTC, khaosdoctor commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +Prompt também torna trivial lidar com um determinado conjunto de propriedades recorrentes que você pode querer anexar.
```suggestion
Usar o prompt também torna trivial lidar com um determinado conjunto de propriedades recorrentes que você pode querer anexar.
```

2019-09-08 18:40 UTC, SauloNunes commented
thanks @khaosdoctor your tips are welcome!!!

2019-09-09 12:39 UTC, JCMais commented on locale/pt-br/knowledge/command-line/how-to-prompt-for-command-line-input.md
> +O prompt foi criado para ser fácil - se seus olhos começaram a brilhar assim que você leu `Readable Stream`,então essa é uma seção para você. Compare os seguintes exemplos abaixo:
```suggestion
O prompt foi criado para ser fácil - se seus olhos começaram a brilhar assim que você leu `Readable Stream`, então essa é uma seção para você. Compare os seguintes exemplos abaixo:
```

Missing space after comma

2019-09-09 16:49 UTC, khaosdoctor approved these changes
LGTM @MaledongGit

2019-09-17 01:06 UTC, merged