Removed English comments from translations
nodejs/nodejs.org pull request #2591
Opened 2019-09-19 16:11 UTC by grodd

fixes #2510

2019-09-19 16:56 UTC, XhmikosR commented
Without having another solution for translators, this shouldn't land.

Also, note there are test failures (extra blank lines).

2019-09-19 16:57 UTC, XhmikosR commented on locale/ja/docs/guides/buffer-constructor-deprecation.md
> +- [Variant 1: Node.js ≤ 4.4.x および 5.0.0 — 5.9.x のサポートを終了](#variant-1) (*推奨*)
This kind of changes shouldn't be in this patch.

2019-09-20 01:04 UTC, MaledongGit commented
@grodd, thanks for your contribution!

However, there must be something wrong with your submit, so you should run `npm run test` locally before your submittion.

2019-09-20 01:07 UTC, ghost requested changes
Hello,

First I'd say welcome your contributions!

Before your submition, please have a review first and run `npm run test`.

Then please DO NOT remove the comment in Korean and Japanese, because their authors want to keep them as a history track which they can compare and do translations, it's their habits (Waiting for their response).

If you have any other changes, please repush them and we'll have a review of them.

2019-10-09 09:49 UTC, XhmikosR commented
This has become outdated already.

I lean towards closing this until we have a proper solution to track translations.

2019-10-12 02:50 UTC, closed without merging