zh-TW: Translate docs index
nodejs/nodejs.org pull request #2593
Opened 2019-09-20 07:45 UTC by osk2

Translate `zh-tw/docs/index.md`

2019-09-20 08:23 UTC, MaledongGit commented
@nodejs/nodejs-tw, please have a review, thanks!

2019-09-21 14:15 UTC, PeterDaveHello requested changes

2019-09-21 14:15 UTC, PeterDaveHello commented on locale/zh-tw/docs/index.md
> +### 教學
Wrong hierachy

2019-09-21 14:15 UTC, PeterDaveHello commented on locale/zh-tw/docs/index.md
> +### ES6 功能
Wrong hierachy

2019-09-21 14:15 UTC, PeterDaveHello commented on locale/zh-tw/docs/index.md
> +### 在找舊版本的 API 文件嗎？
Suggestion:
```diff
---  ### 在找舊版本的 API 文件嗎？
+++  ### 在找舊版的 API 文件嗎？
```

2019-09-21 14:15 UTC, PeterDaveHello commented on locale/zh-tw/docs/index.md
> +* 教學
This seems to be another word?

2019-09-23 01:29 UTC, osk2 commented on locale/zh-tw/docs/index.md
> +* 教學
How about "技術指南"?

2019-09-24 05:36 UTC, willin approved these changes
LGTM

2019-09-25 16:28 UTC, PeterDaveHello commented on locale/zh-tw/docs/index.md
> +* 教學
Looks great!

2019-09-25 16:29 UTC, PeterDaveHello approved these changes

2019-09-25 16:29 UTC, merged