Create the-process-module.md in portuguese language
nodejs/nodejs.org pull request #2637
Opened 2019-10-02 20:49 UTC by adrianoapj

2019-10-03 00:21 UTC, adrianoapj commented
@nodejs/nodejs-pt

2019-10-03 00:21 UTC, adrianoapj commented
@nodejs/nodejs-pt, review please

2019-10-03 18:40 UTC, khaosdoctor commented
Looking into it :)

2019-10-06 03:42 UTC, khaosdoctor requested changes
Minor changes e some untranslated text

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +Cada processo do Node.js tem uma série de funcionalidades embutidas, acessíveis através do módulo global `process`.  O módulo `process` não precisa ser requisitado - isso é, de certo modo, literalmen
```suggestion
Cada processo do Node.js tem uma série de funcionalidades embutidas, acessíveis através do módulo global `process`.  O módulo `process` não precisa ser importado - ele é, de certo modo, literalmente um wrapper em volta do processo sendo executado, e muitos dos métodos que ele possui, nada mais são do que wrappers em torno de chamadas de algumas das bibliotecas em C do núcleo do Node.
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +Códigos como o acima podem ser realmente úteis para salvar algum tipo de registro final antes de encerrar a execução.  Note o uso de uma chamada de um sistema de arquivos síncrono - isso é para garan
```suggestion
Códigos como o acima podem ser realmente úteis para salvar algum tipo de registro final antes de encerrar a execução.  Note o uso de uma chamada de um sistema de arquivos síncrono - isso é para garantir que a E/S de dados finalize antes do processo.
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +O outro evento embutido se chama `uncaughtException`.  Como você já deve imaginar, ele é acionado sempre que ocorreu algum erro que não foi devidamente tratado em seu programa.  Essa não é a forma id
```suggestion
O outro evento embutido se chama `uncaughtException`.  Como você já deve imaginar, ele é acionado sempre que algum erro que não foi devidamente tratado em seu programa ocorre.  Essa não é a forma ideal de processar erros, mas pode ser bem útil como última linha de defesa se um programa necessita rodar continuamente mesmo após o erro.
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +O objeto `process` também disponibiliza alguns wrappings para as três streams `STDIO`, que são `stdin`, `stdout`, and `stderr`.  De forma resumida, `stdin` é uma stream de entrada (que lê as informaç
```suggestion
O objeto `process` também disponibiliza alguns wrappings para as três streams `STDIO`, que são `stdin`, `stdout` e `stderr`.  De forma resumida, `stdin` é uma stream de entrada (que lê as informações inseridas pelo usuário), `stdout` é uma stream de saída não bloqueante (em outras palavras, é assíncrona), e `stderr` é uma stream de saída bloqueante (síncrona).
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +O `pid` é ID de processo do SO, `platform` é algo mais geral como 'linux' ou 'darwin', e `version` refere-se a sua versão do Node. `process.title` é um pouco mais diferente - enquanto definido como `
```suggestion
O `pid` é ID de processo do SO, `platform` é algo mais geral como 'linux' ou 'darwin', e `version` refere-se a sua versão do Node. `process.title` é um pouco diferente - enquanto definido como `node` por padrão, isto pode ser definido para o que você desejar, e será o que aparecerá na sua lista de processos em execução.
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +`process.execPath` will return the absolute path of the executable that started this process.
```suggestion
`process.execPath` vai retornar o caminho absoluto do executável que começou o processo em questão
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +`process.exit` encerra o processo.  Se você chamar uma função assíncrona e então chamar `process.exit()` imediatamente após, você está em uma situação imprevisível - a chamada assíncrona pode, ou não
```suggestion
`process.exit` encerra o processo.  Se você chamar uma função assíncrona e então chamar `process.exit()` imediatamente após, você está em uma situação imprevisível - a chamada assíncrona pode ou não ser finalizada antes do término do programa. `process.exit` aceita apenas um parâmetro adicional - um número inteiro como código de saída.  `0`, por convenção, é uma saída sem erros.
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +Finalmente, em uma nota mais avançada, nós temos o `process.nextTick`.  Este método aceita um argumento - um callback - e coloca isso no topo da próxima execução do loop do evento.  Algumas pessoas f
```suggestion
Finalmente, em uma nota mais avançada, nós temos o `process.nextTick`.  Este método aceita um argumento - um callback - e coloca isso no topo da próxima execução do event loop.  Algumas pessoas fazem algo parecido com isso:
```

2019-10-06 03:42 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-process-module.md
> +Assim é bem mais eficiente, e muito mais preciso.
```suggestion
Além de bem mais eficiente, é muito mais preciso.
```

2019-10-06 16:37 UTC, TiagoDanin approved these changes
:+1: LGTM

2019-10-07 19:59 UTC, khaosdoctor approved these changes
Perfect :)

2019-10-07 19:59 UTC, khaosdoctor commented
I think this one is ready to go @MaledongGit

2019-10-09 04:54 UTC, merged