[PT-BR] translate getting-started the-console-module
nodejs/nodejs.org pull request #2639
Opened 2019-10-04 01:21 UTC by JCMais

2019-10-04 01:21 UTC, JCMais commented
@nodejs/nodejs-pt review please

2019-10-06 03:33 UTC, khaosdoctor requested changes
Some minor changes

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +Qualquer pessoa familiar com o desenvolvimento voltado para navegadores provavelmente já usou `console.log` para fins de debug - Node.js implementou um objeto próprio `console` para imitar grande par
```suggestion
Qualquer pessoa familiar com o desenvolvimento voltado para navegadores provavelmente já usou `console.log` para fins de debug - O Node.js implementou um objeto `console` próprio para imitar grande parte desta experiência. Porém, como nós estamos trabalhado do lado do servidor, ela funciona como uma camada acima do `stdout`, `stdin` e `stderr` em vez do console de debug do navegador.
```

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +Por conta deste paralelo com o navegador, o módulo `console` se tornou a casa para grande parte da funcionalidade de "output" do Node. O mais simples é `console.log()`.
```suggestion
Por conta deste paralelo com o navegador, o módulo `console` se tornou a principal API para grande parte da funcionalidade de "output" do Node. O mais simples é o `console.log()`.
```

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +Uma pegadinha com a função `console.log`, e todas as funções que dependem nela, é que ela possui um "buffer" para a sua saída. Portanto se o processo é interrompido abruptamente, seja por meio de alg
```suggestion
Uma pegadinha com a função `console.log`, e todas as funções que dependem dela, é que ela possui um "buffer" para a sua saída. Portanto se o processo é interrompido abruptamente, seja por meio de algum erro ou através do `process.exit()`, é bem possível que o conteúdo no buffer nunca seja definitivamente enviado para a tela. Isso pode causar certa frustração, portanto fique atento para esta situação.
```

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +`console.error()` funciona do mesmo modo que `console.log`, exceto pelo fato que o conteúdo enviado para `stderr` em vez de `stdout`. Isso é na realidade uma diferença extremamente importante, pois o
```suggestion
`console.error()` funciona do mesmo modo que `console.log`, exceto pelo fato que o conteúdo enviado para `stderr` em vez de `stdout`. Isso é, na realidade, uma diferença extremamente importante, pois o conteúdo enviado para `stderr` é sempre escrito de forma síncrona. Qualquer uso de `console.error`, ou qualquer outra função no core do Node.js que escreva para `stderr`, irá bloquear o processo até que todo o conteúdo seja escrito. Isso é útil para mensagens de erro - você as recebe no momento que elas acontecem - porém se usado de forma indiscriminada, pode tornar o processo do Node.js bastante lento.
```

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +`console.dir()`, como mencionado acima, é um "alias" para `util.inspect()` - é uma função usada para enumerar as propriedades de um objeto.  [Leia mais](/pt-br/knowledge/getting-started/how-to-use-ut
```suggestion
`console.dir()`, como mencionado acima, é um "alias" para `util.inspect()` - é uma função usada para enumerar as propriedades de um objeto. [Leia mais](/pt-br/knowledge/getting-started/how-to-use-util-inspect/)
```

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +Isto iria determinar a quantidade de tempo necessária para executar as ações entre as chamadas de `console.time` e `console.timeEnd`.
```suggestion
Isto irá determinar a quantidade de tempo necessária para executar as ações entre as chamadas de `console.time` e `console.timeEnd`.
```

2019-10-06 03:33 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +Uma última função que merece ser mencionada é `console.trace()`, que exibe o conteúdo da pilha (stack trace) do momento que é chamado, sem ocasionar um erro. Isso ocasionalmente pode vim a ser útil c
```suggestion
Uma última função que merece ser mencionada é `console.trace()`, que exibe o conteúdo da pilha (stack trace) do momento que é chamado, sem ocasionar um erro. Isso ocasionalmente pode vir a ser útil caso você queira descobrir de onde determinada função com erro foi chamada.
```

2019-10-07 13:16 UTC, JCMais commented
Thanks @khaosdoctor

2019-10-07 20:02 UTC, khaosdoctor requested changes
Just a small thing I didn't see

2019-10-07 20:02 UTC, khaosdoctor commented on locale/pt-br/knowledge/getting-started/the-console-module.md
> +Qualquer pessoa familiar com o desenvolvimento voltado para navegadores provavelmente já usou `console.log` para fins de debug - O Node.js implementou um objeto `console` próprio para imitar grande p
```suggestion
Qualquer pessoa familiarizada com o desenvolvimento voltado para navegadores provavelmente já usou `console.log` para fins de debug - O Node.js implementou um objeto `console` próprio para imitar grande parte desta experiência. Porém, como nós estamos trabalhado do lado do servidor, ela funciona como uma camada acima do `stdout`, `stdin` e `stderr` em vez do console de debug do navegador.
```

Didn't see it in my previous review

2019-10-08 03:40 UTC, khaosdoctor approved these changes

2019-10-08 03:40 UTC, khaosdoctor commented
@MaledongGit this is good to go!

2019-10-09 04:43 UTC, merged