translated v8-memory-corruption-stack-overflow
nodejs/nodejs.org pull request #2714
Opened 2019-10-22 18:40 UTC by WeslleyNasRocha

2019-10-23 03:15 UTC, nschonni commented
Ping @nodejs/nodejs-pt

2019-10-23 18:09 UTC, khaosdoctor commented
Reviewing!

2019-10-23 18:11 UTC, khaosdoctor approved these changes
Small Changes :)

2019-10-23 18:11 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/v8-memory-corruption-stack-overflow.md
> +O melhor curso de ação é fazer corrigir ou atualizar o Node.js
```suggestion
O melhor curso de ação é corrigir ou atualizar o Node.js
```

2019-10-23 18:11 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/v8-memory-corruption-stack-overflow.md
> +trabalhou junto com o time do V8 para descobrir nossa resolução.
```suggestion
trabalhou junto com o time do V8 para descobrir a resolução.
```

2019-10-23 18:12 UTC, khaosdoctor requested changes
Small Changes

2019-10-29 21:45 UTC, khaosdoctor approved these changes
LGTM 👍 @Trott @MaledongGit @nschonni

2019-10-30 03:00 UTC, merged