Update getting-started-guide.md
nodejs/nodejs.org pull request #2730
Opened 2019-10-27 18:08 UTC by nellai-rider

The output of console.log was like http://${host}:${port}/, without the variables being printed.

2019-10-27 18:21 UTC, Trott requested changes

2019-10-27 18:21 UTC, Trott commented on locale/en/docs/guides/getting-started-guide.md
> +  console.log(`Server running at http://%s:%d/', hostname, port);
This introduces a syntax error. This has changed one of the backquotes to a single quote. In other words, this breaks the template string.

2019-10-27 18:24 UTC, Trott commented
> The output of console.log was like http://${host}:${port}/, without the variables being printed.

The current code is correct. The results you describe are what will happen if you replace the backquotes with single quotes. That will change the template literal into a string. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals for information on template literals.

I'd also be reluctant to make this change because format strings like this are very much not-idiomatic in JavaScript.

Thanks for the pull request. I'm going to close this since this seems to be a pretty obvious case of user error.

2019-10-27 18:24 UTC, closed without merging

2019-10-28 04:26 UTC, nellai-rider commented
Got it, As I did not copy paste, but typed myself the sample program to get started and got into that problem. I had used single quote and the sample code had back quote enclosure for the string.

The existing code works well with back-quote.  Thanks.