[PT-BR] openssl-and-low-severity-fixes-sep-2019
nodejs/nodejs.org pull request #2732
Opened 2019-10-29 17:15 UTC by WeslleyNasRocha

@nodejs/nodejs-pt por favor façam a revisão aqui

https://github.com/nodejs/nodejs-pt/issues/80

2019-10-30 22:55 UTC, nschonni commented
Ping @nodejs/nodejs-pt

2019-11-01 23:39 UTC, maugravena requested changes
I made some suggestions for improvements, thanks for your translation! @WeslleyNasRocha

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +title: Lançamento de segurança OpenSSL talvez necessite um lançamento de segurança do Node.js
```suggestion
title: Atualizações de segurança do OpenSSL talvez necessite uma atualização de segurança do Node.js
```
Tentando encontrar uma tradução melhor para "releases", caso você ache a sugestão interessante.

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +### Sumário
```suggestion
### Resumo
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +O projeto Node.js está lançando uma nova versão para todas as suas linhas suportadas
```suggestion
O projeto Node.js poderá lançar novas versões em todas as suas linhas suportadas
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +Por-favor continue lendo para mais detalhes
```suggestion
Por favor, continue lendo para mais detalhes
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +O lançamento ira corrigir dois defeitos de segurança que foram marcados com severidade "BAIXA"
```suggestion
O lançamento corrigirá dois defeitos de segurança que foram classificados com severidade "BAIXA"
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +na suas [politicas de segurança](https://www.openssl.org/policies/secpolicy.html),
```suggestion
na [política de segurança](https://www.openssl.org/policies/secpolicy.html),
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +o significado é:
```suggestion
ou seja:
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +> ... problemas que afetão apenas o utilitário da linha de comando ou configurações
```suggestion
> ... problemas como os que afetam apenas o utilitário de linha de comando do openssl
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +> improváveis.
```suggestion
> ou configurações improváveis.
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +Node.js v8.x usa OpenSSL v1.0.2 e Node.js v10.x e v12.x usam OpenSSL v1.1.1, contudo
```suggestion
O Node.js v8.x usa OpenSSL v1.0.2 e o Node.js v10.x e v12.x usam OpenSSL v1.1.1, portanto
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +todas as linhas de lançamento ativas são impactadas por essa atualização.
```suggestion
todas as linhas de versão ativas são impactadas por esta atualização.
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +assim como o impacto que elas teram nos usuários do Node.js
```suggestion
assim como o impacto que eles terão nos usuários do Node.js
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +Nesse estágio, por conta de embargos, a natureza exata desses problemas é incerta
```suggestion
Nesta fase, devido ao embargo, a natureza exata desses problemas é incerta
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +necessitarão de lançamentos de segurança imediatos do Node.js, ou se eles podem
```suggestion
exigem  atualizações imediatas de segurança do Node.js, ou se podem
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +ser incluídos na agenda de lançamentos normais.
```suggestion
ser incluídos no cronograma de atualizações normalmente.
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +Por favor monitore o grupo no Google **nodejs-sec** para mais atualizações, incluindo
```suggestion
Por favor monitore o Google Group **nodejs-sec** para mais atualizações, incluindo
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +uma decisão dentro de 24 horas depois do lançamento do OpenSSL sobre o tempo de lançamento,
```suggestion
uma decisão dentro de 24 horas depois do lançamento do OpenSSL sobre o tempo de atualização,
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +### Contato e futuros lançamentos
```suggestion
### Contato e futuras atualizações
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +A politica de segurança atual do Node.js pode ser encontrada em <https://nodejs.org/en/security/>,
```suggestion
A política de segurança atual do Node.js pode ser encontrada em <https://nodejs.org/en/security/>,
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +Se inscreva para a lista de emails de volume-baixo e apenas-anuncios do **nodejs-sec**
```suggestion
Se inscreva para a lista de emails de baixo volume e apenas anúncios **nodejs-sec**
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +no https://groups.google.com/forum/#!forum/nodejs-sec e fique por dentro das vulnerabilidades
```suggestion
em https://groups.google.com/forum/#!forum/nodejs-sec e fique por dentro das vulnerabilidades
```

2019-11-01 23:39 UTC, maugravena commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +de segurança e lançamentos relacionados à segurança do Node.js e os projetos mantidos na
```suggestion
de segurança e atualizações relacionadas à segurança do Node.js e os projetos mantidos na
```

2019-11-02 04:24 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +title: Lançamento de segurança OpenSSL talvez necessite um lançamento de segurança do Node.js
I think `releases` should be kept as is. No translation needed, it is a tech word

2019-11-02 04:28 UTC, khaosdoctor approved these changes

2019-11-02 04:28 UTC, khaosdoctor requested changes
I agree with @maugravena in the changes as well

2019-11-05 17:55 UTC, khaosdoctor approved these changes

2019-11-05 17:57 UTC, khaosdoctor requested changes
Change `release` to make it as is

2019-11-05 17:57 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +title: Lançamento de segurança OpenSSL talvez necessite um lançamento de segurança do Node.js
```suggestion
title: Release de segurança OpenSSL talvez necessite um lançamento de segurança do Node.js
```

2019-11-05 17:57 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +O lançamento corrigirá dois defeitos de segurança que foram classificados com severidade "BAIXA"
```suggestion
A release corrigirá dois defeitos de segurança que foram classificados com severidade "BAIXA"
```

2019-11-05 17:57 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +todas as linhas de lançamento ativas são impactadas por essa atualização.
```suggestion
todas as linhas de release ativas são impactadas por essa atualização.
```

2019-11-05 17:57 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +necessitarão de lançamentos de segurança imediatos do Node.js, ou se eles podem
```suggestion
necessitarão de releases de segurança imediatos do Node.js, ou se eles podem
```

2019-11-05 17:57 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +para saber de todos os detalhes dos defeitos sobre o eventual lançamento:
```suggestion
para saber de todos os detalhes dos defeitos sobre a eventual release:
```

2019-11-05 17:57 UTC, khaosdoctor commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +uma decisão dentro de 24 horas depois do lançamento do OpenSSL sobre o tempo de atualização,
```suggestion
uma decisão dentro de 24 horas depois da release do OpenSSL sobre o tempo de atualização,
```

2019-11-05 19:08 UTC, WeslleyNasRocha commented
Applied the requested changes

2019-11-07 15:34 UTC, khaosdoctor approved these changes
LGTM @Trott @nschonni @MaledongGit

2019-11-07 19:18 UTC, willchb commented on locale/pt-br/blog/vulnerability/september-2019-openssl-updates.md
> +title: Lançamento de segurança OpenSSL talvez necessite um lançamento de segurança do Node.js
"Atualizações de segurança" sounds way better than "Releases de segurança" and "Lançamento de segurança".

As is now, it doesn't sound natural: "Release de segurança OpenSSL talvez necessite um lançamento de segurança do Node.js"

I'd rather say something like: "Atualizações de segurança do OpenSSL podem necessitar de atualizações de segurança do Node.js também"

By the way, original in English is: "OpenSSL security releases may require Node.js security releases".

2019-11-08 03:10 UTC, merged