Turkish language localization
nodejs/nodejs.org pull request #2777
Opened 2019-11-17 14:38 UTC by enverarslan

Hi, everyone.

I think this version of Turkish language localization is enough for starting. I copied non-translated files from English locale files for may community help us for translation.

### Translated
- Homepage
- About
- Download
- Docs Index
- 404
- Navigations
- Footer links

2019-11-17 15:43 UTC, Trott commented
@nodejs/nodejs-tr

2019-11-17 21:59 UTC, nschonni requested changes
Can you remove the files that aren't being translated. Those already get redirected to the English versions, so copying them in means they'll likely get out of date with the original English ones till they're translated

2019-11-17 23:05 UTC, nschonni approved these changes

2019-11-23 09:13 UTC, merged

2019-11-23 09:14 UTC, MaledongGit commented
@enverarslan: Thanks for your great contributions for Nodejs