Update event-loop-timers-and-nexttick.md
nodejs/nodejs.org pull request #2778
Opened 2019-11-18 01:38 UTC by meooxx

The original article is like being translated from Google. I made some changes to make the sentence smoother.

2019-11-18 01:41 UTC, nschonni commented
Ping @nodejs/nodejs-cn

2019-11-21 13:18 UTC, pan93412 requested changes
> add space between English or special characters and Chinese characters.

You can use [this tool](https://github.com/vinta/pangu.js) to add space automatically.

Also, please review again as I saw many meaningless spaces.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +当 Node.js 启动后，它会初始化事件轮询；处理已提供的输入脚本（或丢入 [REPL][]，本文不涉及到），它可能会调用一些异步的 API ，调度定时器，或者调用 `process.nextTick()`，然后开始处理事件循环。
```
一些异步的 API、调度定时器，或者调用 `process.nextTick()`
```

A **、** B 或 C

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +下面的图表展示了事件循环的操作顺序的简化概览。
...事件循环操作顺序的简化概览。

Please remove the useless "的".

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +每个阶段都有一个 FIFO 队列来执行回调。虽然每个阶段都是特殊的，但通常情况下，当事件循环进入给定的阶段时，它将执行特定于该阶段的任何操作，然后执行该阶段队列中回调，直到队列用尽或最大回调数已执行。当该队列已用尽或达到回调限制，事件循环将移动到下一阶段，等等。
执行该阶段队列中 **的** 回调

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +例如，假设您调度了一个在 100 毫秒后超时定时器，然后您的脚本开始去异步的读取一个耗费95ms文件:
- 假设您调度了一个在 100 毫秒后超时 **的** 定时器
- 然后您的脚本开始 ~~去~~ 异步 ~~的~~ 读取 **会** ~~一个~~ 耗费 95ms **的** 文件
  - -> 然后您的脚本开始异步读取会耗费 95ms 的文件

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +* _如果 **轮询** 队列 **不是空的**_ ，事件循环 将循环访问回调队列并同步执行它们，直到队列已用尽，或者达到了与系统相关的硬性限制。
remove the meaningless space between chinese characters.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +此阶段允许人员在轮询阶段完成后立即执行回调。如果轮询阶段变为空闲状态，并且脚本使用 `setImmediate()`后被排列在队列中，则事件循环可能继续到 **检查** 阶段而不是等待。
并且脚本使用 `setImmediate()` 后被排列在队列中

add space between English or special characters (\`) and Chinese characters

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +通常，在执行代码时，事件循环最终会命中轮询阶段，在那等待传入连接、请求等。但是，如果回调已使用 `setImmediate()`调度过，并且轮询阶段变为空闲状态，则它将结束此阶段， 并继续到检查阶段而不是继续等待轮询事件。
remove the meaningless space between chinese characters.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +`setImmediate()` 和 `setTimeout()` 很类似，但是 基于被调用的时机，他们也有不同表现。
remove the meaningless space between chinese characters.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +* `setTimeout()` 在最小阈值(ms单位)过后运行脚本。
add space between English or special characters (`(` and `)`) and Chinese characters,
also, you can remove '單位' that can be omitted.

` 在最小阈值 (ms) 过后运行脚本。`

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +使用 `setImmediate()` 相对于`setTimeout()` 的主要优势是，如果`setImmediate()`是在I/O周期内被调度的，那它将会在其中任何的定时器之前执行， 跟这里存在多少个定时器无关
add space between English or special characters and Chinese characters.

https://github.com/nodejs/nodejs-zh-CN
> 请直接前往 [Issue 列表](https://github.com/nodejs/iojs-cn/issues)找到你感兴趣的 Issue 参与讨论，也可申请指派翻译任务。为了保持一致性，提升文档的质量，**在翻译之前建议先查阅下[中英文排版规范](https://github.com/sparanoid/chinese-copywriting-guidelines)**。请按照以下流程执行，避免浪费人力做相同的事情。

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +回顾我们的图示，任何时候在给定的阶段中调用 `process.nextTick()`，所有传递到 `process.nextTick()` 的回调将在事件循环继续之前解析。这可能会造成一些糟糕的情况, 因为**它允许您通过递归 `process.nextTick()`调用 来“饿死”您的 I/O**，阻止事件循环到达 **轮询** 阶段。
add space between English or special characters and Chinese characters.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +代码段进行参数检查。如果不正确，则会将错误传递给回调函数。最近对API 进行了更新，允许传递参数给 `process.nextTick()`，这将允许它接受任何在回调函数位置之后的参数，并将参数传递给回调函数作为回调函数的参数，这样您就不必嵌套函数了。
add space between English or special characters and Chinese characters.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +我们正在做的是将错误传回给用户，但仅在我们已让用户的其余代码执行之后。通过使用`process.nextTick()`，我们保证 `apiCall()` 始终在用户代码的其余部分*之后*和在让事件循环继续进行*之前*，执行其回调函数。为了实现这一点，JS 调用栈被允许展开，然后立即执行提供的回调，允许进行递归调用 `process.nextTick()`，而不达到 `RangeError: 超过
> 而不达到 `RangeError: 超过 V8 的最大调用堆栈大小`

My suggestion:
```
而不碰到 `RangeError: 超过 V8 的最大调用堆栈大小` 限制
```

> 但仅在我们已让用户的其余代码执行之后

-> 但仅在执行用户的其余代码之后

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +通过将回调置于 `process.nextTick()` 中，脚本仍具有运行完成的能力，允许在调用回调之前初始化所有的变量、函数等。它还具有不让事件循环继续的优点。它可以在让事件循环继续之前，把错误警告给用户， 这方面有用。下面是上一个使用 `process.nextTick()` 的示例：
> 它适合在让事件循环继续之前警告警告用戶错误。

i think the source is `it is useful for`.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +只有端口被传递时，端口才会立即被绑定。因此，可以立即调用 `'listening'` 回调。问题是 `.on('listening')` 的回调在那个时间点尚未被设置。
只有传递端口时

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +* `setImmediate()` 在事件循环的接下来的迭代或'tick'上触发。
add space between English or special characters and Chinese characters.

Please read the instruction above and self-review this article again.

2019-11-21 13:18 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +假设 `listen()` 在事件循环开始时运行，但listening的回调被放置在 `setImmediate()` 中。除非传递过主机名，才会立即绑定到端口。为使事件循环继续进行，它必须命中 **轮询** 阶段，这意味着有可能已经接收了一个连接，并在侦听事件之前触发了连接事件。
add space between English or special characters and Chinese characters.

`但 listening 的回调被放置在`

2019-11-23 08:36 UTC, MaledongGit commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +假设 `listen()` 在事件循环开始时运行，但listening的回调被放置在 `setImmediate()` 中。除非传递过主机名，才会立即绑定到端口。为使事件循环继续进行，它必须命中 **轮询** 阶段，这意味着有可能已经接收了一个连接，并在侦听事件之前触发了连接事件。
@pan93412: Thanks for this tip, 'listening' should better be translated to Chinese if it can. So here '侦听' is better.

2019-11-23 08:41 UTC, MaledongGit commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +例如，假设您调度了一个在 100 毫秒后超时定时器，然后您的脚本开始去异步的读取一个耗费95ms文件:
ms => 毫秒，尽量能够全部汉化的汉化，注释保留原版英语 ;)

2019-11-23 09:03 UTC, ghost approved these changes
Firstly, GREAT thanks for the reviewer @pan93412 and contributor @meooxx ！
Then, there're some issues fixed by me according to @pan93412 and my ideas. It should be good with me ;)

2019-11-23 10:21 UTC, amorist approved these changes

2019-11-24 05:31 UTC, pan93412 requested changes
Thanks for @MaledongGit works! but I just found some mistakes. :(

2019-11-24 05:31 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +当 Node.js 启动后，它会初始化事件轮询；处理已提供的输入脚本（或丢入 [REPL][]，本文不涉及到），它可能会调用一些异步的 API ，调度定时器，或者调用 `process.nextTick()`，然后开始处理事件循环。
它可能会调用一些异步的 API、调度定时器，或者调用 `process.nextTick()`，然后开始处理事件循环。

2019-11-24 05:31 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +主要有两个主要原因：
贅詞

`有两个主要原因：`

2019-11-24 05:31 UTC, pan93412 commented on locale/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
> +一个符合用户的预期的例子。简单示例：
一个符合用户的预期的簡單例子：

2019-11-24 07:30 UTC, pan93412 approved these changes

2019-11-24 07:47 UTC, merged