[Localization] Add and Fix Some Japanese Translations
nodejs/nodejs.org pull request #2859
Opened 2019-12-26 12:21 UTC by cmplstofB

Hello.
I added and fixed some of the Japanese translations for the Node.js’ website.

If there is no problem, would you please merge them?

---

The following is a commentary that describes why I had changed an existing translation.

(in Japanese)
“scrollToTop”とは「（表示されている）Webページの一番上まで移動する」動作を意味しています。
既存の翻訳「上部へスクロールする」は訳語としては正確ではありますが，
当動作を指す言葉としてはあまり一般的でないように感じます（あくまで主観です）。
日本政府及び関連機関が運営するサイトにおいては，
当動作を行う機能の標示として「ページの先頭へ」という語を充てているようです。
（参考1: [国立国会図書館](https://www.ndl.go.jp/)，参考2: [首相官邸](https://www.kantei.go.jp/)）
典拠と言うには烏滸がましいかもしれませんが，上記を踏まえて訳語を変更しました。
なお，私による最初の[変更](https://github.com/cmplstofB/nodejs.org/commit/77d7e3ad997e10445626e08e55b00bbe414c9dfa#diff-71ccf9d143f55cfe82d28766abffda3dR9)は，
暫定訳として手許に残しておいた語を誤って確定してしまったものです。
すいません。

2019-12-27 00:43 UTC, nschonni commented
Ping @nodejs/nodejs-ja

2019-12-27 00:51 UTC, okuryu commented on locale/ja/site.json
> +  "scrollToTop": "ページの先頭へ",
👍

2019-12-27 00:52 UTC, okuryu commented on locale/ja/site.json
> +  "nightly": "最新不安定版",
不安定とは限らないと思うので、「開発版」でどうでしょうか。
```suggestion
  "nightly": "最新の開発版",
```

2019-12-27 00:53 UTC, okuryu commented on locale/ja/site.json
> +      "text": "書庫化バイナリから Node.js をインストールする"
書庫化って聞きなれないですね。。「アーカイブ」でいいと思いました。
```suggestion
      "text": "バイナリアーカイブから Node.js をインストールする"
```

2019-12-27 00:55 UTC, okuryu commented on locale/ja/site.json
> +      "text": "コード及び学習"
「及び」はひらがなの方がいいかもしれません。

```suggestion
      "text": "コードおよび学習"
```

JTF日本語標準スタイルガイド
https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf
> 接続詞の場合。常用漢字表にあるが、ひらがなを使う。

2019-12-27 02:23 UTC, cmplstofB commented on locale/ja/site.json
> +  "nightly": "最新不安定版",
確かにそちらの方が適切ですね。

2019-12-27 02:25 UTC, cmplstofB commented on locale/ja/site.json
> +      "text": "コード及び学習"
申し訳ないです，スタイルガイドの存在を知りませんでした（文章作法は日本産業規格に従っていました）。
スタイルガイドの規約に合わせます。

2019-12-27 03:20 UTC, cmplstofB commented on locale/ja/site.json
> +      "text": "書庫化バイナリから Node.js をインストールする"
確かに，連語としての“binary archive”の訳語は「バイナリアーカイブ」が適切ですね……（[dpkgの翻訳](https://github.com/oerdnj/dpkg/blob/master/po/ja.po#L5122)を見ても）。
調査不足で申し訳ないです，「バイナリアーカイブ」に修正して下さい。

2019-12-27 04:35 UTC, watilde commented on locale/ja/site.json
> +      "text": "書庫化バイナリから Node.js をインストールする"
書庫化バイナリから => アーカイブから

2019-12-27 04:35 UTC, watilde commented on locale/ja/site.json
> +      "text": "コード及び学習"
We might want to keep this as is in English

2019-12-27 06:32 UTC, okuryu commented on locale/ja/site.json
> +      "text": "書庫化バイナリから Node.js をインストールする"
なるほど。アーカイブだけでも良さそうですね。

2020-01-01 12:12 UTC, Maruda1986 commented
d

2020-01-03 16:44 UTC, okuryu requested changes
Please apply the changes I suggested.

2020-01-23 00:24 UTC, MaledongGit commented
@cmplstofB: Thanks for your 1st contribution, and if possible and free, please leave your feedback messages to @okuryu, or do changes and submit.

2020-01-24 01:07 UTC, cmplstofB commented
@MaledongGit Thanks you to announce me.

@okuryu Thank you to review and fix translation. I have no complaint about your suggestion. I thought I had applied your changes, but it doesn't seem to be done.
Sorry to trouble you, can you tell me how to do it?

2020-01-24 01:21 UTC, okuryu commented
It looks like you just resolved the conversation without applying my suggestions (see also [GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)). Please try to commit and push the changes to your branch again.

2020-01-24 02:42 UTC, cmplstofB commented
@okuryu I see. I was mistaken about applying suggested changes... Thank you for teaching me.

2020-01-24 02:42 UTC, closed without merging