fix: Enable remark-lint-no-trailing-spaces
nodejs/nodejs.org pull request #3120
Opened 2020-04-19 18:00 UTC by nschonni

2020-04-21 18:22 UTC, XhmikosR requested changes

2020-04-21 18:22 UTC, XhmikosR commented on locale/uk/about/governance.md
> -Не більш як 1/3 від всіх членів TSC можуть бути пов’язані одним роботодавцем.
This is meant to be a line break.

2020-04-21 18:22 UTC, XhmikosR commented on static/legacy/README.md
> +Those assets are still being used by legacy versions of the Node.js docs.
Same here

2020-04-21 18:22 UTC, XhmikosR commented on static/legacy/README.md
> +The actual URL rewriting is done in the nodejs.org nginx config:
And here

2020-04-21 19:32 UTC, nschonni commented
@XhmikosR the rule doesn't support double space as line break, so they are converted to explicit line breaks instead. I've opened an upstream issue for support, but I wouldn't block this waiting for it

2020-04-21 19:34 UTC, XhmikosR commented
IMHO since this is a perfectly valid Markdown way of doing things and this rule doesn't follow the specs, it shouldn't be merged.

2020-04-21 19:46 UTC, nschonni commented
It's the style of the Node formatting rules upstream. It's not that the rule doesn't follow the spec, it just says that style of line break shouldn't be used

2020-04-24 13:50 UTC, Trott commented
> It's the style of the Node formatting rules upstream. It's not that the rule doesn't follow the spec, it just says that style of line break shouldn't be used

Maybe add a disable comment in the `locale/uk` file affected and don't worry about the legacy README as long as the resulting format is still intelligible?

2020-05-02 01:12 UTC, nschonni commented
@Trott the style isn't being used on the English content, so I don't think it makes sense for the Ukrainian docs only

2021-07-16 10:41 UTC, MaledongGit commented
This now is solved by adding https://github.com/nodejs/nodejs.org/blob/cf0873f7b4a8c203530667a0ba7260fb3127b73e/.remarkrc#L11.

2021-07-16 15:31 UTC, nschonni commented
@MaledongGit that isn't resolved, that is the current work around that existed when this PR was opened. This was to enable and fix the rule. That's usually the goal of the "temporary" suppression of the rules in `.remarkrc`

2021-07-16 17:31 UTC, merged