[PT-BR]: translate about resources to pt-br
nodejs/nodejs.org pull request #3125
Opened 2020-04-20 20:36 UTC by AugustoCalaca

ping friendly @khaosdoctor

2020-04-20 20:38 UTC, nschonni commented
Might be better to submit on https://crowdin.com/project/nodejs-website/pt-BR

2020-04-22 08:46 UTC, alexandrtovmach commented
@AugustoCalaca Thank you for contribution. We're moving translation process to Crowdin, please read these guidelines for more information:
https://github.com/nodejs/i18n/#contributing

2020-04-22 08:49 UTC, alexandrtovmach commented
@nodejs/nodejs-pt Please manage this PR [until **May 1, 2020**](https://github.com/orgs/nodejs/teams/translators/discussions/7)

2020-04-22 11:29 UTC, JCMais commented on locale/pt-br/about/resources.md
> +Por favor, revise [política de marca registrada](/pt/about/trademark/) para informações sobre o que é permitido aos usuários das logos e marcas do Node.js®.
```suggestion
Por favor, revise a [política de marca registrada](/pt/about/trademark/) para informações sobre o uso permitido das logos e marcas do Node.js®.
```

2020-04-22 11:31 UTC, JCMais commented on locale/pt-br/about/resources.md
> +Orientações para a mostra visual da marca Node.js são descritas em [Orientações Visuais](/static/documents/foundation-visual-guidelines.pdf).
```suggestion
Orientações para a exibição visual da marca Node.js estão disponíveis em [Orientações Visuais](/static/documents/foundation-visual-guidelines.pdf).
```

2020-04-22 11:32 UTC, JCMais commented on locale/pt-br/about/resources.md
> +    <td class="bg-node-gray"><a href="/static/images/logos/nodejs-new-pantone-white.ai"><img src="/static/images/logos/nodejs-new-pantone-white.svg" alt="Node.js on dark background"></a></td>
```suggestion
    <td class="bg-node-gray"><a href="/static/images/logos/nodejs-new-pantone-white.ai"><img src="/static/images/logos/nodejs-new-pantone-white.svg" alt="Node.js sobre um plano de fundo escuro"></a></td>
```

2020-04-22 11:32 UTC, JCMais commented on locale/pt-br/about/resources.md
> +    <td class="bg-white"><a href="/static/images/logos/nodejs-new-pantone-black.ai"><img src="/static/images/logos/nodejs-new-pantone-black.svg" alt="Node.js on light background"></a></td>
```suggestion
    <td class="bg-white"><a href="/static/images/logos/nodejs-new-pantone-black.ai"><img src="/static/images/logos/nodejs-new-pantone-black.svg" alt="Node.js sobre um plano de fundo claro"></a></td>
```

2020-04-22 11:33 UTC, JCMais commented on locale/pt-br/about/resources.md
> +    <td class="bg-white"><a href="/static/images/logos/nodejs-new-black.ai"><img src="/static/images/logos/nodejs-new-black.svg" alt="Node.js on light background"></a></td>
```suggestion
    <td class="bg-white"><a href="/static/images/logos/nodejs-new-black.ai"><img src="/static/images/logos/nodejs-new-black.svg" alt="Node.js sobre um plano de fundo claro"></a></td>
```

2020-04-22 11:33 UTC, JCMais commented on locale/pt-br/about/resources.md
> +    <td class="bg-node-gray"><a href="/static/images/logos/nodejs-new-white.ai"><img src="/static/images/logos/nodejs-new-white.svg" alt="Node.js on dark background"></a></td>
```suggestion
    <td class="bg-node-gray"><a href="/static/images/logos/nodejs-new-white.ai"><img src="/static/images/logos/nodejs-new-white.svg" alt="Node.js sobre um plano de fundo escuro"></a></td>
```

2020-04-22 11:34 UTC, JCMais requested changes
I've left some suggestions

2020-04-22 18:57 UTC, JCMais approved these changes
looks good, thanks @AugustoCalaca

2020-04-25 14:49 UTC, TiagoDanin approved these changes
:+1: LGTM

2020-04-25 14:51 UTC, JCMais commented
@AugustoCalaca could you please rebase this against master?

2020-04-25 15:28 UTC, alexandrtovmach commented
@AugustoCalaca Thanks for contribution
@JCMais @TiagoDanin Additional thanks for reviews

2020-04-25 15:29 UTC, merged