Create getting-started-guide.md
nodejs/nodejs.org pull request #3312
Opened 2020-07-20 16:55 UTC by LuanComputacao

Translation to pt-br of the original en-us page

2020-10-15 22:15 UTC, nschonni commented
Ping @nodejs/nodejs-pt

2020-10-15 22:19 UTC, nschonni commented on locale/pt-br/docs/guides/getting-started-guide.md
> +
Remove extra line to make linter happy
```suggestion
```

2020-10-21 17:54 UTC, khaosdoctor commented
Taking a look at it!

2020-10-27 18:58 UTC, khaosdoctor requested changes
There's one small  correction

2020-10-27 18:58 UTC, khaosdoctor commented on locale/pt-br/docs/guides/getting-started-guide.md
> +Uma ves instalado o Node.js, vamos começar nosso primeiro web server.
```suggestion
Uma vez instalado o Node.js, vamos começar nosso primeiro web server.
```

2021-06-15 15:03 UTC, khaosdoctor commented
It's been a while since this has been opened... Is it still useful?

2021-12-19 08:19 UTC, XhmikosR commented
Since the fork repo is gone, this is now obsolete. Feel free to make a new PR.

2021-12-19 08:19 UTC, closed without merging