abi-stablity spanish version
nodejs/nodejs.org pull request #3374
Opened 2020-09-14 19:07 UTC by cristiandelcidd

Support for node Spanish documentation

2020-09-14 19:59 UTC, nschonni commented
Thanks, can you take a look at the formatting issues
```
   18:539-18:561  warning  Use the trailing `[]` on reference links  no-shortcut-reference-link  remark-lint
    31:1-31:210  warning  Don’t pad `strong` with inner spaces      no-inline-padding           remark-lint
    31:16-31:21  warning  Don’t pad `emphasis` with inner spaces    no-inline-padding           remark-lint
```

2020-09-14 20:00 UTC, nschonni requested changes

2020-09-14 20:00 UTC, nschonni commented on locale/es/docs/guides/abi-stability.md
> +Con estos fines, Node.js ha introducido N-API en la versión 8.6.0 y lo ha marcado como un componente estable del proyecto a partir de Node.js 8.12.0. La API se define en los encabezados [`node_api.h`
```suggestion
Con estos fines, Node.js ha introducido N-API en la versión 8.6.0 y lo ha marcado como un componente estable del proyecto a partir de Node.js 8.12.0. La API se define en los encabezados [`node_api.h`][] y [` node_api_types.h`][], y proporciona una garantía de compatibilidad con versiones posteriores que cruza el límite de la versión principal de Node.js. La garantía puede expresarse de la siguiente manera:
```

2020-09-14 20:00 UTC, nschonni commented on locale/es/docs/guides/abi-stability.md
> +** Una versión * n * dada de N-API estará disponible en la versión principal de Node.js en la que se publicó y en todas las versiones posteriores de Node.js, incluidas las versiones principales poste
```suggestion
**Una versión *n* dada de N-API estará disponible en la versión principal de Node.js en la que se publicó y en todas las versiones posteriores de Node.js, incluidas las versiones principales posteriores.**
```

2020-09-14 20:01 UTC, nschonni commented
Ping @nodejs/nodejs-es

2020-09-21 04:56 UTC, nschonni commented on locale/es/docs/guides/abi-stability.md
> +Node.js proporciona archivos de encabezado mantenidos por varios equipos independientes. Por ejemplo, el equipo de Node.js mantiene archivos de encabezado como `node.h` y` node_buffer.h`. `v8.h` es m
```suggestion
Node.js proporciona archivos de encabezado mantenidos por varios equipos independientes. Por ejemplo, el equipo de Node.js mantiene archivos de encabezado como `node.h` y` node_buffer.h`. `v8.h` es mantenido por el equipo de V8, que, aunque en estrecha cooperación con el equipo de Node.js, es independiente y tiene su propio horario y prioridades. Por lo tanto, el equipo de Node.js solo tiene control parcial sobre los cambios que se introducen en los encabezados que proporciona el proyecto. Como resultado, el proyecto Node.js adoptó [versiones semánticas](https://semver.org/). Esto asegura que las API proporcionadas por el proyecto darán como resultado una ABI estable para todas las versiones menores y de parche de Node.js lanzadas dentro de una versión principal. En la práctica, esto significa que el proyecto Node.js se ha comprometido a garantizar que un complemento nativo de Node.js compilado con una versión principal determinada de Node.js se cargue correctamente cuando lo cargue cualquier versión menor o parche de Node.js dentro de la principal. versión contra la que se compiló.
```

2020-11-02 22:02 UTC, wardaks24 approved these changes

2021-03-06 01:01 UTC, closed without merging