Updated the Language selector icon
nodejs/nodejs.org pull request #3503
Opened 2020-11-09 05:15 UTC by DantrazTrev

For issue #3372 
I've changed the language selector icon to a better one, that is easily identifiable for all users 
![image](https://user-images.githubusercontent.com/43457420/98502572-560c5200-2278-11eb-8c06-2fa87af1761c.png)

As mentioned in the issue
The current icons makes it look like the site will be automatically translated with Google Translate, rather than actual human translations.

2021-02-14 06:04 UTC, XhmikosR commented
@nschonni @Trott thoughts?

2021-02-14 06:04 UTC, XhmikosR commented on layouts/partials/header.hbs
> +      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="20" height="20" aria-hidden="true" focusable="false" fill="currentColor">
We should try and keep the previous dimensions

2021-02-14 06:08 UTC, Trott commented
> @nschonni @Trott thoughts?

If don't have an opinion on this one and am happy to defer to you, @nschonni, and anyone else in the website group who might be paying more attention to this particular interface element.

2021-02-14 06:09 UTC, XhmikosR commented
I'm not sure I like this new icon TBH. But the previous one, is wrong too, because it's from Google translate.

2021-02-15 05:23 UTC, nschonni commented
Where did the new icon come from? I'm not sure if the current one was properly sourced either 😄

2021-02-15 13:55 UTC, XhmikosR commented
That I don't know either. Better put this on hold then?

2021-03-27 09:24 UTC, MaledongGit commented
What about this article about the language icon? Use for free.

http://www.languageicon.org/

2021-11-11 14:09 UTC, DerekNonGeneric commented
> What about this article about the language icon? Use for free.
> 
> http://www.languageicon.org/

It looks like we are going to be going w/ that suggestion. Thanks for the link, I was able to convert that to an optimized SVG for whoever wants to do the honors. @DantrazTrev, you may be able to simply modify your PR to use the following SVG.

https://codepen.io/DerekNonGeneric/pen/bGroexG

Also, please take dark mode into account if you do end up going for it as this icon would need to be made into a lighter color to contrast the dark background.

2021-11-11 14:09 UTC, DerekNonGeneric requested changes
> What about this article about the language icon? Use for free.
> 
> http://www.languageicon.org/

It looks like we are going to be going w/ that suggestion. Thanks for the link, I was able to convert that to an optimized SVG for whoever wants to do the honors. @DantrazTrev, you may be able to simply modify your PR to use the following SVG.

https://codepen.io/DerekNonGeneric/pen/bGroexG

Also, please take dark mode into account if you do end up going for it as this icon would need to be made into a lighter color to contrast the dark background.

2022-09-02 00:20 UTC, closed without merging