Revert "chore: add link to OpenJSF Slack channel"
nodejs/nodejs.org pull request #3619
Opened 2021-01-05 23:21 UTC by mmarchini

This reverts commit c10bb69904ff1b069af4adbe912661f5cfa83cba.

----

Based on discussion from https://github.com/nodejs/community-committee/issues/655, the change was added without appropriate communications and with lack of approval from CommComm (which should be involved in such decisions). Therefore reverting it until further discussion takes place.

2021-01-05 23:22 UTC, mmarchini commented
cc @nodejs/community-committee (and @nodejs/tsc for awareness)

2021-01-05 23:28 UTC, nschonni approved these changes

2021-01-05 23:30 UTC, mhdawson approved these changes
LGTM. Good step to take while the discussion as to how to move forward takes place.

2021-01-07 17:02 UTC, bnb commented
IMO unnecessary but understandable. Will not -1, but do want to make the assertion that I don't see anything wrong with having this.

2021-01-07 17:40 UTC, MylesBorins requested changes, later dismissed
-1

We have channels in this slack where project work happens including build + release. If we want to change the order, something I had mentioned in the original PR, I would have no problem... but I do not think that it makes sense to remove this.

2021-01-07 18:12 UTC, joepie91 commented
> -1
> 
> We have channels in this slack where project work happens including build + release. If we want to change the order, something I had mentioned in the original PR, I would have no problem... but I do not think that it makes sense to remove this.

This change concerns (what is perceived as) community channels, not project work venues.

2021-01-07 18:17 UTC, mmarchini commented
@MylesBorins fwiw I preserved the changes on nodejs/node documentation since those are mostly core development related. For WGs work, I think those specific channels are (or should be) linked on the WG readmes?

2021-01-07 18:20 UTC, MylesBorins commented
We have node slackers and the IRC channel in here. The OpenJS slack is a foundation run and moderated space and I think it belongs on that list just as much as the other channels. I do not think it should be removed. I'm going to my dismiss my objection but I don't think it makes sense to remove this only to open up another discussion to decide to bring it back. The Slack belongs on this list. I'd like to suggest we simply change the order and make IRC first out of respect for the history of the channel.

2021-01-07 18:36 UTC, mmarchini commented
Opened another PR as an alternative: https://github.com/nodejs/nodejs.org/pull/3626

2021-02-13 04:50 UTC, MaledongGit commented
Compare with the two versions, and I've taken your latest one by merging it, with many people's approves. So will this be closed or ?

PS：Agree with @MylesBorins , because these discussions are related to Nodejs, it'd be better to put here, which will make better for Node.js fans.

2021-06-07 18:36 UTC, Atom1985 commented on locale/en/get-involved/index.md
> +* For real-time chat about Node.js development go to `irc.freenode.net` in the `#node.js` channel with an [IRC client](https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients) or conn
```suggestion
* For real-time chat about Node.js development go to `irc.freenode.net` in the `#node.js` channel with an [IRC client](https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients) or connect in your web browser to the channel using [freenode's WebChat](https://webchat.freenode.net/#node.js).
```

2021-06-07 18:59 UTC, mmarchini commented
Since the other one was closed this one can be closed.

2021-06-07 18:59 UTC, closed without merging