Translating Title to Arabic.
nodejs/nodejs.org pull request #3679
Opened 2021-02-11 04:07 UTC by E3saR33

2021-02-11 04:49 UTC, nschonni commented
ping @nodejs/nodejs-ar

2021-02-11 19:24 UTC, celyes approved these changes
Looks good to me.

@Aissaoui-Ahmed take a look

2021-02-12 23:27 UTC, Aissaoui-Ahmed requested changes

2021-02-12 23:27 UTC, Aissaoui-Ahmed commented on locale/ar/download/package-manager.md
> +# أو للتحميل الكامل بواسطة npm
```suggestion
# أو للتثبيت الكامل بواسطة npm
```

2021-02-13 22:44 UTC, aymen94 approved these changes

2021-02-14 09:19 UTC, celyes approved these changes

2021-02-14 13:57 UTC, Aissaoui-Ahmed approved these changes

2021-02-14 13:57 UTC, Aissaoui-Ahmed approved these changes

2021-02-14 14:03 UTC, merged