add note for Chrome DevTools
nodejs/nodejs.org pull request #3888
Opened 2021-05-22 14:26 UTC by tigercosmos

mention that the nodeJS and Chrome need to be on the same platform for using Chrome DevTools

2021-08-27 08:02 UTC, ghost submitted a review, later dismissed

2021-08-27 08:02 UTC, ghost commented on locale/en/docs/guides/debugging-getting-started.md
> +> note that the NodeJS and the Chrome need to be run on the same platform, for example, a NodeJS running on Linux and a Chrome running on Linux.
Nothing but some tiny suggestions：

1. "note" should be "Note"?

2. "for example, a NodeJS running on Linux and a Chrome running on Linux.", is this a bit duplicated? Because you've mentioned:

> Note that the NodeJS and the Chrome need to be run on the same platform

2021-08-27 08:04 UTC, ghost reviewed
Please use `test:lint:stylelint -- --fix` to fix the style first and submit.

2021-08-27 08:15 UTC, ghost commented
Ping @nodejs/documentation : Any other ideas about it to guide the juniors in a detailled info?

2021-08-27 14:40 UTC, tigercosmos commented
@MaledongGit fix. also have run `test:lint:stylelint -- --fix`

2021-08-28 00:32 UTC, MaledongGit approved these changes

2021-08-28 00:33 UTC, MaledongGit commented
@tigercosmos: Great! Thanks for your contribution, and I've invited others to see...If there's no ideas against you, it will be merged.

2021-08-30 09:35 UTC, aymen94 approved these changes

2021-08-30 18:55 UTC, trivikr requested changes

2021-08-30 18:55 UTC, trivikr commented on locale/en/docs/guides/debugging-getting-started.md
> +> Note that the NodeJS and the Chrome need to be run on the same platform.
Use Node.js
```suggestion
> Note that the Node.js and the Chrome need to be run on the same platform.
```

2021-08-31 00:26 UTC, trivikr approved these changes

2021-08-31 00:45 UTC, merged

2021-08-31 00:45 UTC, MaledongGit commented
@tigercosmos: Thanks for your contribution, and don't forget to translate it into zh-TW.

2021-08-31 00:53 UTC, MaledongGit commented
Ping @nodejs/translators

2021-08-31 00:53 UTC, MaledongGit commented
Ping @nodejs/translators