docs: Improve some zh-tw translations in download/package-manager.md
nodejs/nodejs.org pull request #3951
Opened 2021-07-04 08:29 UTC by PeterDaveHello

cc @nodejs/nodejs-tw

2021-07-04 08:31 UTC, PeterDaveHello commented
@bluet @jackycute not sure if you guys would like to help take a look/review 😃

2021-07-04 09:07 UTC, jackycute requested changes
Would love to give a review @PeterDaveHello 
I've made some suggestion according to the en version.
https://github.com/nodejs/nodejs.org/blob/master/locale/en/download/package-manager.md

2021-07-04 09:07 UTC, jackycute commented on locale/zh-tw/download/package-manager.md
> +然後執行 `nvs use` ，為當前腳本的 `PATH` 路徑下新增一個 node 版本：
```suggestion
然後執行 `nvs use` ，為目前 shell 的 `PATH` 路徑下新增一個 node 版本：
```

2021-07-04 09:07 UTC, jackycute commented on locale/zh-tw/download/package-manager.md
> +你可以在 [此處](https://github.com/jasongin/nvs/blob/master/doc/SETUP.md#mac-linux) 找到關於在 macOS / 形如 Unix-like 作業系統的安裝步驟文件。
```suggestion
你可以在 [此處](https://github.com/jasongin/nvs/blob/master/doc/SETUP.md#mac-linux) 找到關於在 macOS / Unix-like 作業系統的安裝步驟文件。
```

2021-07-04 09:24 UTC, jackycute approved these changes
LGTM.

2021-07-04 15:28 UTC, bluet approved these changes
LGTM

2021-07-05 05:48 UTC, PeterDaveHello commented
Thank you guys 😄

2021-07-05 05:49 UTC, merged