Update nodejs-docker-webapp.md
nodejs/nodejs.org pull request #4293
Opened 2021-12-13 07:08 UTC by endeesa

Since the PORT environment variable is set to 8080, the run command should expose port 8080 from the container to port 8080 on the host

2022-02-18 11:33 UTC, aymen94 approved these changes

2022-08-05 09:34 UTC, aymen94 requested changes
You should update the other lines containing the same port number in the same file

2022-09-17 18:53 UTC, lxmarinkovic approved these changes

2022-12-30 10:55 UTC, ovflowd commented
Closing as stale.

2022-12-30 10:55 UTC, closed without merging