Update Releases.md
nodejs/nodejs.org pull request #4544
Opened 2022-04-12 21:56 UTC by jnaubry

First draft of french translation for the Release page.

2022-04-13 00:39 UTC, nschonni approved these changes

2022-04-13 00:39 UTC, nschonni commented
Ping @nodejs/nodejs-fr

2022-04-13 07:26 UTC, cedced19 reviewed
Just a little omission with the word "general" not translated.

2022-04-13 07:26 UTC, cedced19 commented on locale/fr/about/releases.md
> +Les versions majeures de Node.js entrent dans le statut de version _Current_ pour six mois, ce qui laisse le temps aux auteurs des librairies d'ajouter le support nécessaire. Après six mois les versi
"ready for general use" can be translated by "prêt pour une utilisation générale" or by "prêt pour une utilisation grand publique".
This is just a little omission, the rest is well translated.

2022-04-13 07:28 UTC, abenhamdine requested changes

2022-04-13 07:28 UTC, abenhamdine commented on locale/fr/about/releases.md
> +Les versions majeures de Node.js entrent dans le statut de version _Current_ pour six mois, ce qui laisse le temps aux auteurs des librairies d'ajouter le support nécessaire. Après six mois les versi
fixés -> corrigés
prodution -> production

2022-04-13 07:28 UTC, abenhamdine commented on locale/fr/about/releases.md
> +Les versions majeures de Node.js entrent dans le statut de version _Current_ pour six mois, ce qui laisse le temps aux auteurs des librairies d'ajouter le support nécessaire. Après six mois les versi
> Les applications utilisées en prodution doivent utiliser uniquement les versions

should ne traduit pas une obligation, mais une forte préconisation.
Une meilleure traduction serait 
"Pour des applications utilisées en production, il est fortement préconisé d'utiliser uniquement les versions Active LTS ou Maintenance LTS"

2022-04-13 08:13 UTC, aduh95 commented on locale/fr/about/releases.md
> +Les versions majeures de Node.js entrent dans le statut de version _Current_ pour six mois, ce qui laisse le temps aux auteurs des librairies d'ajouter le support nécessaire. Après six mois les versi
```suggestion
Les versions majeures de Node.js entrent dans le statut de version _Current_ pour six mois, ce qui laisse le temps aux auteurs des librairies d'ajouter le support nécessaire. Après six mois, les versions impaires (9, 11, etc.) ne sont plus supportées, les versions paires (10, 12, etc.) passent au statut _Active LTS_ et sont prêtes pour utilisation. Le statut de version _LTS_ signifie "long-term support", ce qui garantit généralement que tous les bugs critiques seront fixés pendant 30 mois. Les applications utilisées en prodution doivent utiliser uniquement les versions _Active LTS_ ou _Maintenance LTS_.
```

2023-03-14 09:55 UTC, ovflowd commented
Hey y'all, as we moved all translation efforts to Crowdin, we're closing this PR.

Please feel free to add your translations on Crowdin :)

Guide available on the repository `TRANSLATION.md`.

2023-03-14 09:55 UTC, closed without merging