doc: add diagnosis memory leak guide
nodejs/nodejs.org pull request #4590
Opened 2022-05-05 16:52 UTC by tony-go

Hi Node Familly 👋 

## Context

The Diagnostic Working Group started an [initiative](https://github.com/nodejs/diagnostics/issues/532) to re-assess the [diagnostics tools list](https://github.com/nodejs/node/blob/master/doc/contributing/diagnostic-tooling-support-tiers.md).

I start to work around the `--trace-gc` flag:
* add it to the list itself https://github.com/nodejs/node/pull/42346
* add tests https://github.com/nodejs/node/pull/42471

But something is missing... 😞 

If you take a look at the diagnostic tooling support tiers, you'll see that:
> The tool must have a guide or other documentation in the Node.js GitHub organization or website;

## Added

I propose to add a new guide to the existing collection 🆕. 

The guide is about how could we use built-in tools to diagnose memory leaks.

Here is a list of topics I hope this guide will help on:
* basics of garbage collection
* what is the purpose of `--trace-gc`? and how could we interpret the output?
* how to perform heap snapshot?
* how to compare heap snapshot with Chrome dev tool?

**⚠️ DISCLAIMER**: I voluntarily simplify garbage collection concepts (that I didn't master myself). I don't know If it's a good idea or not, please share your thoughts on that. Note that my initial intention was to provide an introductory guide more than a deep dive.

2022-05-05 17:22 UTC, tony-go commented
cc @nodejs/diagnostics

2022-05-05 17:35 UTC, nschonni commented on locale/en/docs/guides/diagnosis-memory-leak.md
> +1 - Create a new project
Looks like this might be an ordered list

2022-05-05 17:57 UTC, RafaelGSS requested changes
I think the initial idea of the diagnostics working group was to add those guides in https://github.com/nodejs/diagnostics to then elaborate a long guide to nodejs.org.

I feel we need to discuss it, first. What do you think?

I recommend you add it to the next diag-agenda. cc: @nodejs/diagnostics

2022-05-10 14:53 UTC, tony-go commented
Hey @RafaelGSS 👋 

Sorry, I was off the past week so I didn't answer quickly.

> I think the initial idea of the diagnostics working group was to add those guides in https://github.com/nodejs/diagnostics to then elaborate a long guide to nodejs.org.
> 
> I feel we need to discuss it. What do you think?
> 
> I recommend you add it to the next diag-agenda. cc: @nodejs/diagnostics

[This issue](https://github.com/nodejs/diagnostics/issues/554) is still in the agenda we could discuss it at the next meeting 🙌  My only concern about keeping stuff in diag repo is that visibility/accessibility is limited. I'd like to expose each piece of the puzzle as soon as it's ready.

2022-05-10 14:56 UTC, tony-go commented on locale/en/docs/guides/diagnosis-memory-leak.md
> +1 - Create a new project
🤦🏻‍♂️ Shame on me! I'll fix this ^^ nice catch.

2022-05-17 19:50 UTC, Szolcsy approved these changes

2022-06-07 19:02 UTC, tony-go commented
As discussed in the last diagnostics WG meeting, we'll close this issue and merge the content into the diagnostic repository.

2022-06-07 19:02 UTC, closed without merging