French: translate "knowledge"
nodejs/nodejs.org pull request #4647
Opened 2022-06-07 20:14 UTC by AugustinMauroy

# French: translate "knowledge"
This pull request translate all file "knowledge"

2022-06-08 13:30 UTC, Trott commented
@nodejs/nodejs-fr

2022-06-08 18:17 UTC, aduh95 reviewed
The original file contains outdated advices – `url.parse` is a legacy API that we no longer recommend now that Node.js ships the standard WHATWG `URL` API, so I’m not sure if we should merge this. 

Merci beaucoup pour la PR, la traduction semble de qualité, ma critique porte uniquement sur le fond du document original.

2022-06-08 18:21 UTC, aduh95 reviewed
Ca vaudrait le coût de split cette PR en plusieurs PR pour simplifier la review.

2022-06-08 20:09 UTC, AugustinMauroy commented
@aduh95 https://github.com/nodejs/nodejs.org/pull/4647#pullrequestreview-1000234936
je te laisse faire car je vois pas ce que tu veux dire. x'D
Je pense lancé à la trad de la doc.

2022-06-12 17:07 UTC, ACT-team-ytb approved these changes
@AugustinMauroy Je trouve que tu as encore fait une bonne traduction.

2022-06-12 17:08 UTC, AugustinMauroy commented
@ACT-team-ytb Oui merci.

2022-06-12 19:52 UTC, ACT-team-ytb requested changes
on écrirais pas http en maj?

2022-06-12 19:53 UTC, ACT-team-ytb commented
@AugustinMauroy  genre HTTP

2022-06-12 19:57 UTC, AugustinMauroy commented
@ACT-team-ytb Non cela n'est pas utiles.

2022-06-12 19:58 UTC, ACT-team-ytb approved these changes

2022-06-15 13:19 UTC, AugustinMauroy commented
@MaledongGit you can merge this pr

2022-06-16 09:19 UTC, MaledongGit approved these changes
Rubber stamp for me for someone has approved it.

2022-06-16 09:21 UTC, merged