French translation "download"
nodejs/nodejs.org pull request #4660
Opened 2022-06-16 12:55 UTC by AugustinMauroy

# French translation "download"
- [Translate package-manager.md](https://github.com/nodejs/nodejs.org/commit/7fd0635c98343d44ee0e1b60065a690df9b2a770)
- [Translate releases.md](https://github.com/nodejs/nodejs.org/commit/e3a3ad329e1295f3659aef1bc7cb344ac3177c29)

2022-06-17 00:57 UTC, MaledongGit commented
Ping @nodejs/nodejs-fr, plz have a review.

2022-06-17 19:36 UTC, kapouer commented on locale/fr/download/package-manager.md
> +* [Debian et Ubuntu baser sur des distributions Linux, Enterprise Linux/Fedora et Snap packages](#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages)
`[Distributions Linux dérivées de Debian et Ubuntu, Linux/Fedora Entreprise, et paquets Snap]`

2022-06-17 19:37 UTC, kapouer commented on locale/fr/download/package-manager.md
> +## Les distributions Linux basées sur Debian et Ubuntu, Enterprise Linux/Fedora et les paquets Snap
Même problème: Distribution *dérivées*

2022-06-17 19:38 UTC, kapouer commented on locale/fr/download/package-manager.md
> +Installez un paquetage binaire via [pkg](https://www.freebsd.org/cgi/man.cgi?pkg) :
Partout ailleurs il y a
package -> paquet

2022-06-17 19:59 UTC, kapouer requested changes

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +Pour installer Node.js 12.x à partir de la ligne de commande, exécutez la commande suivante en tant qu'utilisateur disposant de l'autorisation spéciale \*ALLOBJ :
J'ai un doute sur "authority" -> "autorisation".
C'est pas simplement "autorité"  ?

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +Sur les systèmes Unix / OS X, Node.js construit à partir des sources peut être installé en utilisant [nvm](https://github.com/creationix/nvm) en l'installant à l'emplacement attendu par nvm :
*un* (ou *le*) Node.js
ça rend la phrase plus claire

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +Les images SmartOS sont livrées avec pkgsrc pré-installé. Sur les autres distributions illumos, installez d'abord **[pkgsrc](https://pkgsrc.joyent.com/install-on-illumos/)**, puis vous pouvez install
Là encore, il faut mettre le "paquet" :)

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +Impliquez-vous pour télécharger le [Windows Installer](https://nodejs.org/en/#home-downloadhead) directement depuis le site web [nodejs.org](https://nodejs.org/).
Téléchargez simplement le [Windows Installer](...) directement...

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/releases.md
> +title: Communiqués antérieurs
Versions antérieures ?
Publications antérieures ?
Certainement pas communiqués en tous cas.

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/releases.md
> +modules: "<code>NODE_MODULE_VERSION</code> désigne le numéro de version ABI (application binary interface) de Node.js, utilisé pour déterminer les versions de Node.js dans lesquelles les binaires d'e
...dans lesquelles les extensions C++ compilées en binaires peuvent être chargées dans devoir être recompilées.

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/releases.md
> +Les versions 1.x à 3.x étaient appelées "io.js" car elles faisaient partie du fork io.js. A partir de Node.js 4.0.0, les anciennes versions de io.js ont convergé avec Node.js 0.12.x en versions unifi
Je trouve que dans ce cas là, "schisme" va bien à la place de "fork". Mais ce n'est pas une traduction officielle.

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +* [Debian et Ubuntu baser sur des distributions Linux, Enterprise Linux/Fedora et Snap packages](#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages)
[Distributions Linux dérivées de Debian et Ubuntu, Linux/Fedora Entreprise, et paquets Snap]

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +## Les distributions Linux basées sur Debian et Ubuntu, Enterprise Linux/Fedora et les paquets Snap
Même problème: Distribution dérivées

2022-06-17 19:59 UTC, kapouer commented on locale/fr/download/package-manager.md
> +Installez un paquetage binaire via [pkg](https://www.freebsd.org/cgi/man.cgi?pkg) :
Partout ailleurs il y a
package -> paquet

2022-06-19 14:35 UTC, AugustinMauroy commented on locale/fr/download/package-manager.md
> +Pour installer Node.js 12.x à partir de la ligne de commande, exécutez la commande suivante en tant qu'utilisateur disposant de l'autorisation spéciale \*ALLOBJ :
je pense que les deux se disse mais pour moi "autorisation" est le mieux dit moi ce que tu en pense

2022-06-19 14:37 UTC, AugustinMauroy commented on locale/fr/download/package-manager.md
> +Sur les systèmes Unix / OS X, Node.js construit à partir des sources peut être installé en utilisant [nvm](https://github.com/creationix/nvm) en l'installant à l'emplacement attendu par nvm :
On peut faire ça c'est vrais que la phrase est plus compréhensible.

2022-06-19 14:39 UTC, AugustinMauroy commented on locale/fr/download/package-manager.md
> +Impliquez-vous pour télécharger le [Windows Installer](https://nodejs.org/en/#home-downloadhead) directement depuis le site web [nodejs.org](https://nodejs.org/).
Je fait ça bonne idée

2022-06-19 14:40 UTC, AugustinMauroy commented on locale/fr/download/releases.md
> +title: Communiqués antérieurs
Release cela ne signifie pas  "Communiqués"?

2022-06-19 14:41 UTC, AugustinMauroy commented on locale/fr/download/releases.md
> +modules: "<code>NODE_MODULE_VERSION</code> désigne le numéro de version ABI (application binary interface) de Node.js, utilisé pour déterminer les versions de Node.js dans lesquelles les binaires d'e
Ok je change ça.

2022-06-19 14:41 UTC, AugustinMauroy commented on locale/fr/download/package-manager.md
> +Installez un paquetage binaire via [pkg](https://www.freebsd.org/cgi/man.cgi?pkg) :
OK

2022-06-19 14:41 UTC, AugustinMauroy commented on locale/fr/download/package-manager.md
> +## Les distributions Linux basées sur Debian et Ubuntu, Enterprise Linux/Fedora et les paquets Snap
Je change ca

2022-06-19 14:42 UTC, AugustinMauroy commented on locale/fr/download/package-manager.md
> +* [Debian et Ubuntu baser sur des distributions Linux, Enterprise Linux/Fedora et Snap packages](#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages)
ok

2022-06-24 22:39 UTC, AugustinMauroy commented
Finish

2022-06-24 22:40 UTC, ACT-team-ytb approved these changes

2022-06-30 05:16 UTC, MaledongGit commented
@kapouer ：Is it fine with you? If it's OK, I'll merge it.

2022-06-30 09:15 UTC, aduh95 approved these changes

2022-06-30 09:15 UTC, aduh95 commented on locale/fr/download/package-manager.md
> +***Note:*** Les paquets sur cette page sont maintenus et supportés par leurs mainteneurs respectifs, **non** par l'équipe centrale de Node.js. Veuillez signaler tout problème que vous rencontrez au m
```suggestion
***Note:*** Les paquets sur cette page sont maintenus et supportés par leurs mainteneurs respectifs, **non pas** par l'équipe centrale de Node.js. Veuillez signaler tout problème que vous rencontrez au mainteneur du paquet. S'il s'avère que votre problème est un bogue dans Node.js lui-même, le mainteneur signalera le problème en amont.
```

2022-06-30 09:15 UTC, aduh95 commented on locale/fr/download/releases.md
> +Les versions 1.x à 3.x étaient appelées "io.js" car elles faisaient partie du fork io.js. A partir de Node.js 4.0.0, les anciennes versions de io.js ont convergé avec Node.js 0.12.x en versions unifi
```suggestion
Les versions 1.x à 3.x étaient appelées "io.js" car elles faisaient partie du fork io.js. À partir de Node.js 4.0.0, les anciennes versions de io.js ont convergé avec Node.js 0.12.x en versions unifiées de Node.js.
```

2022-07-01 22:21 UTC, ACT-team-ytb approved these changes

2022-07-01 22:22 UTC, AugustinMauroy commented
@kapouer regard la tard si tout est bon

2022-07-07 04:23 UTC, merged