chore(gitignore): add .idea folder to .gitignore file
nodejs/nodejs.org pull request #5095
Opened 2023-03-09 13:36 UTC by EmirBoyaci

Fixes #5093

2023-03-09 15:24 UTC, AugustinMauroy commented on .gitignore
> +# JetBrains IDE
```suggestion
# IDE's Files
.idea/
.vscode/
```

2023-03-09 15:25 UTC, AugustinMauroy approved these changes
LGTM!

2023-03-09 23:20 UTC, Trott commented
I won't block this, but I would vastly prefer people add these kinds of things to their personal `.gitignore` files rather than to individual repositories. Every repository on the planet should not have to add every IDE's specific files (or `.DS_Store` files or....) But *you* should know about *your* IDE (and your operating system, in the case of `.DS_Store`). So you can put it in one place and solve the problem everywhere for yourself.

2023-03-10 05:27 UTC, EmirBoyaci commented
> I won't block this, but I would vastly prefer people add these kinds of things to their personal `.gitignore` files rather than to individual repositories. Every repository on the planet should not have to add every IDE's specific files (or `.DS_Store` files or....) But _you_ should know about _your_ IDE (and your operating system, in the case of `.DS_Store`). So you can put it in one place and solve the problem everywhere for yourself.

I understand what you’re mentioning but in the case some ppl had no idea to do that. I have global git config setup in my windows machine but didn’t do that for my mac machine. And to be honest, I forgot global git config. Because, when I did that I never touched again :D 
I am still thinking adding some kind of global folders/files to gitignore would make more sense to make contributing easily.

2023-03-10 12:09 UTC, ovflowd requested changes
Sadly I cannot approve this. I appreciate the intent, tho.

2023-03-10 12:13 UTC, EmirBoyaci commented
> Sadly I cannot approve this. I appreciate the intent, tho.

I totally understood their comments but I'm on the opposite side :D

2023-03-10 12:13 UTC, closed without merging