Update theme.tsx
nodejs/nodejs.org pull request #5269
Opened 2023-04-13 13:47 UTC by SpriteyOnTheDraconic

created a H component to handle the different heading updated the highlightAll and startLegacyApp calls in Content to use the useEffect hook updated the ThemeProps interface to include a more specific type for the frontMatter property in pageOpts

should improve the codes readability maintainability and safety

2023-04-13 13:48 UTC, SpriteyOnTheDraconic commented
I'm not the best But I think this could be good? if it's not atleast I tried Lol!

2023-04-13 20:15 UTC, manishprivet commented on theme.tsx
> +type HProps = React.PropsWithChildren<{
What is the purpose of this element? What problem does it solve?

2023-04-13 20:15 UTC, manishprivet commented on theme.tsx
> +  useEffect(() => {
This seems like you just re-formatted it

2023-04-13 20:15 UTC, manishprivet commented on theme.tsx
> -// @TODO: Nextra should provide better customization to FrontMatter Props
Why are we removing this here?

2023-04-14 09:33 UTC, ovflowd requested changes
These changes sadly bring no value. Also not sure what the H component is doing and why it is different.

This is very likely not going to land. Closing this PR.

2023-04-14 09:33 UTC, closed without merging