fix(i18n): translation key
nodejs/nodejs.org pull request #5347
Opened 2023-05-02 10:03 UTC by AugustinMauroy

2023-05-02 10:08 UTC, ovflowd commented on i18n/locales/en.json
> +  "components.section.newfooter.trademark": "Trademark Policy",
Name of the subfolder is `sections` not `section` 👀

2023-05-02 10:08 UTC, ovflowd commented on i18n/locales/en.json
>    "components.prevnextlink.next": "NEXT",
Could you also fix this one? I know it's unrelated, but I'd appreciate!

2023-05-02 12:51 UTC, ovflowd commented on components/Sections/NewFooter/index.tsx
> +          <FormattedMessage id="components.section.newFooter.about" />
You forgot to update the usage of `section` to `sections`. Again, be extra attentive when submitting changes...

2023-05-02 13:03 UTC, shanpriyan requested changes

2023-05-02 13:03 UTC, shanpriyan commented on i18n/locales/en.json
> +  "components.section.newFooter.trademark": "Trademark Policy",
```suggestion
  "components.sections.newFooter.trademark": "Trademark Policy",
```

Also update the key as `sections` in `NewFooter` component too (as ovflowd mentioned)

2023-05-03 05:55 UTC, shanpriyan approved these changes
LGTM!

2023-05-03 09:32 UTC, ovflowd approved these changes

2023-05-03 09:38 UTC, merged