Feat(toc): Introduce
nodejs/nodejs.org pull request #5375
Opened 2023-05-12 12:15 UTC by AugustinMauroy

## Description

Migration of table of contents from nodejs.dev but using nextra TOC

## Related Issues

#5242 

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [X] I've covered new added functionality with unit tests if necessary.

2023-05-12 14:44 UTC, Harkunwar commented on components/Article/TableOfContents/index.tsx
> +  if (!tableOfContents.length) {
```suggestion
  if (tableOfContents.length === 0) {
```
It's better to have positive checks than negations.

2023-05-12 14:52 UTC, Harkunwar commented on components/Article/TableOfContents/index.tsx
> +};
```suggestion
const traverseTableOfContents = (tableOfContents: PropsTableOfContents) => (
  <ul>
    {tableOfContents.map(item => (
      <li key={item.id}>
        <Link href={`#${item.id}`}>{item.value}</Link>
      </li>
    ))}
  </ul>
);

```
You don't need `return` statements. 


Also, can you convert this to a Component instead of a Function. It's considered a bad pattern.

2023-05-12 16:00 UTC, AugustinMauroy commented on components/Article/TableOfContents/index.tsx
> +};
Thanks for giving this advidce but on original component we have nested list.
I have to update the component

2023-05-12 18:06 UTC, AugustinMauroy commented on components/Article/TableOfContents/index.tsx
> +};
Now take a look, `return` is needed

2023-05-14 16:17 UTC, ovflowd commented on components/Article/TableOfContents/index.tsx
> +};
Why is return needed?

2023-05-14 16:22 UTC, AugustinMauroy commented on components/Article/TableOfContents/index.tsx
> +};
Look up the code now, you will have the answer 😁

2023-05-17 13:48 UTC, shanpriyan requested changes

2023-05-17 13:48 UTC, shanpriyan commented on components/Article/TableOfContents/index.tsx
> +const TableOfContents: FC<{ tableOfContents: PropsTableOfContents }> = ({
```suggestion
};

const TableOfContents: FC<{ tableOfContents: PropsTableOfContents }> = ({
```

2023-05-17 13:49 UTC, shanpriyan commented on components/Article/TableOfContents/index.tsx
> +};
@AugustinMauroy As Harkunwar mentioned this function can be changed to React component

2023-05-17 13:54 UTC, shanpriyan commented on components/Article/TableOfContents/index.tsx
> +};
I don't see a problem of using `return` here but if you really want to remove it you can change the following line
```diff
- {MappedTableOfContents.map(item => (
+ {parseTableOfContents(tableOfContents).map(item => (
```

2023-05-17 14:00 UTC, AugustinMauroy commented on components/Article/TableOfContents/index.tsx
> +};
Good idea !

2023-05-18 21:23 UTC, ovflowd commented
@AugustinMauroy the builds are failing, just as a fyi

2023-05-18 21:24 UTC, AugustinMauroy commented
I know it's from type

2023-05-22 06:12 UTC, mikeesto commented
Hi @AugustinMauroy . I think if you update the storybook snapshot now, the build will be successful

2023-05-22 08:25 UTC, AugustinMauroy commented
@mikeesto that an point but they are an other big part. It's typing of parsing function
BTW thanks

2023-05-22 09:00 UTC, ovflowd commented
@AugustinMauroy I didn't get your reply to @mikeesto could you rephrase?

2023-05-22 09:06 UTC, mikeesto commented
I think I understand now there. There are two issues: (1) Storybook snapshot needs updating, and (2) the types in `TableofContents/index.tsx` could be improved. This is how I would type it @AugustinMauroy . Feel free to take it as is or modify.

```tsx

type TableOfContentsNode = {
  depth: number;
  value: string;
  id: string;
  children?: TableOfContentsNode[];
  parent?: TableOfContentsNode | null;
};

type TableOfContentsProps = {
  tableOfContents: TableOfContentsNode[];
};

function parseTableOfContents(
  tableOfContents: TableOfContentsNode[]
): TableOfContentsNode[] {
  const parsedTableOfContents: TableOfContentsNode[] = [];

  function addChildNode(
    parent: TableOfContentsNode,
    node: TableOfContentsNode
  ) {
    if (!parent.children) {
      parent.children = [];
    }
    parent.children.push(node);
  }

  tableOfContents.forEach(node => {
    const { depth, value, id } = node;
    const parsedNode: TableOfContentsNode = { depth, value, id };

    let parentNode = parsedTableOfContents[parsedTableOfContents.length - 1];
    while (parentNode && parentNode.depth >= depth) {
      parentNode = parentNode.parent!;
    }

    if (parentNode) {
      addChildNode(parentNode, parsedNode);
    } else {
      parsedTableOfContents.push(parsedNode);
    }

    parsedNode.parent = parentNode || null;
  });

  return parsedTableOfContents;
}

const traverseTableOfContents: FC<TableOfContentsNode[]> = tableOfContents => (
  <ul>
    {parseTableOfContents(tableOfContents).map(item => (
      <li key={item.id}>
        <Link href={`#${item.id}`}>{item.value}</Link>
        {item.children && traverseTableOfContents(item.children)}
      </li>
    ))}
  </ul>
);

const TableOfContents: FC<TableOfContentsProps> = ({ tableOfContents }) => {
  if (tableOfContents.length === 0) {
    return null;
  }
  return (
    <details className={styles.tableOfContents}>
      <summary>
        <strong>
          <FormattedMessage id="components.article.tableOfContents" />
        </strong>
      </summary>
      {traverseTableOfContents(tableOfContents)}
    </details>
  );
};
```

2023-05-22 09:19 UTC, AugustinMauroy commented
@mikeesto Yep i will test you code. Thanks 😄!

2023-05-24 13:37 UTC, closed without merging

2023-05-24 13:38 UTC, ovflowd commented
**FYI:** We deleted the `major/website-redesign` branch to simplify our release and rollout process. Please feel free to recreate this PR or reopen it with the `main` branch as a target.

Thank you, and we apologise for the inconvenience!