Feat(download header): introduce
nodejs/nodejs.org pull request #5401
Opened 2023-05-24 13:47 UTC by AugustinMauroy

## Description

Introduce DownloadHeader form nodejs.dev

## Related Issues

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [X] I've covered new added functionality with unit tests if necessary.

2023-05-28 10:10 UTC, AugustinMauroy commented
They are big conflict here I will fix that

2023-06-14 12:03 UTC, ovflowd requested changes
I think we need to wait for @HinataKah0 PR about Node Release data to be merged first before we can proceed here.

You will probably need to rebase and change how you're doing the PR.

Code-wise it looks okay-ish, but I foresee a lot of changes needed because of @HinataKah0's PR.

2023-06-14 12:26 UTC, AugustinMauroy commented
I fully assume what there is to do about nodejs data.

2023-06-29 21:17 UTC, ovflowd commented
@AugustinMauroy a lot of unrelated changes here 🤔 can we recreate the branch maybe?

2023-06-29 21:19 UTC, ovflowd commented on components/Downloads/DownloadHeader/index.module.scss
> +    @media (max-width: 500px) {
Don't we have now shared media tags for mobile devices?

2023-06-29 21:20 UTC, ovflowd commented on components/Downloads/DownloadHeader/index.tsx
> +type DownloadHeaderProps = {
This could be one-line? `type DownloadHeaderProps = { release: NodeRelease; };`

2023-06-29 21:21 UTC, ovflowd commented on components/Downloads/DownloadHeader/index.tsx
> +        <SectionTitle
IMHO SectionTitle should support the array items to be React Elements too, not just strings.

You could update the type of `SectionTitle` and then pass a `<FormattedMessage>` here. And remove the `useIntl`.

2023-07-01 07:17 UTC, HinataKah0 commented on components/Downloads/DownloadHeader/index.tsx
> +const DownloadHeader: FC<DownloadHeaderProps> = ({ release }) => {
```suggestion
const DownloadHeader: FC<NodeRelease> = ({ versionWithPrefix, isLts, npm }) => {
```
Don't forget to let prettier fix the formatting :)

2023-07-05 00:33 UTC, mikeesto commented on components/Downloads/DownloadHeader/index.stories.tsx
> +console.log(createNodeReleases());
```suggestion

```

2023-07-05 00:39 UTC, mikeesto commented on public/blog-posts-data.json
> +{"pagination":[2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023],"categories":["announcements","community","feature","module","npm","release","uncategorized","video","vulnerability","
This file shouldn't be in the diff. You might be missing the pre-commit hooks on your branch?

2023-07-05 00:39 UTC, mikeesto commented on public/node-releases-data.json
> +[{"major":20,"version":"20.3.1","codename":"","currentStart":"2023-04-18","ltsStart":"2023-10-24","maintenanceStart":"2024-10-22","endOfLife":"2026-04-30","npm":"9.6.7","v8":"11.3.244.8","releaseDate
Same with this file

2023-07-05 12:00 UTC, bmuenzenmeyer commented on components/Common/SectionTitle/index.tsx
> +          <span className={styles.active} key={index}>
smal nit that I even mistake sometimes: `index` should not be used as a key  - see https://react.dev/learn/rendering-lists#why-does-react-need-keys the pitfall section for more info.

it'd be better if `item` was retained in some way. I didn't run this to see if it's a complex object or only text- but we do need to get it down to a string

(and below)

2023-07-27 12:27 UTC, closed without merging