feat: migrate download toggle component
nodejs/nodejs.org pull request #5407
Opened 2023-05-24 21:30 UTC by araujogui

## Description

Migrate `DownloadToggle` component

## Related Issues

Related to #5303 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [x] I've covered new added functionality with unit tests if necessary.

2023-05-25 07:48 UTC, AugustinMauroy commented on components/Downloads/DownloadToggle/index.tsx
> +const DownloadToggle = ({
You should use FC ref: "contribution guideline"

2023-05-30 20:58 UTC, shanpriyan submitted a review, later dismissed

2023-05-30 20:58 UTC, shanpriyan commented on i18n/locales/en.json
> +  "components.downloadToggle.current": "Current",
keys should be as per  [translation guidelines](https://github.com/nodejs/nodejs.org/blob/572c1edd3eaaf32c6f803894ad54b9e4b219110d/TRANSLATION.md?plain=1#L48)
```suggestion
  "components.downloads.downloadToggle.current": "Current",
```

2023-06-09 00:39 UTC, mikeesto requested changes

2023-06-09 00:39 UTC, mikeesto commented on .eslintjscache
> +[{"/Users/araujo/Documents/Projects/nodejs.org/components/AnchoredHeading.tsx":"1","/Users/araujo/Documents/Projects/nodejs.org/components/Api/DataTag/index.stories.ts":"2","/Users/araujo/Documents/P
Can you please remove this file from the PR?

2023-06-09 00:39 UTC, mikeesto commented on .eslintmdcache
> +[{"/Users/araujo/Documents/Projects/nodejs.org/CODE_OF_CONDUCT.md":"1","/Users/araujo/Documents/Projects/nodejs.org/COLLABORATOR_GUIDE.md":"2","/Users/araujo/Documents/Projects/nodejs.org/CONTENT_VS_
Same with this one

2023-06-09 15:39 UTC, ovflowd commented
@araujogui could you check those files that @mikeesto mentioned? 👀

2023-06-12 00:54 UTC, mikeesto approved these changes
LGTM, thanks

2023-06-12 07:32 UTC, aymen94 approved these changes

2023-06-12 15:06 UTC, merged