chore: updated english to use en-GB locale
nodejs/nodejs.org pull request #5485
Opened 2023-07-09 09:23 UTC by ovflowd

## Description

This PR introduces a simple `Time` component that fulfils the specification presented on the issue.

## Related Issues

Fixes #5481

2023-07-09 13:19 UTC, AugustinMauroy requested changes
You are recoding an fonctionnality of react-intl (formattedDate)

2023-07-09 13:43 UTC, ovflowd commented
> You are recoding an fonctionnality of react-intl (formattedDate)

I'm not. Why do you think this component is reimplementing existing functionality from `react-intl`?

2023-07-09 14:00 UTC, ovflowd commented
I'm updating this PR to use `FormattedDate`, and I want to clarify that we're not "redoing/reimplementing" existing functionality. It's often more beneficial to utilize Native JavaScript APIs instead of relying on sugarcoated components.

Additionally, it's important to note that the `Time` component acts as a "wrapper" for HTML's `time` element. It doesn't replace `react-intl`'s Date & Time Components, which return a plain JSX-string.

I'm providing these explicit details to ensure you understand why your assessment may not be accurate, even though using `FormattedDate` makes sense in this case.

2023-07-10 01:44 UTC, mikeesto approved these changes

2023-07-10 01:44 UTC, mikeesto commented on components/Common/Time/index.tsx
> +  const { isoDate, formatedDate } = useMemo(() => {
```suggestion
  const { isoDate, formattedDate } = useMemo(() => {
```

2023-07-10 01:44 UTC, mikeesto commented on components/Common/Time/index.tsx
> +      formatedDate: dateObject.toLocaleString(currentLocale.hrefLang, {
```suggestion
      formattedDate: dateObject.toLocaleString(currentLocale.hrefLang, {
```

2023-07-10 01:44 UTC, mikeesto commented on components/Common/Time/index.tsx
> +  return <time dateTime={isoDate}>{formatedDate}</time>;
```suggestion
  return <time dateTime={isoDate}>{formattedDate}</time>;
```

2023-07-10 15:21 UTC, closed without merging