Improvement banner#5510
nodejs/nodejs.org pull request #5518
Opened 2023-07-14 17:28 UTC by BahugunaSaumya

Description
A Fix to Improvement: Banner issue [5510](https://github.com/nodejs/nodejs.org/issues/5510)
mostly all the changes are committed but changes are as follows:-
Added a div to the react component and added a class called banner content to make the div centred and add the banner background to it.

Newer:- Changed the colour of the button matched values with the Figma prototype
added all the changes mentioned in the above comment except the button size increase

One thing to review:- I tried fitting the banner by 100% to the sides but due to padding put by StoryBook div, I had to put a margin = -1 in the banner which helped solve the issue but I am not sure if it is the sustainable solution, so can you have a quick look and let me know if I need to change that - [It is in index. module.scss, line 8 , inside.banner class](https://github.com/BahugunaSaumya/nodejs.org/blob/237f5c5773a8e9ae1db082a35460b40beca5c177/components/Common/Banner/index.module.scss#L8)

Related Issues
Check List
 I have read the Contributing Guidelines and made commit messages that follow the guideline.
 I have run npx turbo lint to ensure the code follows the style guide. And run npx turbo lint:fix to fix the style errors if necessary.
 I have run npx turbo format to ensure the code follows the style guide.
 I have run npx turbo test to check if all tests are passing, and/or npx turbo test:snapshot to update snapshots if I created and/or updated React Components.
 I've covered new added functionality with unit tests if necessary.

2023-07-17 16:31 UTC, BahugunaSaumya commented
Hey, Is there anything wrong or something different than what you had in your mind in my PR?

2023-07-17 16:42 UTC, ovflowd commented
The font size is wrong. It should be 14px and not 18px. Also, the height should be `3rem` (`var(--line-height-subheading)`)

You also manually set the colour property of the text, which is wrong. It would be best if you used the variables. Otherwise, on the dark theme, the colour looks completely wrong. Also, the colour on the hover should not be `var(--color-fill-app)` otherwise, on dark the hover also feels incorrect.

2023-07-17 22:22 UTC, ovflowd commented on components/Common/Banner/index.module.scss
> +    font-family: --var(--sans);
This line should be removed.

2023-07-17 22:24 UTC, ovflowd reviewed
Overall there are many styles that are repeated or improper/should be removed. I would recommend to please cleanup some of these styles if possible.

Also, the font-size is wrong. 1rem is way too small. Please try to check other font-size variables that we have that better match what would 14px look like :)

2023-07-20 20:31 UTC, ovflowd commented on components/Common/Banner/index.module.scss
> +      height: var(--space-32);
No need to have a height actually, it calculates by itself correctly already

2023-07-20 20:32 UTC, ovflowd commented on components/Common/Banner/index.module.scss
> +      width: var(--space-92);
This variable `--space-92` does not exist. Also no need to have a width setting here

2023-07-21 04:52 UTC, mikeesto commented
@BahugunaSaumya Do you need to update the snapshots? I ran the PR checks for you and storybook tests are not passing atm

2023-07-21 07:36 UTC, BahugunaSaumya commented
Hey Michael,


I ran it but it just says remote cachin disabled,




![Screenshot_20230721-083600~2.jpg](https://github.com/nodejs/nodejs.org/assets/91420676/fdba179c-b705-4cf0-ae2d-c75935fb20e6)

2023-07-23 01:13 UTC, mikeesto commented
@BahugunaSaumya If you run prettier now, that should fix up the formatting in `components/Common/Banner/index.module.scss` and then hopefully we can land this

2023-07-23 13:36 UTC, ovflowd approved these changes
LGTM! Thank you for your first contribution! Super appreciate the effort put into this! 🙇

2023-07-23 13:40 UTC, ovflowd requested changes
FYI I've just noticed the DOM Validation fails on the UNIT tests.

Apparently, you have `p` elements inside other `p` elements. This is happening in this test `components/Common/Banner/__tests__/index.test.tsx`

I would say the Banner should be a `div` element and not a paragraph element. So if you can revert the `p` change that be great!

2023-07-23 13:59 UTC, BahugunaSaumya commented
I've done that now, thankyou for the help

2023-07-23 14:01 UTC, ovflowd commented
> I've done that now, thankyou for the help

Did you also update the snapshots after changing the tags? 👀

2023-07-23 14:12 UTC, BahugunaSaumya commented
Yes I did that this time :-)

2023-07-23 15:18 UTC, BahugunaSaumya reviewed
https://github.com/nodejs/nodejs.org/pull/5518#pullrequestreview-1542254270 Done that now

2023-07-23 15:26 UTC, BahugunaSaumya commented
https://github.com/nodejs/nodejs.org/pull/5518#pullrequestreview-1542254270 finished that

2023-07-23 15:47 UTC, ovflowd approved these changes

2023-07-23 15:48 UTC, merged