fix: correct matcher
nodejs/nodejs.org pull request #5604
Opened 2023-08-03 19:48 UTC by balazsorban44

## Description

The Next.js Middleware did not correctly export a matcher. There is no top-level export of `matcher`.

Based on https://github.com/nodejs/nodejs.org/blob/625b2ab787271daa6946a7d88cb57cbbf9cf445c/middlewares/detectLanguage.ts#L47 you only want to run Middleware for the index page. This PR ensures that Middleware is not invoked unnecessarily to other pages.

## Validation

Refer to the Next.js docs: https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

2023-08-03 19:52 UTC, balazsorban44 commented on middleware.ts
> +export const config = { matcher: ["/"] };
Note, this cannot be a re-export so its value can be statically analyzed:

From the [Next.js docs](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher):
> Good to know: The matcher values need to be constants so they can be statically analyzed at build-time. Dynamic values such as variables will be ignored.

2023-08-03 20:54 UTC, ovflowd requested changes
Sorry, but I aint going to approve this change. I understand that this enables the static analysis at build-time, but this PR doesn't fix any issue, actually, it breaks the custom "middleware" matching we've introduced.

The whole point of the `createMiddleware` is allowing us to merge multiple middlewares or have one or more. Since very unfortunately, Next.js does not support more than one middleware.

2023-08-03 20:58 UTC, ovflowd commented
Let me know if there are any alternatives or if this change is required for well, route matching to work at all, and if that's the case, I still cannot approve this PR without a solution that would allow us to have more than one matcher, or a matcher that comes from our "custom" middleware creator.

(I'm genuinely all fine with any change on the custom setup, if you feel like it, you can completely refactor this code in a way that makes you happy or that solves our issues 🙇)

Now, suppose there's no possibility at all to have something similar to what we're designing. In that case, I'd request the change to altogether remove our custom middleware engine and simply apply the only middleware we have now. (And I'd request pretty please for Vercel to consider supporting multiple middlewares)

2023-08-04 23:09 UTC, ovflowd commented
@balazsorban44 a quick question, since the matcher is ignored, does that mean the middleware runs for every route?

Wouldn't https://nextjs.org/docs/app/building-your-application/routing/middleware#conditional-statements conditional statements still apply here? Because the docs say this: 
![image](https://github.com/nodejs/nodejs.org/assets/12037269/cd2a724e-d05c-4891-a849-8b3698562f60)

So would we still get "billed" (aka the middleware run, even if there are these conditional statements)?

2023-08-08 20:47 UTC, ovflowd commented
Hey @styfle sorry for pinging you! Not sure if @balazsorban44 has been busy lately. Do you have any extra insights here?

2023-08-08 21:02 UTC, balazsorban44 commented
> @balazsorban44 a quick question, since the matcher is ignored, does that mean the middleware runs for every route?
> 
> Wouldn't https://nextjs.org/docs/app/building-your-application/routing/middleware#conditional-statements conditional statements still apply here? Because the docs say this: 
> ![image](https://github.com/nodejs/nodejs.org/assets/12037269/cd2a724e-d05c-4891-a849-8b3698562f60)
> 
> So would we still get "billed" (aka the middleware run, even if there are these conditional statements)?


Sorry, haven't seen this before.

When you have a conditional statement within the Middleware code, it's still going to run for the Route, you can just choose to not do execute any logic by returning early.

The matcher config is the one that can determine on the platform (like Vercel) when the Middleware should be skipped. This configuration needs to be static so it's predictable at build-time.

2023-08-08 21:17 UTC, styfle commented
> I legit see a huge amount of invocations on the Edge Middleware and I wonder if (by any chance) this would alleviate it?

Yes, it would reduce middleware invocations. Thats why the `matcher` needs to be statically analyzable, because its not invoked at runtime like the current implementation you're using.

[Learn more](https://vercel.com/docs/concepts/functions/edge-middleware/middleware-api#match-paths-based-on-custom-matcher-config)

2023-08-08 21:20 UTC, ovflowd commented
> > I legit see a huge amount of invocations on the Edge Middleware and I wonder if (by any chance) this would alleviate it?
> 
> Yes, it would reduce middleware invocations. Thats why the `matcher` needs to be statically analyzable, because its not invoked at runtime like the current implementation you're using.
> 
> [Learn more](https://vercel.com/docs/concepts/functions/edge-middleware/middleware-api#match-paths-based-on-custom-matcher-config)

Ty. I've read that documentation, some parts are kinda confusing, hence I thought that dynamic matching was going to work due to making rules during the invocation. Anyhow, can you review this PR? https://github.com/nodejs/nodejs.org/pull/5613

2023-08-08 21:23 UTC, styfle commented
@ovflowd Just to be clear, you only want middleware to run on the homepage (`/`) and not on other pages, correct?

2023-08-08 21:24 UTC, ovflowd commented
> @ovflowd Just to be clear, you only want middleware to run on the homepage (`/`) and not on other pages, correct?

Yup, at least for that one.

2023-08-08 22:27 UTC, ovflowd commented
Closing due to https://github.com/nodejs/nodejs.org/pull/5613

2023-08-08 22:27 UTC, closed without merging