add scorecard pipeline
nodejs/nodejs.org pull request #5660
Opened 2023-08-22 10:25 UTC by UlisesGascon

Refs: https://github.com/nodejs/nodejs.org/issues/5659

2023-08-22 10:34 UTC, ovflowd requested changes
Why do we need to run this on the Website codebase? Shouldn't this be executed against nodejs/node?

2023-08-22 10:40 UTC, AugustinMauroy commented
@ovflowd it's scorecard of this repo so we need an action to analyse the code and output the score 😄

2023-08-22 10:42 UTC, ovflowd commented
Sorry, but we don't need a GitHub Action in this repository to have the scorecard analysed here.

This is a simple GitHub Action. It can be done anywhere else. And I rather have this on the Security WGs repository.

Also, @AugustinMauroy I'm asking @UlisesGascon's feedback here, not yours. (Please avoid answering on behalf of the PR author)

2023-08-22 10:50 UTC, ovflowd commented
Note that Im happy to be proven wrong, and to understand why we might need this 🤔

2023-08-22 11:00 UTC, UlisesGascon commented
> Why do we need to run this on the Website codebase? Shouldn't this be executed against nodejs/node?

Yep @AugustinMauroy is correct here. Let me explain in more in details: 

The `nodejs/nodejs.org` repository has also a scoring, actually all the repositories in the org have them. There are two ways on how the Scorecard data is updated:
1. CRON: basically the OpenSSF runs a massive CRON job and pull the most relevant repositories from Github and execute the analysis.
2. Voluntary notification: The projects will proactively build the SARIF and upload it to the Github Dashboard.

While the CRON way is great for exploratory and build a great idea of the ecosystem for the community and the OpenSSF, it is not a reliable for us due the way we are monitoring the changes and the evolution of all the repos at organization level.

> This is a simple GitHub Action. It can be done anywhere else. And I rather have this on the Security WGs repository.

Until now, we had included in each repository that we actively monitored (we are increasing the scope now):
- [nodejs/undici](https://github.com/nodejs/undici/blob/main/.github/workflows/scorecard.yml)
- [nodejs/node](https://github.com/nodejs/node/blob/main/.github/workflows/scorecard.yml)

And even for some Node dependencies as well:
- [ada-url/ada](https://github.com/ada-url/ada/blob/main/.github/workflows/scorecard.yml)

The pipeline itself is quite simple, with a single dependency that doesn't require maintenance (dependabot will manage the upgrades) and it runs as a cron job, so it won't affect the current workflow of the team (even if fails).

2023-08-22 11:11 UTC, ovflowd commented
> Yep @AugustinMauroy is correct here. Let me explain in more in details:

Never said he isn't.

2023-08-22 11:12 UTC, ovflowd commented
> While the CRON way is great for exploratory and build a great idea of the ecosystem for the community and the OpenSSF, it is not a reliable for us due the way we are monitoring the changes and the evolution of all the repos at organization level.

Gotcha. Ack that. That's good reasoning enough for me. If this is a limitation, and it is per design that individual repositories should run that, then that's fine by me.

2023-08-22 11:13 UTC, ovflowd commented on .github/workflows/scorecards.yml
> +        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d # v2.0.6
Whitelisted the Action

2023-08-22 11:13 UTC, ovflowd commented
FYI file has linting issues, @UlisesGascon

2023-08-26 14:08 UTC, UlisesGascon commented on .github/workflows/scorecards.yml
> +        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d # v2.0.6
Thanks!

2023-08-26 14:08 UTC, UlisesGascon commented
linting issues resolved in fb9829f

2023-08-29 15:11 UTC, ovflowd approved these changes

2023-08-29 15:15 UTC, merged