add codeql pipeline
nodejs/nodejs.org pull request #5663
Opened 2023-08-22 10:26 UTC by UlisesGascon

Refs: https://github.com/nodejs/nodejs.org/issues/5659

2023-08-22 10:31 UTC, ovflowd requested changes
We already have CodeQL enabled by default.

2023-08-22 10:42 UTC, UlisesGascon commented
> We already have CodeQL enabled by default.

Even if is enabled, it is recommended to include the pipeline.

![Captura de pantalla 2023-08-22 a las 12 40 21](https://github.com/nodejs/nodejs.org/assets/5110813/f34d27fe-c372-4bca-bb9a-34dabe25908c)

_[Current warnings](https://github.com/nodejs/nodejs.org/security/code-scanning/tools/CodeQL/status)_

2023-08-22 10:43 UTC, ovflowd commented
Gotcha. That makes sense. Can you add the missing EOF line?

2023-08-22 10:46 UTC, ovflowd commented on .github/workflows/codeql.yml
> +        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
I've whitelisted this Action.

2023-08-22 10:47 UTC, ovflowd commented
@UlisesGascon can you checkout your branch locally and fix the linting issues?

2023-08-26 14:10 UTC, ovflowd approved these changes

2023-08-26 14:11 UTC, ovflowd commented
Seems like CodeQL is failing.

2023-08-26 14:28 UTC, UlisesGascon commented
I am researching about [the error](https://github.com/nodejs/nodejs.org/actions/runs/5985234979/job/16237142971):

> Error: Code Scanning could not process the submitted SARIF file:
> CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled

Seems like there is a misconfiguration. Maybe is related to https://github.com/github/codeql-action/issues/1528. 

Current config in Security tab 🤔 

![Captura de pantalla 2023-08-26 a las 16 25 41](https://github.com/nodejs/nodejs.org/assets/5110813/a4971d04-7368-473f-bc25-b15b1bc11f50)

2023-08-31 20:18 UTC, ovflowd commented
@UlisesGascon are you going to fix this PR?

2023-09-07 07:54 UTC, aymen94 approved these changes

2023-09-25 13:09 UTC, ovflowd commented
I'm closing this as a stale PR. Please feel free to reopen at your convenience.

2023-09-25 13:09 UTC, closed without merging