Style: Added inline code styling
nodejs/nodejs.org pull request #5952
Opened 2023-10-02 14:32 UTC by akhilender-bongirwar

## Description
In this commit, I've implemented inline code block styling according to the Figma design.

Changes Made:
- Created `styles/new/base.css` and added styling for code blocks in light mode.
- Created `styles/new/layout/dark-theme.css` and added styling for code blocks in dark mode.
- Created `variables.css` to declare variables.

For these changes, I followed the existing file structure in the `styles/old` folder.

## Validation
Fixes #5934 

## Related Issues

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [ ] I've covered new added functionality with unit tests if necessary.

2023-10-02 15:02 UTC, ovflowd requested changes
Please read our Collaborator Guidelines. We don't do manual CSS here as we use Tailwind.

Tailwind has already all the font sizes, colours, spacings, font sizes, spacing and etc.

You might only need to update `tailwind` config by adding the font families for the inline code.

You might want to follow Tailwind's guide for adding new font-families (ie, you need to update `.storybook/preview.tsx` with the IBM Plex Mono font and also `tailwind.config`

Not to mention you forgot to add the Storybooks here.

2023-10-03 10:00 UTC, akhilender-bongirwar commented
@ovflowd, my apologies for not having read the Collaborator Guidelines previously. I have now adhered to the guidelines by using only Tailwind CSS classes for styling. Additionally, could you please provide guidance on how to add storybooks here?

2023-10-03 10:10 UTC, ovflowd commented
> Additionally, could you please provide guidance on how to add storybooks here?

You mentioned you read the Collaborator Guides, if you did, you would know how to. It's all written there.

2023-10-03 10:11 UTC, ovflowd commented on styles/new/base.css
> +code {
```css
code {
  @apply font-mono 
    text-base 
    font-semibold 
    text-neutral-900;
}
```

2023-10-03 10:14 UTC, ovflowd commented on styles/new/layout/dark-theme.css
That's not the way of doing dark theming. Read https://tailwindcss.com/docs/dark-mode

You simply add `dark:` as a prefix for the dark things.

Also, you don't need to define again `text-base`, `font-semibold` and all of the other things already set on the base styles. You only need to add on base.css `dar:text-white` (I'd recommend you to give a better read on how CSS works).

Also, inline code should have a background colour and a border-radius and I'm not seeing here.

2023-10-03 10:14 UTC, ovflowd commented on tailwind.config.ts
> +      mono: ['var(--font-ibm-plex-mono)'],
This should be called 'ibm-plex-mono'

```suggestion
      'ibm-plex-mono': ['var(--font-ibm-plex-mono)'],
```

2023-10-03 14:56 UTC, ovflowd commented on styles/new/base.css
> +   dark:bg-neutral-900
The `dark` styles need to be indented (extra space) too 👀

2023-10-03 14:56 UTC, ovflowd commented on components/__design__/text.stories.tsx
> +export const Code: StoryObj = {
```suggestion
export const InlineCode: StoryObj = {
```

2023-10-03 15:00 UTC, ovflowd approved these changes
Everything seems alright! Thanks for making this contribution and for making the updates based on feedback! Appreciate it!

I'm just verifying the Stories now, but afaik it looks alright!

2023-10-03 15:01 UTC, ovflowd commented
> NextFontError: Preload is enabled but no subsets were specified for font `IBM Plex Mono`. Please specify subsets or disable preloading if your intended subset can't be preloaded.
Available subsets: `cyrillic`, `cyrillic-ext`, `latin`, `latin-ext`, `vietnamese`

FYI apparently there is missing a subset setting on the font https://nextjs.org/docs/messages/google-fonts-missing-subsets can you set the subset as `latin`?

2023-10-03 17:43 UTC, akhilender-bongirwar commented
> > NextFontError: Preload is enabled but no subsets were specified for font `IBM Plex Mono`. Please specify subsets or disable preloading if your intended subset can't be preloaded.
> > Available subsets: `cyrillic`, `cyrillic-ext`, `latin`, `latin-ext`, `vietnamese`
> 
> FYI apparently there is missing a subset setting on the font https://nextjs.org/docs/messages/google-fonts-missing-subsets can you set the subset as `latin`?

Should I even add display: 'fallback' with subsets:['latin'] ? // @ovflowd

2023-10-03 19:48 UTC, ovflowd approved these changes

2023-10-03 19:52 UTC, AugustinMauroy approved these changes
SGTM ç

2023-10-04 05:25 UTC, akhilender-bongirwar commented
> Everything seems alright! Thanks for making this contribution and for making the updates based on feedback! Appreciate it!
> 
> I'm just verifying the Stories now, but afaik it looks alright!

@ovflowd, I wanted to express my gratitude for your support. Initially, I felt overwhelmed working on a large repository, but I'm actively learning how to collaborate effectively within well-structured projects. Your guidance and assistance have been invaluable, and I appreciate it greatly. Thank you for your patience and encouragement in my learning journey.

2023-10-04 07:40 UTC, ovflowd commented
> > Everything seems alright! Thanks for making this contribution and for making the updates based on feedback! Appreciate it!
> > I'm just verifying the Stories now, but afaik it looks alright!
> 
> @ovflowd, I wanted to express my gratitude for your support. Initially, I felt overwhelmed working on a large repository, but I'm actively learning how to collaborate effectively within well-structured projects. Your guidance and assistance have been invaluable, and I appreciate it greatly. Thank you for your patience and encouragement in my learning journey.

It can be overwhelming, yes. Hopefully, our docs were good enough.

2023-10-04 07:50 UTC, merged