feat: create CodeBox component which fixes issue #5819
nodejs/nodejs.org pull request #6019
Opened 2023-10-17 12:38 UTC by fa-901

## Description

Created a CodeBox component as per the requirements in #5819. 
Added translations where necessary. Captured the 3 necessary mentioned states in Storybook

## Validation
Screenshots below
![image](https://github.com/nodejs/nodejs.org/assets/19715103/266fa971-8967-4914-8855-691d3369484b)
![image](https://github.com/nodejs/nodejs.org/assets/19715103/91e6b7a7-5162-4d49-b7e8-1e67a5554416)

## Related Issues
Addresses issue [5819](https://github.com/nodejs/nodejs.org/issues/5819)

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

2023-10-17 18:53 UTC, ovflowd commented
The Screenshots above look far differently from the Figmas

2023-10-17 18:57 UTC, ovflowd commented on components/Common/CodeBox/index.tsx
This is extremely and completely wrong.

The Codebox component should only wrap the actual Code Element; Meaning the Codebox component should not do anything regarding syntax highlighting, nor invoke shiki.

Shiki is already automatically invoked on real world Application within [here](https://github.com/nodejs/nodejs.org/blob/main/next.dynamic.mjs#L172).

Meaning that you shouldn't do any of this here.

Hence the children of this Component should be something that MDX provides. Hence for testing purposes (Storybook) you could simply call the MDX parser on a certain MDX snippet with the plugin mentioned on the line above.

Anything else shouldn't be done here.

2023-10-17 18:58 UTC, ovflowd requested changes
As this implementation is entirely wrong, I'm requesting changes. Part of the implementation is well-natured, but I believe we didn't explain the ask well enough.

Anyhow, I'd appreciate it if you check how current syntax highlighting works on the website and follow the instructions below.

2023-10-17 19:07 UTC, ovflowd commented on components/Common/CodeBox/index.tsx
In other words, this Component should be connected with what MDX provides you.  (You need actually to see what the props are).

It's essential to mention that MDX will only provide you one Snippet for all the languages you want.

I think that the implementation of this Component in general, is extremely complex due to:

- It's children must be precisely what MDX provides you
- Multiple Languages might come from a single snippet, and we need to be able to handle that

@bmuenzenmeyer I wish we had a sync before creating the Codebox issue because the multiple language part is tricky. Even more, knowing that the current API docs (do two different snippets https://github.com/nodejs/node/blob/main/doc/api/crypto.md) that are then merged during tooling/build. But on nodejs.dev we simplified that by merging both snippets into one https://github.com/nodejs/nodejs.dev/blob/main/content/api/v20/crypto.en.md

So it is a complex question now how we should handle it here. Knowing that the Codebox component will be passed directly to `MDXPRovider`, MDX will provide the arguments to the Component by itself.

Otherwise, we might have two Codebox components. A generic one that works similarly to this one, which receives regular props. And then one wired up for MDX that pretty much wraps this one.

Still, all the actual syntax highlighting is done by MDX itself (with the `rehype-pretty-code` plugin, meaning regardless of the MDX-directly-wired Codebox and the one that received regular props. The content of the Codebox itself should be a `React.ReactNode` that expects to already be highlighted.

2023-10-18 00:29 UTC, bmuenzenmeyer commented on components/Common/CodeBox/index.tsx
@ovflowd I did ping you in https://github.com/nodejs/nodejs.org/issues/5819#issuecomment-1728510131 but I think it got lost in the shuffle of GHC and hacktoberfest. Want to have a call later this week?

@fa-901 sorry for leading you a bit astray here

2023-10-18 00:39 UTC, bmuenzenmeyer commented on components/Common/CodeBox/index.tsx
ah yes, even a cursory read of https://github.com/nodejs/nodejs.org/pull/5713/files reveals my mistake.

2023-10-18 15:01 UTC, ovflowd commented on components/Common/CodeBox/index.tsx
> Want to have a call later this week?

I also somehow didn't get a notification about this 🙈 but sure!

2023-10-18 15:02 UTC, ovflowd commented on components/Common/CodeBox/index.tsx
Also @fa-901 I apologise for my strong tone here. I hope you don't feel less motivated on working in this task!

It's just a super tricky one (probably one of the most complex ones) and requires me and @bmuenzenmeyer to actually provide way more docs and come up with a plan.

2024-01-04 11:05 UTC, closed without merging