feat: nextjs and mdx compiler
nodejs/nodejs.org pull request #6071
Opened 2023-10-31 01:25 UTC by ovflowd

## Description

This PR does a significant rework on our MDX Parsing and updates Next.js to v14 and MDX to v3.

### Motivation

We used a 3rd party package to parse `mdx` with source strings, aka, `next-mdx-remote` "maintained" by Hashicorp. But as it became more apparent that we don't need a 3rd party solution and we can use a lightweight solution, I've decided to use the core of MDX itself `@mdxjs/mdx` without any extra sugar etc.

- This allows us to be always up to date with upstream `@mdxjs` and all the `unified` ecosystem (vfile, unified, remark, rehype, etc)
- Allows us to finally use `remark-gfm` plugin instead of handpicking a few versions and specific plugins and trying to make a live with it
- Removes complexity, simplifies the code, and gives better ownership for our needs.

The implementation is bare-bones and very simple, and it works fantastically.

## Validation

Pages should be rendering as usual

2023-10-31 11:44 UTC, bmuenzenmeyer requested changes, later dismissed
js syntax highlighting is not working

✅ https://nodejs.org/en/learn/manipulating-files/working-with-folders-in-nodejs
❌ https://nodejs-org-git-feat-next-14-lightweight-mdx-compiler-openjs.vercel.app/en/learn/manipulating-files/working-with-file-descriptors-in-nodejs

❌ https://nodejs-org-git-feat-next-14-lightweight-mdx-compiler-openjs.vercel.app/en/about is not loading for me

❌ blog post is not rendering https://nodejs-org-git-feat-next-14-lightweight-mdx-compiler-openjs.vercel.app/en/blog/vulnerability/openssl-fixes-in-regular-releases-oct2023

2023-10-31 11:44 UTC, bmuenzenmeyer commented on next.dynamic.mjs
> +  console.log(filename);
do you intend to leave  these console logs here?
```suggestion
```

2023-10-31 11:44 UTC, bmuenzenmeyer commented on next.dynamic.mjs
> +    console.time('createVFile');
```suggestion
```

2023-10-31 11:44 UTC, bmuenzenmeyer commented on next.dynamic.mjs
> +
```suggestion
```

2023-10-31 11:44 UTC, bmuenzenmeyer commented on next.dynamic.mjs
> +
```suggestion
```

2023-10-31 23:58 UTC, ovflowd commented
@bmuenzenmeyer feel free to re-review this ✨

2023-11-01 09:15 UTC, AugustinMauroy approved these changes
STMG

2023-11-01 15:15 UTC, canerakdas approved these changes
LGTM, I compared the preview with nodejs.org. Also, fixes the markdown formatted tables

2023-11-01 15:27 UTC, merged