feat: sentry
nodejs/nodejs.org pull request #6099
Opened 2023-11-08 17:20 UTC by ovflowd

## Description

Introduces Sentry to the Node.js Website (Server-side, Edge-functions and Client-side)

2023-11-08 17:29 UTC, ovflowd commented
cc @nodejs/web-infra for review and approval ✅

2023-11-08 17:52 UTC, flakey5 approved these changes

2023-11-08 21:15 UTC, AugustinMauroy approved these changes
LGTM !
i din't use a lot sentry but it's great tool

2023-11-09 02:34 UTC, canerakdas approved these changes

2023-11-09 04:15 UTC, bmuenzenmeyer requested changes
I'm really excited for this!

In addition to my comments, can you also add to https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website perhaps?

2023-11-09 04:15 UTC, bmuenzenmeyer commented on next.config.mjs
> +);
I've grown really accustomed to how great our documentation is.

To familiarize myself with the tool a bit more, I've added suggestions for each

2023-11-09 04:15 UTC, bmuenzenmeyer commented on next.config.mjs
> +    widenClientFileUpload: true,
```suggestion
    // upload Next.js or third-party code in addition to our code
    widenClientFileUpload: true,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on next.config.mjs
> +    transpileClientSDK: true,
```suggestion
    // transpile the Sentry code too since we target older browsers in our .browserslistrc
    transpileClientSDK: true,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on next.config.mjs
> +    tunnelRoute: '/monitoring',
```suggestion
    // attempt to circumvent ad blockers 
    tunnelRoute: '/monitoring',
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on next.config.mjs
> +    hideSourceMaps: false,
```suggestion
    // prevent source map comments in built files
    hideSourceMaps: false,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.client.config.ts
> +  debug: false,
this is the default https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/options/#debug
```suggestion
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.client.config.ts
> +  tracesSampleRate: 1,
```suggestion
  // percentage of events to send to Sentry (all of them)
  tracesSampleRate: 1,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.client.config.ts
> +  dsn: SENTRY_DSN,
```suggestion
  // tell Sentry where to send events
  dsn: SENTRY_DSN,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.client.config.ts
> +  replaysOnErrorSampleRate: 1.0,
```suggestion
  // percentage of errors to sample (all of them)
  replaysOnErrorSampleRate: 1.0,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.client.config.ts
> +  replaysSessionSampleRate: 0.1,
```suggestion
  // percentage of sessionsto sample (10%)
  replaysSessionSampleRate: 0.1,
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.client.config.ts
> +  integrations: [new Replay({ maskAllText: true, blockAllMedia: true })],
We don't have any PII here - we should capture what is actually on the screen

https://docs.sentry.io/platforms/javascript/guides/nextjs/session-replay/privacy/

```suggestion
  integrations: [new Replay()],
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.edge.config.ts
> +init({ dsn: SENTRY_DSN, tracesSampleRate: 1, debug: false });
debug: false is the default

```suggestion
init({ dsn: SENTRY_DSN, tracesSampleRate: 1 });
```

2023-11-09 04:15 UTC, bmuenzenmeyer commented on sentry.server.config.ts
> +init({ dsn: SENTRY_DSN, tracesSampleRate: 1, debug: false });
debug: false is the default

```suggestion
init({ dsn: SENTRY_DSN, tracesSampleRate: 1 });
```

2023-11-09 12:53 UTC, ovflowd commented
> In addition to my comments, can you also add to [main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md?rgh-link-date=2023-11-09T04%3A15%3A37Z#technologies-used-in-the-website) perhaps?

Not relevant IMO. At least not to your average collaborator.

2023-11-09 13:16 UTC, ovflowd commented
cc @bmuenzenmeyer can you give an approval?

2023-11-09 13:22 UTC, bmuenzenmeyer approved these changes
looking great - dont really have a good way to test this so 🤞 

we can always hotfix if something is messed up

2023-11-09 13:24 UTC, ovflowd commented
cc @nodejs/web-infra let's get this merged as it's always great to have monitoring.

2023-11-09 13:24 UTC, merged