refactor: separate client and server/complex components
nodejs/nodejs.org pull request #6393
Opened 2024-03-02 15:02 UTC by ovflowd

## Description

This PR introduces the support of ChangelogModals within the Download's page of the redesigned Node.js Website

Note that this PR might increase the client bundle size 🤔 we should probably check how much of an increase it is.

## Validation

The "changelog button" should open a changelog with the correctly rendered MDX data.

2024-03-02 15:09 UTC, ovflowd commented
Note that this version of the ChangelogModal does not include the avatars of all contributors that made a release happen. We still need to hook this into some internal utility for getting the names of all release authors.

I remember @richardlau or @targos mentioning this, but I might be remembering this incorrectly 🤔

2024-03-03 02:12 UTC, mikeesto reviewed
On mobile there's a "X" in the top right to close the modal. I think it would be good to keep it their for a wider viewport too?

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/current.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/index.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/package-manager/current.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/package-manager/index.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/prebuilt-binaries/current.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/prebuilt-binaries/index.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/source-code/current.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on pages/en/download/source-code/index.mdx
> +Read the changelog for <Release.ChangelogLink>this verion</Release.ChangelogLink>
```suggestion
Read the changelog for <Release.ChangelogLink>this version</Release.ChangelogLink>
```

2024-03-03 02:12 UTC, mikeesto commented on util/getNodeJsChangelog.ts
> +  const [, changelogHeadinjg] = changelog.match(/^## (.*)$/m) || [];
```suggestion
  const [, changelogHeading] = changelog.match(/^## (.*)$/m) || [];
```

2024-03-03 02:12 UTC, mikeesto commented on util/getNodeJsChangelog.ts
> +  return changelogHeadinjg || '';
```suggestion
  return changelogHeading || '';
```

2024-03-03 20:10 UTC, canerakdas commented
I compared the page source sizes for the two versions:

[With changelog](https://nodejs-lhta2c4o3-openjs.vercel.app/en/download) modal;
Source size: `193.85 KB`

[Beta](https://beta-node-js-org.vercel.app/en/download) without changelog modal;
Source size: `86.65 KB`

----

In addition, when I check with `@next/bundle-analyzer`, the gzipped dimensions are as follows;

Server `feat/changelog-modal`;

<img width="478" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/730da094-620d-4b0f-aa21-34817e300bef">

Server `main`;

<img width="478" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/25c15ec6-de61-4cb9-b7ba-0e8ef1c29e9c">


Due to the nature of our page structure, it is not clear exactly what these parts affect. There seems to be an increase only on `../app/[locale]/[[...path]]/page.js`.

----

Client `feat/changelog-modal`;

<img width="478" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/003e8b76-5aed-4278-acfa-497f2a8d31e3">

Client `main`;

<img width="478" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/b8e0976a-2389-4abc-b65c-cddaba6e4a29">

I'm not sure exactly how we can reduce the size here, but I'll check it out as well (if it's possible) 👀

2024-03-04 12:25 UTC, ovflowd commented
> I compared the page source sizes for the two versions:
> 
> [With changelog](https://nodejs-lhta2c4o3-openjs.vercel.app/en/download) modal; Source size: `193.85 KB`
> 
> [Beta](https://beta-node-js-org.vercel.app/en/download) without changelog modal; Source size: `86.65 KB`
> 
> In addition, when I check with `@next/bundle-analyzer`, the gzipped dimensions are as follows;
> 
> Server `feat/changelog-modal`;
> 
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/14062599/309577267-730da094-620d-4b0f-aa21-34817e300bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTUzMjUsIm5iZiI6MTcwOTU1NTAyNSwicGF0aCI6Ii8xNDA2MjU5OS8zMDk1NzcyNjctNzMwZGEwOTQtNjIwZC00YjBmLWFhMjEtMzQ4MTdlMzAwYmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNDVjN2EwNTg0OWNiMTYwZTUxMWY1ZjlhYzkxYzhmZTk3Y2NmMjE3MTZkM2M5ZDFhYmYyNTQzOGE2OTYwMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.35ZMHDM6NUY0tgD3O6FYaq8PXqJGStNCVnGBixC9Te4">
> Server `main`;
> 
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/14062599/309577332-25c15ec6-de61-4cb9-b7ba-0e8ef1c29e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTUzMjUsIm5iZiI6MTcwOTU1NTAyNSwicGF0aCI6Ii8xNDA2MjU5OS8zMDk1NzczMzItMjVjMTVlYzYtZGU2MS00Y2I5LWI3YmEtMGU4ZWYxYzI5ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzU4NzE1NDgxMTAxZjQxYTQ5MTdjYWYyOTY5ZDYxZDc4NWM2NDZjZjE3YzM1YzE5YzI3YTQyOGNjODRkMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UupFJ4I0zAxxbLLKaPCM5Ic9SjGJI7PCkbeihsLukY">
> Due to the nature of our page structure, it is not clear exactly what these parts affect. There seems to be an increase only on `../app/[locale]/[[...path]]/page.js`.
> 
> Client `feat/changelog-modal`;
> 
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/14062599/309577289-003e8b76-5aed-4278-acfa-497f2a8d31e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTUzMjUsIm5iZiI6MTcwOTU1NTAyNSwicGF0aCI6Ii8xNDA2MjU5OS8zMDk1NzcyODktMDAzZThiNzYtNWFlZC00Mjc4LWFjZmEtNDk3ZjJhOGQzMWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMzVhODUxNGNhYTcyOTVlY2EyMmNhMmZhZGU0MmUwNjcwMWI1YzI0MTU4NjQ4MTMyMjZjMGJlMTEzNmU3YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJ-Q0i1_g_LXOwkodVw6I7UUkWL3U2HOYjQfV2xrUcc">
> Client `main`;
> 
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/14062599/309577355-b8e0976a-2389-4abc-b65c-cddaba6e4a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTUzMjUsIm5iZiI6MTcwOTU1NTAyNSwicGF0aCI6Ii8xNDA2MjU5OS8zMDk1NzczNTUtYjhlMDk3NmEtMjM4OS00YWJjLWI2NWMtY2RkYWJhNmU0YTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxY2VlMjJhMDAzZDUzYTkzZTVmYTFiMTNjNmVmNjUwMjA3OGU2NDhiOGM4M2JhYzNlZGE3MTEwZDQxODA1ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eHMiOMD-mbXwekPmy3nJ0ecPUbAIzzDM6F-JkHd5lwo">
> I'm not sure exactly how we can reduce the size here, but I'll check it out as well (if it's possible) 👀

If you can investigate that'd be great! It is indeed a big bundle increase, mostly (I assume) because it is also bundling the Shiki WASM and Languages and Theme on the client-side 🤔 

Can you check what's the bundle difference if we removed Shiki from the ChangelogModal?

2024-03-05 10:22 UTC, targos commented
Something feels weird with how the page seems to disappear entirely with no UI element to close the modal.

2024-03-05 10:28 UTC, ovflowd commented
> Something feels weird with how the page seems to disappear entirely with no UI element to close the modal.

Indeed, I assume we need to add an X button. Hmm. @canerakdas as I mentioned before, feel free to hijack this PR :)

2024-03-05 12:14 UTC, AugustinMauroy commented
In relation to what @targos said, I think we could make the background around the modal more transparent.

2024-03-08 03:44 UTC, bmuenzenmeyer requested changes
my opinion is that feature is not worth the code, bundle size, or UX experiences. why not link to the GitHub release?

it feels similar to #6369 - how will we resolve differences or deltas from the figma's vision and reality of implementation? do we still have the @nodejs/ux-and-design team? maybe we expand those ranks with some true UX professionals

2024-03-08 10:01 UTC, AugustinMauroy commented
>  how will we resolve differences or deltas from the figma's vision and reality of implementation? 

I think we should open a discussion/issue to find a way forward with the Figma and potential new features that won't be on this design. And also to know how to adapt the design to the real condition.

2024-03-08 15:32 UTC, richardlau commented
> my opinion is that feature is not worth the code, bundle size, or UX experiences. why not link to the GitHub release?

Stepping back a bit, what this is doing is trying to present the notes/lists of changes for the release to allow users of the site a way of finding out what changed or is notable about a particular release. In the redesign this is more or less covered by linking through to the blog post for the release. The blog posts are generated via [`scripts/release-post`](https://github.com/nodejs/nodejs.org/tree/main/scripts/release-post) based on content from the changelog over in the core nodejs/node repository.

If we look at the pre-redesign (i.e. current) website:
- https://nodejs.org/en/download neither links to the changelog nor the blog post.
- The download buttons on the homepage have links underneath to the changelogs on GitHub. These have been problematic because for some releases the file linked to is too large for GitHub to render in the web UI (see for example https://github.com/nodejs/nodejs.org/issues/4816 -- there was also a suggestion there to link to the GitHub release but that's also had size limitations).
- https://nodejs.org/en/about/previous-releases also links to the changelogs on GitHub.
- None of the pages AFAICT link to the blog posts.

So the redesign is already doing something the pre-redesign site did not -- i.e. it presents the changelog information by linking to the blog posts. I think we should keep linking to the blog posts in the redesign and do not need to repeat the information by linking to the changelogs.

2024-03-08 15:46 UTC, ovflowd commented
Right, the intent of this PR was to solve the issue we have of changelog rendering on GitHub.

But it would only cover/handle cases for the current LTS and current releases, afaik.

Since these changelogs use the same content as from the blog posts, probably it is good enough to just have the link to the release post.

One of the other goals of this Modal, was to have a collection of GitHub avatars rendering, that showcase all the committers that made said release possible, and pretty much highlight their contributions.

I think we could still add this, but directly to the Download page, maybe below the header?

Wdyt @nodejs/nodejs-website 

Regarding lack of designers, well, at this point since we do not have anyone here volunteering that works in that field, we lack the experts to assess such cases.

(Also @richardlau I pinged you here because I recall you mentioning there was a way to get a list of all committers of a release, can you point me to the right direction?)

2024-03-08 15:49 UTC, richardlau commented
> (Also @richardlau I pinged you here because I recall you mentioning there was a way to get a list of all committers of a release, can you point me to the right direction?)

👀 I don't recall that.

2024-03-08 16:46 UTC, AugustinMauroy commented
> One of the other goals of this Modal, was to have a collection of GitHub avatars rendering, that showcase all the  committers that made said release possible, and pretty much highlight their contributions.
> 
> I think we could still add this, but directly to the Download page, maybe below the header?

@ovflowd I didn't really get your idea, you want to have an `AvatarGroup` on `BlogHeader` with list of contributor ? and set aside the modal?

2024-03-08 17:57 UTC, ovflowd commented
> > One of the other goals of this Modal, was to have a collection of GitHub avatars rendering, that showcase all the  committers that made said release possible, and pretty much highlight their contributions.
> > I think we could still add this, but directly to the Download page, maybe below the header?
> 
> @ovflowd I didn't really get your idea, you want to have an `AvatarGroup` on `BlogHeader` with list of contributor ? and set aside the modal?

No. I want AvatarGroup on Download page, that's what I wrote on my comment

2024-03-08 19:52 UTC, ovflowd commented
> > (Also @richardlau I pinged you here because I recall you mentioning there was a way to get a list of all committers of a release, can you point me to the right direction?)
> 
> 👀 I don't recall that.

Oh, maybe I talked about that with someone else, but I recall our generated CHANGELOG (GitHub) contains the name of the commuters from their GitHub accounts, do you know where we do get that? Maybe cc @nodejs/releasers know?

2024-03-08 20:12 UTC, richardlau commented
> > > (Also @richardlau I pinged you here because I recall you mentioning there was a way to get a list of all committers of a release, can you point me to the right direction?)
> > 
> > 
> > 👀 I don't recall that.
> 
> Oh, maybe I talked about that with someone else, but I recall our generated CHANGELOG (GitHub) contains the name of the commuters from their GitHub accounts, do you know where we do get that? Maybe cc @nodejs/releasers know?

[changelog-maker](https://github.com/nodejs/changelog-maker) pulls the information out of the git commits.

2024-03-10 17:11 UTC, canerakdas commented
While examining the size of the page here, I noticed that all releases and changelogs were added to the page because we added the changelogs to the release in reducer. To reduce the size of the page, I have removed the changelog from the release and made it accessible via `next-data` 🎉 

Source size:
`89.19 KB`

2024-03-17 11:01 UTC, ovflowd commented
@canerakdas could you rebase? And @bmuenzenmeyer could you re-review?

2024-03-17 23:06 UTC, ovflowd commented
@canerakdas I believe we need to reduce blur and add a close button. Also the changelog should only open after finishing fetching the data (IMO)

2024-03-18 15:52 UTC, canerakdas commented
I think it looks better/accessible now, you can check it in the Vercel preview 👀 @ovflowd

Before:
<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/c74d8cea-6cdb-4933-bc7d-ee762b52af0d">

After:
<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/da4175f1-1cea-4660-92ec-184f794d7ce8">

Before/Dark:
<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/61b26026-aa7b-47fd-8a3c-2d39d484351e">

After/Dark:
<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/a1c992bd-78c0-422d-8018-09aa2beb02e8">

2024-03-18 15:55 UTC, ovflowd commented
Awesome! Would it also bee too much to ask you to check into what Richard mentioned ([changelog-maker](https://github.com/nodejs/changelog-maker) pulls the information out of the git commits.) for getting the full list of GitHub usernames for the "AvatarGroup" on the modal?

2024-03-24 12:18 UTC, ovflowd commented
I believe we can merge this as it is; But we need reviews cc @bmuenzenmeyer @nodejs/nodejs-website

2024-03-24 13:40 UTC, araujogui approved these changes

2024-03-25 00:09 UTC, bmuenzenmeyer requested changes
small accessibility bug to fix


https://github.com/nodejs/nodejs.org/assets/298435/2ac68983-69d7-4c27-b96b-f09ce453fc06

2024-03-25 19:20 UTC, canerakdas commented
Ah, I completely missed this, I solved it by wrapping it with a button. If we think we may encounter such situations more often, it seems like we can use [Radix primitive slot](https://www.radix-ui.com/primitives/docs/utilities/slot)

2024-03-25 20:36 UTC, bmuenzenmeyer approved these changes
🤝

2024-03-25 20:39 UTC, merged