Fix #6404 : Version dropdown on download page doesn't scroll on overflow
nodejs/nodejs.org pull request #6411
Opened 2024-03-03 08:19 UTC by MohitKambli

## Description
Hello,
Hope you're doing well.
This PR has been raised to fix issue #6404, wherein the scroll down feature for versions doesn't work as it actually should.
In order to provide a fix for the same, I have added style property to the **_Primitive.Content_** component for which **_maxHeight_** and **_overflowY_** properties have been defined in the **_index.tsx_** file located at _**components/Common/Select**_.

## Validation
In order to confirm if the scroll feature works as per requirement, I started the server locally and checked if the desired behaviour has been achieved or not.
Following are the screenshots of the updated dropdown component:
1) 
![image](https://github.com/nodejs/nodejs.org/assets/31406633/d9915775-3f5f-4b50-9a1b-480f79b05976)

2)
![image](https://github.com/nodejs/nodejs.org/assets/31406633/9cb10129-fbcd-4b97-8527-be00b73758d2)

If at all there are any changes required from my end, then do let me know.
Sincere apologies if I made any mistakes while resolving this issue and raising a PR for the same.

## Related Issues
Fixes #6404

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I've covered new added functionality with unit tests if necessary.

2024-03-03 08:49 UTC, AugustinMauroy requested changes
Please use css-module and tailwindcss.

2024-03-03 16:39 UTC, MohitKambli commented
Hello @AugustinMauroy,
I have made the necessary changes in the index.module.css file.
If at all there is something else that I need to do, then do let me know.
Sincere apologies for messing up in the previous commit and for my mistakes if you find any in the new commit.
Thank you so so much for understanding my part.

Thanks and Regards,
Mohit Kambli

2024-03-03 19:34 UTC, AugustinMauroy commented on components/Common/Select/index.module.css
>    @apply max-w-xs
```suggestion
  @apply max-h-48
    overflow-y-auto
    max-w-xs
```

You can simplify doing that. Also don't miss to `npx turbo format`

2024-03-03 19:35 UTC, AugustinMauroy commented on components/Common/Select/index.tsx
> +            style={{ maxHeight: '200px', overflowY: 'auto' }}
```suggestion
```
You can totally remove this line

2024-03-03 20:13 UTC, MohitKambli commented
Hello @AugustinMauroy,
As you had mentioned in the comments, I incorporated the code changes.
If at all there is something else required from my end, then do let me know.
Sincere apologies for the trouble being caused.

Thanks and Regards,
Mohit Kambli

2024-03-03 20:15 UTC, ovflowd commented
> Hello @AugustinMauroy, As you had mentioned in the comments, I incorporated the code changes. If at all there is something else required from my end, then do let me know. Sincere apologies for the trouble being caused.
> 
> Thanks and Regards, Mohit Kambli

I'd appreciate if you did not use AI/ChatGPT based solutions for generating your comments.

2024-03-03 20:20 UTC, MohitKambli commented
> > Hello @AugustinMauroy, As you had mentioned in the comments, I incorporated the code changes. If at all there is something else required from my end, then do let me know. Sincere apologies for the trouble being caused.
> > Thanks and Regards, Mohit Kambli
> 
> I'd appreciate if you did not use AI/ChatGPT based solutions for generating your comments.

Hello @ovflowd,
No, I don't use AI/ChatGPT at all to write my comments.
It has just become a habit of writing something like this after every mistake/commit I contribute to the Open Source Repositories.
That's just how I am.

Thanks and Regards,
Mohit Kambli

2024-03-04 09:59 UTC, AugustinMauroy commented
> Sincere apologies for messing up in the previous commit and for my mistakes if you find any in the new commit.

There's nothing to worry about! This is your first contribution, and we have a very strict guiding style which helps maintain the website.

2024-03-04 10:00 UTC, AugustinMauroy approved these changes
LGTM ! Thanks for you first contribution 🎉

2024-03-04 10:01 UTC, AugustinMauroy commented
I'm requiring fast-tracking 'cause it's download page is difficult to use without this change.

2024-03-04 10:02 UTC, aymen94 approved these changes

2024-03-04 12:36 UTC, merged