chore: Translation setup for: Swedish, Finnish, Dutch and Hindi
nodejs/nodejs.org pull request #6531
Opened 2024-03-24 15:45 UTC by MateuszS0

## Description

Added localization for languages: Swedish, Finnish, Dutch and Hindi to the i18n/config.json.

## Validation
## Related Issues
no issues

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

2024-03-28 13:38 UTC, aymen94 approved these changes

2024-06-15 13:20 UTC, bmuenzenmeyer requested changes
[Swedish](https://github.com/nodejs/nodejs.org/pull/6530)and [Hindi](https://github.com/nodejs/nodejs.org/pull/6572)were added out from under this PR. 

Can you adjust this PR to only add Finnish and Dutch? 
Additionally, please English-alphabetize by `code`

2024-06-15 15:09 UTC, bmuenzenmeyer approved these changes

2024-06-15 15:22 UTC, merged

2024-06-15 15:24 UTC, bmuenzenmeyer commented
Finnish and Dutch added in Crowdin