Add author image to blog posts
nodejs/nodejs.org pull request #6581
Opened 2024-03-28 19:01 UTC by joaoGabriel55

## Description

Instead of the initials of each author, now use the GitHub image for each author

## Validation

<img width="876" alt="image" src="https://github.com/nodejs/nodejs.org/assets/23138717/35fd20e4-036c-4477-bff0-3cbd46c828f0">

## Related Issues

Related to #6573

### Check List

- [ ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing.
- [ ] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

2024-03-28 21:35 UTC, AugustinMauroy requested changes
At moment this not solve issue. you just remove initial and put nodejs org profile picture.

So like say on the issue. My opinion it's to use front matter to have profile picture and if it's nodejs project -> use nodejs org as username. And make small work on markdown do verify if major of author is right username.

2024-03-28 23:16 UTC, ovflowd commented
Blog Posts do not have any username at the moment, so this isn't really fixing any issue unfortunately.

We should probably open an issue to keep track of the problem and actually come with a long-term solution.

Unfortunately, not all blog authors have a GitHub account... And we have blog posts from back 2011.

Here's a full list of all blog authors and usernames when available: https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml

Feel free to make a script to replace the existing names to usernames on all blog posts, and then update the script that creates release blog posts to use username instead of name ;)

Then this solution is viable. But we still need their names, so 🤷 if you're feeling like spending time into this, go ahead! It's appreciated

2024-03-29 07:45 UTC, AugustinMauroy commented
> We should probably open an issue to keep track of the problem and actually come with a long-term solution.

Could you do it ?

> Here's a full list of all blog authors and usernames when available:  https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml

I thinks it's will easier to follow you proposal. But use JSON instead of yaml it's can be link to `next.json.mjs`.

2024-03-29 10:17 UTC, ovflowd commented
> > We should probably open an issue to keep track of the problem and actually come with a long-term solution.
> 
> Could you do it ?
> 
> > Here's a full list of all blog authors and usernames when available:  [nodejs/nodejs.dev@`main`/src/data/blog/authors.yaml](https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml?rgh-link-date=2024-03-29T07%3A45%3A47Z)
> 
> I thinks it's will easier to follow you proposal. But use JSON instead of yaml it's can be link to `next.json.mjs`.

Not everything needs to be done by me 🙈

2024-03-29 17:42 UTC, joaoGabriel55 commented
> Blog Posts do not have any username at the moment, so this isn't really fixing any issue unfortunately.
> 
> We should probably open an issue to keep track of the problem and actually come with a long-term solution.
> 
> Unfortunately, not all blog authors have a GitHub account... And we have blog posts from back 2011.
> 
> Here's a full list of all blog authors and usernames when available: https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml
> 
> Feel free to make a script to replace the existing names to usernames on all blog posts, and then update the script that creates release blog posts to use username instead of name ;)
> 
> Then this solution is viable. But we still need their names, so 🤷 if you're feeling like spending time into this, go ahead! It's appreciated

Maybe we could still use the avatar with initial letters if the blog post does not have a username field otherwise we can use this new approach.

2024-03-29 17:56 UTC, AugustinMauroy commented
basically, there is https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml which is a list that transfers the string that is in authors FrontMatter into a link. All you need to do is put it in JSON instead of YAML.

2024-03-29 17:57 UTC, joaoGabriel55 commented
That would be my proposal:
```ts
export const mapAuthorToCardAuthors = (author: string, username?: string) => {
  const authors = author.split(/, | and |;| by /i);
  const usernames = username?.split(/, | and |;| by /i) || [];

  return authors.map((fullName, index) => {
    let src = `https://ui-avatars.com/api/?name=${fullName}`;

    if (username) src = `https://github.com/${usernames[index]}.png?size=40`;

    return { fullName, src };
  });
};
```

2024-03-29 17:57 UTC, joaoGabriel55 commented
> basically, there is https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml which is a list that transfers the string that is in authors FrontMatter into a link. All you need to do is put it in JSON instead of YAML.

I see

2024-03-29 18:18 UTC, joaoGabriel55 commented
> basically, there is https://github.com/nodejs/nodejs.dev/blob/main/src/data/blog/authors.yaml which is a list that transfers the string that is in authors FrontMatter into a link. All you need to do is put it in JSON instead of YAML.

So just to confirm @AugustinMauroy, in the `blogUtils.ts` we will need to map the `fullname` of the author with the author name in the new JSON file generated by the `authors.yaml` file, right?

2024-03-29 19:09 UTC, AugustinMauroy commented
Oh cool !
note:
- "the node.js project" have 404 GitHub image
- "Brian Muenzenmeyer" is missing on json https://github.com/bmuenzenmeyer
- "Marco Ippolito" is missing on json https://github.com/marco-ippolito
- "Ulises Gascón" is missing on json https://github.com/UlisesGascon
-  "Juan José Arboleda" is on JSON but there are also "Juan José" on frontMatter so you should do something to merge it
- "Claudio Wunder" is missing on json https://github.com/ovflowd
- "Matt Cowley" is missing on json https://github.com/MattIPv4
- "ryandahl" isn't working

2024-03-29 19:10 UTC, AugustinMauroy commented on authors.json
> +  },
```suggestion
```

Manish isn't a blog author

2024-03-29 20:01 UTC, joaoGabriel55 commented
> Oh cool ! note:
> 
> * "the node.js project" have 404 GitHub image
> * "Brian Muenzenmeyer" is missing on json https://github.com/bmuenzenmeyer
> * "Marco Ippolito" is missing on json https://github.com/marco-ippolito
> * "Ulises Gascón" is missing on json https://github.com/UlisesGascon
> * "Juan José Arboleda" is on JSON but there are also "Juan José" on frontMatter so you should do something to merge it
> * "Claudio Wunder" is missing on json https://github.com/ovflowd
> * "Matt Cowley" is missing on json https://github.com/MattIPv4
> * "ryandahl" isn't working

Is the Ryan Dahl who has the GitHub username 'ry' the same person as 'ryandahl'?

2024-03-30 16:16 UTC, Cloudstream-io reviewed
Hi looks good

2024-03-30 16:17 UTC, ovflowd commented
> > Oh cool ! note:
> 
> > 
> 
> > * "the node.js project" have 404 GitHub image
> 
> > * "Brian Muenzenmeyer" is missing on json https://github.com/bmuenzenmeyer
> 
> > * "Marco Ippolito" is missing on json https://github.com/marco-ippolito
> 
> > * "Ulises Gascón" is missing on json https://github.com/UlisesGascon
> 
> > * "Juan José Arboleda" is on JSON but there are also "Juan José" on frontMatter so you should do something to merge it
> 
> > * "Claudio Wunder" is missing on json https://github.com/ovflowd
> 
> > * "Matt Cowley" is missing on json https://github.com/MattIPv4
> 
> > * "ryandahl" isn't working
> 
> 
> 
> Is the Ryan Dahl who has the GitHub username 'ry' the same person as 'ryandahl'?

Yes!

2024-04-02 17:05 UTC, AugustinMauroy approved these changes
LGMT !! Thanks for your contribution

2024-04-06 16:33 UTC, canerakdas approved these changes
LGTM 🚀 🐢 

This is not related to this PR, but at some point, it may be more efficient to use the `next/image` component together with the `RadixAvatar.Image` component

2024-04-06 20:09 UTC, bmuenzenmeyer approved these changes
cool stuff - thanks!

2024-04-06 20:15 UTC, merged