Update h1 so that it is visible
nodejs/nodejs.org pull request #6605
Opened 2024-04-03 01:06 UTC by mikolertesx

## Description

Removed web-text-fill-color:transparent.

## Validation

Select the title text, and click outside the browser so that it looses focus.

**Before**
![imagen](https://github.com/nodejs/nodejs.org/assets/13491373/d078b2f9-dde2-4e77-b8a2-4a9e80b0e685)

**After**
![imagen](https://github.com/nodejs/nodejs.org/assets/13491373/263fe590-d3a5-456e-a6b4-6e7e019e450c)

## Related Issues
Fixes #6585 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

2024-04-03 07:21 UTC, AugustinMauroy requested changes
You need to found another solution because it's break the gradient effect on safari.

2024-04-03 20:08 UTC, mikolertesx commented
> You need to found another solution because it's break the gradient effect on safari.

https://stackoverflow.com/questions/46309641/what-happens-in-safari-with-the-transparent-color
This thread seems relevant to this.

Sadly, I don't have access to a computer with Safari at the moment (working on Windows here).
Would it be possible for you to try it with this instead? This one still works for me on Firefox (Windows version).

2024-04-03 20:37 UTC, AugustinMauroy commented
@mikolertesx I think your solution work for you (I'm not able to reproduce your issue on my machine)

2024-04-03 20:48 UTC, mikolertesx commented
> @mikolertesx I think your solution work for you (I'm not able to reproduce your issue on my machine)

No, I made a mistake, since you have to re-run the app so that CSS compiles again.

This is a way more complicated issue than I originally thought.
I can't fix it with my current knowledge.

I have to remove -webkit-text-fill-color so that it doesn't remove the text on Firefox. But doing so breaks Safari.

I imagine something can be done with ::before, and ::after.

2024-04-03 20:49 UTC, closed without merging

2024-04-03 20:49 UTC, mikolertesx commented
I'll close this if you don't mind.

2024-04-03 20:52 UTC, ovflowd commented
> No, I made a mistake, since you have to re-run the app so that CSS compiles again.

Only the global styles, apparently. For some reason (no idea why HMR is not working there, we should probably open an issue)

> I have to remove -webkit-text-fill-color so that it doesn't remove the text on Firefox. But doing so breaks Safari.

Indeed it is a complex issue :melt:

2024-04-03 21:09 UTC, mikolertesx commented
This would also be my first open-source contribution, I'm just not ready for this haha. 😤

2024-04-04 06:32 UTC, AugustinMauroy commented
> This would also be my first open-source contribution, I'm just not ready for this haha. 😤

you're welcome to make another contribution. Unfortunately, you've come across some very strange behaviour.