build(script): use `dev` instead of `serve`
nodejs/nodejs.org pull request #6674
Opened 2024-04-25 15:26 UTC by AugustinMauroy

## Description

I propose to change `serve` to `dev` because it's not serving the site. It's just create a dev environment.
Also on docs I had remove an obsolete mention.

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npm run format` to ensure the code follows the style guide.
- [X] I have run `npm run test` to check if all tests are passing.
- [X] I have run `npx turbo build` to check if the website builds without errors.
- **NA** I've covered new added functionality with unit tests if necessary.

2024-04-25 15:27 UTC, ovflowd commented
I think this is the 3rd time you open a PR proposing the rename of this command. The answer before was NO and it is still a NO.

There is no reason to change and we have kept it this way as it was the name before and people are used to it; changing it now has no meaningful impact.

2024-04-25 15:28 UTC, ovflowd requested changes
.

2024-04-25 15:30 UTC, AugustinMauroy commented
> I think this is the 3rd time you open a PR proposing the rename of this command. The answer before was NO and it is still a NO.

I've never opened a pr. But suggest.

> There is no reason to change and we have kept it this way as it was the name before and people are used to it; changing it now has no meaningful impact.

Yes, there is a home for former contributors. But for new contributors it's strange because ‘the convention’ next makes `dev` the usual command.

2024-04-25 15:34 UTC, ovflowd commented
> I've never opened a pr. But suggest.

My bad then.

> Yes, there is a home for former contributors. But for new contributors it's strange because ‘the convention’ next makes dev the usual command.

You can still run next dev. NPM scripts have nothing to do with Next.js; Have you seen anyone complaining about the command being called "serve" besides yourself? It's on the top of the README, I doubt people are doing this incorrectly and if they are they will quickly make it right once they read the README.

> And we have to bear in mind that serve is not the right term/is no longer appropriate.

No? We are starting a dev server and *serving* files. How is the name not appropriate?

2024-04-25 15:36 UTC, AugustinMauroy commented
> You can still run next dev. NPM scripts have nothing to do with Next.js; Have you seen anyone complaining about the command being called "serve" besides yourself? It's on the top of the README, I doubt people are doing this incorrectly and if they are they will quickly make it right once they read the README.

I have to admit that you're right about that.

> No? We are starting a dev server and serving files. How is the name not appropriate?

1. because if you go to the next doc it calls it a development environment 
2. Because there is the HMR principle
3. The pure serve is the fact that there is no code executed on the server, which is not the case.

2024-04-25 15:43 UTC, ovflowd commented
I believe you are having some language barriers here. "Serve" has nothing to do with the word "server" specifically in this context...

2024-04-25 15:46 UTC, AugustinMauroy commented
> I believe you are having some language barriers here. "Serve" has nothing to do with the word "server" specifically in this context...

For me, the term ‘serve’ in the context of an entry in the `package.json` means turning on/opening a server (rutime/software) which provides static files.

2024-04-25 15:48 UTC, MattIPv4 commented
Fwiw I am probably +1 to `dev` -- that is what I default to when looking for the right command to run locally for development.

2024-04-26 01:30 UTC, bmuenzenmeyer commented
I'm +1 on this change, because ["obvious always wins"](https://www.lukew.com/ff/entry.asp?1945)

In our case here, we are unapologetically stating we are using Next. To deviate from their common patterns is an oddity.

- [next quick start suggests `dev`](https://nextjs.org/docs/getting-started/installation)
- [next's comprehensive learning content suggests `dev`](https://nextjs.org/learn/dashboard-app/getting-started)

Can we simply support both? One alias to the other?

2024-04-26 06:38 UTC, AugustinMauroy commented
> Can we simply support both? One alias to the other?

I found that a good consensus! @ovflowd what do you think ?

2024-04-26 08:16 UTC, ovflowd commented
> I'm +1 on this change, because ["obvious always wins"](https://www.lukew.com/ff/entry.asp?1945)
> 
> In our case here, we are unapologetically stating we are using Next. To deviate from their common patterns is an oddity.
> 
> * [next quick start suggests `dev`](https://nextjs.org/docs/getting-started/installation)
> * [next's comprehensive learning content suggests `dev`](https://nextjs.org/learn/dashboard-app/getting-started)
> 
> Can we simply support both? One alias to the other?
> 
> I'm like a [6 outta 10 ](https://capwatkins.com/blog/the-sliding-scale-of-giving-a-fuck), but hope we can approach the problem with civility and a aim toward concensus.

Those are solid points, but although we use Next.js, we do want to keep the repository as neutral as possible and support existing contributors.

I believe having both commands (serve being the original and "dev" references "serve") a good compromise.

2024-04-26 08:17 UTC, ovflowd commented
For reference, I'm usually against doing changes based on the hypothetical that someone somewhere will ever have such issue, before anyone ever reported that they see such issue; It's overengineering.

2024-04-26 12:40 UTC, MattIPv4 commented
> before anyone ever reported that they see such issue

Feel free to take my comments here as such a report -- I've repeatedly run dev locally and been confused, then had to remember that this uses the non-standard serve instead.

2024-04-26 14:27 UTC, bmuenzenmeyer commented
> Feel free to take my comments here as such a report -- I've repeatedly run dev locally and been confused, then had to remember that this uses the non-standard serve instead.

so have I

2024-04-26 14:28 UTC, bmuenzenmeyer commented
I just want to add that I am glad we can come to an agreement - the project is better off when all of our perspectives are heard

2024-04-28 11:16 UTC, bmuenzenmeyer approved these changes
tested locally

2024-04-30 18:00 UTC, ovflowd approved these changes

2024-05-01 03:02 UTC, merged