Update getNodeDownloadUrl.ts
nodejs/nodejs.org pull request #7242
Opened 2024-11-19 14:44 UTC by CodingRule

Technically the same thing I did to PR #7241

2024-11-19 14:45 UTC, CodingRule commented
If the comments are wrote wrongly please tell me!

2024-11-19 14:49 UTC, RedYetiDev commented on apps/site/util/getNodeDownloadUrl.ts
Looking at the comparison, I think the switch statement is much cleaner.

2024-11-19 14:49 UTC, CodingRule commented on apps/site/util/getNodeDownloadUrl.ts
Ah okay

2024-11-19 14:50 UTC, CodingRule commented on apps/site/util/getNodeDownloadUrl.ts
Any good paths I could take into making this better than the switch cases ? (;

2024-11-19 16:06 UTC, RedYetiDev commented on apps/site/util/getNodeDownloadUrl.ts
What's wrong with the switch statement?

2024-11-19 16:07 UTC, CodingRule commented on apps/site/util/getNodeDownloadUrl.ts
Yeah true ig.
Thx anyway for review

2024-11-19 16:12 UTC, RedYetiDev commented on apps/site/util/getNodeDownloadUrl.ts
No problem! Feel free to look at the issues tab for things that need to be fixed. "Help wanted" and "good first issue" are places to start.

2024-11-19 16:18 UTC, AugustinMauroy commented on apps/site/util/getNodeDownloadUrl.ts
> Looking at the comparison, I think the switch statement is much cleaner.

Same feeling

2024-11-19 20:43 UTC, RedYetiDev requested changes
Based on my comment above, I dont think this should land in its current form.

2024-11-20 06:27 UTC, closed without merging

2024-11-20 19:39 UTC, ovflowd reviewed
Not gonna lie, I actually was a fan of this PR, it looked way cleaner than the switch statement :)

Feel free to reopen it.

2024-11-20 19:41 UTC, RedYetiDev commented
I'm still -1. I think that the switch statement is cleaner, but if you disagree. I won't block.