Update accept-input-from-the-command-line-in-nodejs.md to use a promise
nodejs/nodejs.org pull request #7252
Opened 2024-11-20 11:25 UTC by heybosi

## Description

## Validation

## Related Issues

### Check List

- [ ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npm run format` to ensure the code follows the style guide.
- [ ] I have run `npm run test` to check if all tests are passing.
- [ ] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

2024-11-20 11:34 UTC, RedYetiDev requested changes
I have a few concerns:

1. There is no indication that this is experimental
2. This isn't formatted (I.e. spacing and capitalization)

I think, you can use code tabs to make this look cleaner

2024-11-20 11:47 UTC, avivkeller commented on apps/site/pages/en/learn/command-line/accept-input-from-the-command-line-in-nodejs.md
> +
```suggestion
console.log(`Hi ${name}!`);

rl.close()
```

2024-11-20 11:47 UTC, RedYetiDev commented on apps/site/pages/en/learn/command-line/accept-input-from-the-command-line-in-nodejs.md
> +```mjs
```suggestion
```mjs displayName="Promises API"
```

And change the other one accordingly

2025-02-23 15:51 UTC, AugustinMauroy commented
bump @heybosi

2025-03-19 20:06 UTC, avivkeller commented
Hi, @heybosi! This hasn't seen any activity in a while, and so I'm closing this PR. Feel free to comment / re-open if you get back to this.

Thank you for your contribution!

2025-03-19 20:06 UTC, closed without merging