Getting started page is added in docs/guides
nodejs/nodejs.org pull request #888
Opened 2016-09-07 19:20 UTC by pushpendupurkait

In this page we are showing some steps to check node version and running
    JavaScript code with Node.js

2016-09-08 09:28 UTC, pushpendupurkait commented
@fhemberger , please take a look at the page and inform me if further changes are required.

2016-09-14 18:59 UTC, fene commented on locale/en/docs/guides/getting-started.md
> +First we have to make sure that Node.js is correctly installed in you
*on your system

2016-09-14 18:59 UTC, fene commented on locale/en/docs/guides/getting-started.md
> +Then we will run a small JavaScript code using node.
`Then we will run a short piece of JavaScript code using node`

2016-09-14 19:00 UTC, fene commented on locale/en/docs/guides/getting-started.md
> +**Test node:** To check if Node is installed properly in you system,
again, `your system`

2016-09-14 19:00 UTC, fene commented on locale/en/docs/guides/getting-started.md
> +**Create a test file and run it:** This is the easiest way to check Node.js
`to check if Node.js is installed on your system1

2016-09-14 19:01 UTC, ghost requested changes
please fix these spelling mistakes, thank you!

2016-09-15 06:31 UTC, pushpendupurkait commented
@fene , Sure
I'll make changes according to the comments. 
Thanks for the feedback

2016-09-15 13:02 UTC, pushpendupurkait commented
Hi, @fene 
I have made changes as suggested by you. please review it.

2016-09-16 07:16 UTC, fene commented
/cc @nodejs/evangelism can you have a look at this pleasE?

2016-09-20 06:07 UTC, pushpendupurkait commented
@fene 
Is there any other changes for the document ?

2016-09-20 14:19 UTC, Trott commented
I don't think this should be posted as a "Getting Started" page and I don't think it is sufficiently in depth to qualify as a guide. This content seems more like two steps one should take after installing. We don't seem to have an installation page (do we?) so maybe one should be created and this should be integrated into it.

At a minimum, if it's going to be a "Getting Started" page, it:

* should include a handful of simple but useful examples, such as one sees at https://howtonode.org/hello-node (Not all the examples on that page would be appropriate, although I think the first three would be.)
* should include a short list of places to go next to learn more about Node.js. Maybe a link to nodeschool.io, the API docs, something about working with npm, and a few similar resources or something like that.

So I think there are two options: Include this content as part of a larger "installation" page or expand it to make it more substantial.

2017-03-25 06:29 UTC, fhemberger commented
Agreeing with @Trott, please feel free to submit a more comprehensive version.

2017-03-25 06:29 UTC, closed without merging