locale: add translation to German
nodejs/nodejs.org pull request #971
Opened 2016-10-16 17:50 UTC by junedev

This PR is related to #807  and https://github.com/nodejs/nodejs-de/issues/27.
I created the "minimal set" for the translation to German. Following the advice in #807 this includes
- site.json
- index
- about/index
- docs/index
- download/index
- 404

For one of these pages (docs/index) @juliangruber started a translation end of last year. Since the text seemed not in sync any more and he never made a PR I just made a new translation based on the current English version.

For discussion:
- I used the casual not the formal version of addressing someone ("du", not "Sie").
  Example: "Oder wirf einen Blick auf den LTS Release Plan."
- If possible I gave German words (as used in some universities) precedence over the also used English words. My train of thought here was that if someone understands all the English terms the person might nearly be able to read the English version anyway. 
  Examples: Event Loop -> Ereignisschleife, callback function -> Rückruffunktion

Please help with pinging the right people who can review this.

2016-10-17 09:39 UTC, fhemberger requested changes
Sorry, I'll keep this in German. Discussing translations of your mother tongue in a foreign language gets a bit awkward.;)

---

Erstmal Danke für deine Mühe. Die Liste der Änderungen sieht schlimmer aus, als sie ist. Im Prinzip geht es um wenige Punkte:
- Es gibt kein Binnen-Leerzeichen im Deutschen bei zusammengesetzten Hauptwörtern, stattdessen wird ein Trennstrich verwendet ("Node Version" -> "Node-Version")
- Bei Nebensätzen mit "um … zu" muss ein Komma stehen
- "Community" würde ich als Begriff so stehen lassen, zumindest nicht mit "Gemeinde" übersetzen. Das ist in dem sprachlichen Kontext unpassend.

Die Frage wäre auch, ob man einige Fachbegriffe nicht auf Englisch lässt, da die deutsche Übersetzung doch etwas holprig klingt. Vielleicht kann ja jemand schauen, wie andere deutsche Publikationen zu Node.js mit dem Thema umgehen (z.B. O'Reilly).

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +    "reportNodeIssue": "Node.js Fehler melden",
"Node.js-Fehler"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +    "reportWebsiteIssue": "Websitenfehler melden",
"Webseitenfehler melden"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +    "all-downloads": "Alle Download Optionen",
"Alle Download-Optionen"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +            "text": "Node.js Blog"
"Node.js-Blog"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +            "text": "Node.js Blog: Versionen"
"Node.js-Blog"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +            "text": "Node.js Blog: Berichte über Sicherheitslücken"
"Node.js-Blog"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +            "text": "Node.js TSC Sitzungsprotokoll"
"Node.js TSC-Sitzungsprotokolle"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +            "text": "Ältere Versionen"
Vorschlag: "Alle Versionen"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +            "text": "Node.js mit dem Paketmanager installieren"
"Node.js mit Paketmanagern installieren" (gibt ja mehrere)

2016-10-17 09:39 UTC, fhemberger commented on locale/de/site.json
> +             "text": "In den Nachrichten"
Vorschlag: "In der Presse" (?)

2016-10-17 09:39 UTC, fhemberger commented on locale/de/index.md
> +Node.js® ist eine JavaScript Laufzeitumgebung, die auf  [Chromes V8 JavaScript Engine](https://developers.google.com/v8/) basiert.
"JavaScript-Laufzeitumgebung", "JavaScript-Engine"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/index.md
> +Durch ein Event-basiertes, blockierungsfreies I/O Modell ist Node.js schlank und effizient. Mit [npm](https://www.npmjs.com/) hat Node.js das größte Ökosystem für Open Source Bibliotheken der Welt.
"I/O-Modell" … den Satz könnte man aber vielleicht noch etwas anders formulieren.

2016-10-17 09:39 UTC, fhemberger commented on locale/de/download/index.md
> +        Lade den Node.js Quellcode oder ein bereits gebautes Installationsprogramm für deine Plattform herunter und beginne gleich mit der Entwicklung.
"Node.js-Quellcode"
Vorschlag: "oder ein bestehendes Installationsprogramm"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/download/index.md
> +    buildDisclaimer: "Hinweis: Um den von den Quelldateien (tarball) zu bauen wird Python 2.6 oder 2.7 benötigt."
"Hinweis: Um Node.js aus den Quelldateien (tarball) zu bauen, wird Python 2.6 oder 2.7 benötigt."

2016-10-17 09:39 UTC, fhemberger commented on locale/de/download/index.md
> +    currentVersion: Aktuellste LTS Version
"Aktuellste LTS-Version"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/download/index.md
> +        Mitglieder der Node.js Gemeinde pflegen inoffizielle, gebaute Versionen von Node.js für weitere Plattformen. Beachte, dass
"Node.js-Gemeinde", würde hier aber das englische "Community" verwenden:
a) Der Begriff ist im Deutschen weit verbreitet,
b) es geht hier nicht um kirchliche Angelegenheiten. ;)

2016-10-17 09:39 UTC, fhemberger commented on locale/de/download/index.md
> +        solche Versionen nicht vom Node.js Kernteam unterstützt werden und daher eventuell noch nicht auf dem selben Level wie die
"Node.js-Kernteam"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/download/index.md
> +        aktuelle Node.js Version sind.
"Node.js-Version"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +Unter Anleitungen finden sich lange, ausführliche Artikel über technische
~~lange, ~~

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +den Verhaltenskodex und das Governance Modell, wie man über GitHub und IRC Kontakt
"Governance-Modell"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +aufnehmen kann und wie man helfen kann Fehler ausfindig zu machen.
"wie man helfen kann, Fehler ausfindig zu machen."

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +Der [ES6 Bereich](/en/docs/es6/) beschreibt die drei Gruppen von ES6
"ES6-Bereich", "ES6-Funktionalitäten"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +welcher Node.js Version enthalten ist.
"Node.js-Version"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +Die API Referenz beschreibt Module, die in Node.js integriert sind. Module, die
"API-Referenz"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +von der Gemeinde zur Verfügung gestellt werden, sind dort nicht dokumentiert.
"~~Gemeinde~~Community"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +Die [API Referenz](/api/) stellt detaillierte Informationen über Funktionen und
"API-Referenz"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +Objekte in Node.js bereit. Diese Dokumentation zeigt, welche Argument die
"welche Argument**e**"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/docs/index.md
> +Methoden in den verschiedenen Node.js Versionen verfügbar sind.
"Node.js-Versionen"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +"Hallo Welt" Beispiel können viele Verbindungen gleichzeitig bearbeitet werden.
"Hallo Welt"-Beispiel

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +Bei jeder neuen Verbindung wird die Rückruffunktion ausgeführt. Gibt es jedoch
"Rückruffunktion" -> Ich würde hier beim technischen Begriff "Callback-Funktion" bleiben, das wird AFAIK auch so in der gängigen deutschsprachigen Node.js-Literatur so gehandhabt.

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +"Hallo Welt" Beispiel können viele Verbindungen gleichzeitig bearbeitet werden.
Vorschlag: "Verbindungen" -> "Anfragen" (= Request)

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +Zudem müssen sich Node Nutzer nicht um Deadlocks im Prozess sorgen, da es
"Node.js-Nutzer"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +keine Blockierung gibt. Fast keine Funktion in Node führt direkt I/O
"Node.js"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +keine Blockierung gibt. Fast keine Funktion in Node führt direkt I/O
"I/O-Operationen"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +[Event Machine][] oder Pythons [Twisted][]. Node führt das Event Modell noch
"Event-Modell"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +[Event Machine][] oder Pythons [Twisted][]. Node führt das Event Modell noch
Vorschlag: Ich würde zur besseren Lesbarkeit die Links in Anführungszeichen setzen, weil es sich um Eigennamen handelt:

Rubys "[Event Machine][]" oder Pythons "[Twisted][]"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +Aufruf notwendig um die Ereignisschleife zu starten. Üblicherweise wird das
"Aufruf notwendig, um die Ereignisschleife zu starten."

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +Node beginnt einfach mit der Ereignisschleife, nachdem das Eingabe Skript
"Eingabe-Skript"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +geringe Latenz. Dadurch ist Node sehr gut als Grundlage für Webbibliotheken
"Web-Bibliotheken"

2016-10-17 09:39 UTC, fhemberger commented on locale/de/about/index.md
> +Sockets gemeinsam zu nutzen um Lastverteilung über Kerne hinweg zu
"zu nutzen, um Lastverteilung über Kerne hinweg"

2016-10-17 19:57 UTC, junedev commented
Thanks @fhemberger for taking the time to mark all the missing dashes. Sorry for that. I updated the PR.
I don't have a better idea for the one sentence you mentioned to maybe rephrase but I hope this does not block the whole PR in case no one else comes up with a better idea.

2016-10-19 16:34 UTC, fhemberger approved these changes

2016-10-19 16:36 UTC, fhemberger commented
@junedev Okay, let's keep it that way for now. If someone has a good idea how to improve the sentence in question, they can submit another PR.

LGTM.

2016-10-19 16:36 UTC, merged

2016-10-20 18:04 UTC, junedev commented
@fhemberger Please see #988. Seems like a file was missing for making the translation appear correctly in production. "Worked in my machine" unfortunately.